/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithFormItemRequestBuilder, WithFormItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { LookupRequestBuilderRequestsMetadata, type LookupRequestBuilder } from './lookup/index.js';
// @ts-ignore
import { SlugCheckRequestBuilderRequestsMetadata, type SlugCheckRequestBuilder } from './slugCheck/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/forms
 */
export interface FormsRequestBuilder extends BaseRequestBuilder<FormsRequestBuilder> {
    /**
     * The lookup property
     */
    get lookup(): LookupRequestBuilder;
    /**
     * The slugCheck property
     */
    get slugCheck(): SlugCheckRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.forms.item collection
     * @param form Unique identifier of the item
     * @returns {WithFormItemRequestBuilder}
     */
     byForm(form: string) : WithFormItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const FormsRequestBuilderUriTemplate = "{+baseurl}/api/forms";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FormsRequestBuilderNavigationMetadata: Record<Exclude<keyof FormsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byForm: {
        navigationMetadata: WithFormItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["form"],
    },
    lookup: {
        requestsMetadata: LookupRequestBuilderRequestsMetadata,
    },
    slugCheck: {
        requestsMetadata: SlugCheckRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
