ignoredBuiltDependencies:
  - nx

onlyBuiltDependencies:
  - '@bitdisaster/exe-icon-extractor'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - electron
  - electron-winstaller
  - esbuild
  - lmdb
  - msgpackr-extract
