ignoredBuiltDependencies:
  - nx

onlyBuiltDependencies:
  - '@bitdisaster/exe-icon-extractor'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
