ignoredBuiltDependencies:
  - nx

onlyBuiltDependencies:
  - '@bitdisaster/exe-icon-extractor'
  - '@journeyapps/wa-sqlite'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - native-machine-id

blockExoticSubdeps: false

allowBuilds:
  '@bitdisaster/exe-icon-extractor': true
  '@parcel/watcher': true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  less: true
  lmdb: false
  msgpackr-extract: true
  nx: false
