import {stringify} from 'yaml';
import {from, map, mergeMap, filter, groupBy, reduce} from "rxjs";
import {set} from 'lodash';
import {join, resolve} from 'node:path';
import {mkdir, writeFile} from "node:fs/promises";
import {existsSync} from "fs";

const en = `
login.username=Username
login.forgot_password=Forgot password?
login.lets_continue_your_journey=Let's continue your Journey
login.password=Password
login.powered_by=Powered by
login.settings=Settings
login.sign_in=Sign in
login.welcome_back=Welcome back
settings.advanced.title=Advanced
settings.advanced.db.pwd=Password
settings.advanced.db.host=Host
settings.advanced.db.user=Username
settings.advanced.db.title=Database
settings.general=General
settings.language=Language
settings.language.en=English
settings.language.fr=French
settings.title=Settings
settings.advanced.db.port=Port
settings.msg.invalid_port=Invalid port number (Range: 1025 - 65535)
settings.msg.value_required=This field is required
settings.advanced.db.ssl=SSL
settings.advanced.storage.title=Storage
settings.msg.invalid_url=Invalid URL
settings.msg.value_too_short=Value is too short
settings.advanced.storage.endpoint=API Endpoint (S3 compatible)
settings.advanced.storage.access_key=Access key
settings.advanced.storage.secret_key=Secret key
settings.advanced.api.origin=API Origin
settings.advanced.api.title=API Settings
csc.add_new=Add New
shell.filter=Filter
shell.sign_out=Sign out
shell.menu.forms.fosa=FOSA Form
shell.menu.forms.chefferie=CHEFFERIE Form
fosa.submissions.title=Submissions
shell.menu.forms.title=Forms
fosa.add_submission=Add Submission
fosa.columns.validated=Is Valid
fosa.columns.recorded_at=Recorded at
fosa.columns.last_updated_by=Last updated by
fosa.columns.last_updated_at=Last updated at
fosa.form.filter=Filter
fosa.form.title=FOSA Submission
fosa.form.sections.respondent.title=Respondent
fosa.form.sections.respondent.description=Information about the respondent
forms.validation.msg.field_required=This field is required
fosa.form.sections.structure_identification.title=Structure identification
fosa.form.sections.reg_cs_events.title=Registration of civil status events
fosa.form.sections.infra_eq.title=Infrastructure and Equipment
fosa.form.sections.personnel_status.title=Personnel Status
fosa.form.fields.names.title=First and last names
fosa.form.fields.position.title=Function
fosa.form.fields.position.description=Position / function in the health facility
fosa.form.fields.phone.title=Phone number
fosa.form.fields.phone.description=Phone number (preferably WhatsApp)
fosa.form.fields.email.title=Email
fosa.form.fields.creation_date.title=Created at
fosa.form.fields.creation_date.description=Year of creation of the health facility (dd/MM/YYYY)
fosa.form.fields.email.description=Email address (work email)
forms.msg.invalid_value=Invalid value
fosa.form.fields.department.title=Division
fosa.form.fields.department.description=Division in the region
fosa.form.fields.communes.title=Town/City
fosa.form.fields.quarter.title=Neighborhood
fosa.form.fields.locality.title=Locality
fosa.form.fields.fosa_name.title=Facility name
fosa.form.fields.fosa_name.description=Full name of the FOSA facility
fosa.form.fields.district.title=Health district
fosa.form.fields.district.description=Associated health district
fosa.form.fields.health_area.title=Health area
fosa.form.fields.environment.title=Environment type
fosa.form.fields.fosa_type.title=Type of facility
fosa.form.fields.fosa_status.title=Status of the facility
fosa.form.fields.has_maternity.title=Has maternity
fosa.form.fields.has_maternity.description=Existence of a maternity ward in the health facility
fosa.form.fields.csc_reg.title=Associated CSC
fosa.form.fields.csc_reg.description=Local registry office
fosa.form.fields.distance_csc.title=CSC Proximity
fosa.form.fields.distance_csc.description=Average distance from the registry office
fosa.form.fields.environment.options.urban.title=Urban
fosa.form.fields.environment.options.rural.title=Rural
fosa.form.fields.region.title=Region
forms.footer.actions.finish=Save Changes
forms.footer.actions.discard=Discard Changes
fosa.columns.year=Year
fosa.columns.births=# of births registered
fosa.columns.deaths=# of deaths registered
fosa.columns.observation=Observations
fosa.form.fields.dhis2_usage.title=DHIS2 Usage
fosa.form.fields.dhis2_usage.description=Using DHIS2 in health training
fosa.form.fields.uses_bunec_birth_form.title=Uses BUNEC's Birth Form
fosa.form.fields.uses_bunec_birth_form.description=Registration of births on the standardized form provided by BUNEC
fosa.form.fields.uses_dhis2_form.title=Uses DHIS2 Forms
fosa.form.fields.uses_dhis2_form.description=Training in the use of the DHIS2 standardized form
fosa.form.fields.birth_declaration_transmission_to_csc.title=Birth Declarations to CSC
fosa.form.fields.birth_declaration_transmission_to_csc.description=Transmission of birth declarations to the registry office
fosa.form.fields.csc_event_reg_type.title=Record civil status events?
fosa.form.fields.csc_event_reg_type.description=How do you record civil status events?
fosa.form.fields.stats.title=Vital statistics for the last 5 years
controls.stats_collector.actions.add_new=Add
controls.stats_collector.actions.remove_selection=Remove selected
fosa.form.fields.toilet_present.title=Has Toilet?
fosa.form.fields.toilet_resent.description=Presence of accessible toilets for users in the facility
fosa.form.fields.has_eneo_connection.title=ENEO Connection?
fosa.form.fields.has_eneo_connection.description=Is the facility connected to the electricity grid (ENEO)?
fosa.form.fields.has_power_source.title=Has emergency Power Source?
fosa.form.fields.has_power_source.description=Does the center have an emergency or alternative source of power
fosa.form.fields.alternative_power.title=Backup Power Sources
fosa.form.fields.internet_conn.title=Has an Internet Connection?
fosa.form.fields.has_water_source.title=Alternative Water Source?
fosa.form.fields.has_water_source.description=Availability of an alternative water supply for the facility
fosa.form.fields.water_source.title=Water sources
controls.inventory.columns.quantity=Quantity
controls.inventory.columns.equipment=Equipment Name
fosa.form.fields.inventory.title=Functional equipment in Inventory
data_personnel.columns.name.title=Names
data_personnel.columns.role.title=Position
data_personnel.columns.gender.title=Sex
data_personnel.columns.phone.title=Phone number (WhatsApp)
data_personnel.columns.age.title=Age
data_personnel.columns.has_cs_training.title=CS Training
data_personnel.columns.education_level.title=Education level
data_personnel.columns.pc_knowledge.title=Computer skills
data_chefferie_personnel.columns.name.title=Names
data_chefferie_personnel.columns.role.title=Position
data_chefferie_personnel.columns.gender.title=Sex
data_chefferie_personnel.columns.phone.title=Phone number (WhatsApp)
data_chefferie_personnel.columns.age.title=Age
data_chefferie_personnel.columns.has_cs_training.title=CS Training
data_chefferie_personnel.columns.email.title=Email
data_chefferie_personnel.columns.education_level.title=Education level
data_chefferie_personnel.columns.pc_knowledge.title=Computer skills
fosa.form.fields.personnel_status.title=List of civil registry staff
fosa.form.fields.key_personnel_count.title=Key personnel for deaths/births
fosa.form.fields.key_personnel_count.description=How many key staff personnel are in charge of the civil registry (maternity and death departments)
fosa.form.msg.value_out_of_range=Value out of range
fosa.form.sections.geo_point.title=GPS Coordinates
controls.gps.lat=Latitude
controls.gps.lon=Longitude
controls.gps.acc=Precision (meters)
controls.gps.alt=Altitude (meters)
fosa.columns.validation_code=Validation Code
fosa.columns.recorded_by=Recorded by
fosa.open_filters=Filters
fosa.submissions.form_type.prompt_text=Select Form Type
fosa.submissions.msg.delete_confirmation=Are you sure you want to remove the selected item(s)?
filters.validation.title=Validation Status
filters.user.recorded_by.title=Recorded by
filters.validation.valid=Validated
filters.validation.invalid=Not validated
filters.validation.any=Any
fosa.columns.recorded_on=Date
filters.title=Filters
loading.txt=Loading...
filters.validation.status=Validation Status
filters.validation.code=Validation Code
filters.submitted_at.region.title=Region
filters.recorded_on.title=Recorded on
filters.controls.operator.prompt_text=Choose an operator
Dialog.filters.clear=Reset
filter.operators.eq=Equals to
filter.operators.ne=Not equal to
filter.operators.gt=Greater than
filter.operators.lt=Less than
filter.operators.before=Before
filter.operators.before_or_today=Before or on
filter.operators.after=After
filter.operators.after_or_today=After or on
filter.operators.between=Between
filter.operators.contains=Contains
filter.operators.gte=Greater than or equals
filter.operators.lte=Less than or equals
filter.operators.start_with=Starts with
filter.operators.ends_with=Ends with
filter.operators.in=In
filter.operators.is_null=Is null
and=and
filter.operators.nn=Is not null
filters.sorting.title=Sorting
msg.restart_notice=System-wide configuration updated. The application needs to be restarted to apply the changes.
stage.notificationPane.restart.actions.text=Restart
settings.advanced.db.name=Database Name
fosa.submissions.context_menu.actions.edit=Edit
choices.region.west=West Region
choices.region.south_west=South West
fosa.form.fields.bike_count.title=Bikes
fosa.form.fields.car_count.title=Cars
fosa.form.fields.tablet_count.title=Tablets
fosa.form.fields.printer_count.title=Printers
fosa.form.fields.pc_count.title=Computers
msg.discard_msg.txt=Are you sure you want to discard the changes you've made?
choices.gender.male=Man
choices.gender.female=Woman
choices.ed_level.secondary=Secondary
choices.ed_level.advanced=Higher
choices.ed_level.primary=Primary
choices.ed_level.none=None
choices.nz2pr56.v_good=Very good
choices.nz2pr56.average=Average
choices.nz2pr56.none=None
choices.nz2pr56.good=Good
data_personnel.columns.email.title=Email
msg.ok=Ok
forms.header.actions.navigation.prev=Prev
forms.header.actions.navigation.next=Next
forms.header.controls.index=Index
fosa.form.fields.index=Index
forms.header.controls.validation_code=Validation Code
forms.header.date.new=New Submission
forms.header.index_search.prompt=Search Index
field_mapper.title=Form field mapper
mapper.categories.forms.fosa.base_fields.title=Base fields
mapper.categories.forms.any.sub_forms.title=Sub-forms
mapper.categories.forms.fosa.sub_forms.title=Sub-forms
mapper.categories.forms.chefferie.sub_forms.title=Sub-forms
mapper.categories.forms.fosa.sub_forms.data_personnel.title=Personnel Info
mapper.categories.forms.chefferie.sub_forms.data_personnel.title=Personnel Info
fosa.form.fields.validation_code=Validation code
mapper.categories.forms.fosa.sub_forms.stats_0.title=Vital statistics (Line 1)
mapper.categories.forms.fosa.sub_forms.stats_1.title=Vital statistics (Line 2)
mapper.categories.forms.fosa.sub_forms.stats_2.title=Vital statistics (Line 3)
mapper.categories.forms.fosa.sub_forms.stats_3.title=Vital statistics (Line 4)
mapper.categories.forms.fosa.sub_forms.stats_4.title=Vital statistics (Line 5)
fosa.columns.year.0=Year
fosa.columns.year.1=Year
fosa.columns.year.2=Year
fosa.columns.year.3=Year
fosa.columns.year.4=Year
fosa.columns.deaths.0=# of deaths registered
fosa.columns.deaths.1=# of deaths registered
fosa.columns.deaths.2=# of deaths registered
fosa.columns.deaths.3=# of deaths registered
fosa.columns.deaths.4=# of deaths registered
fosa.columns.births.0=# of births registered
fosa.columns.births.1=# of births registered
fosa.columns.births.2=# of births registered
fosa.columns.births.3=# of births registered
fosa.columns.births.4=# of births registered
fosa.form.fields.responding_device.title=Which device do you use to fill in the questionnaire?
chefferie.submissions.title=Submission - CHEFFERIE
chefferie.columns.submitted=Add Submission
chefferie.columns.recorded_at=Submitted
chefferie.columns.last_updated_by=Recorded At
chefferie.columns.last_updated_at=Last updated by
chefferie.add_submission=Last updated at
chefferie.form.sections.respondent.title=Respondent
chefferie.form.sections.structure_identification.title=Structure identification
chefferie.form.sections.service_offered_and_amenities.title=Services offered and amenities
chefferie.form.sections.infra_eq.title=Infrastructure and Equipment
chefferie.form.sections.personnel_status.title=Personnel Status
chefferie.form.finish=Finish
chefferie.form.discard=Discard
chefferie.form.fields.names.title=First and last names
chefferie.form.fields.position.title=Function
chefferie.form.fields.position.description=Position / function in the health facility
chefferie.form.fields.phone.title=Phone number
chefferie.form.fields.phone.description=Phone number (preferably WhatsApp)
chefferie.form.fields.email.title=Email
chefferie.form.fields.creation_date.title=Created at
chefferie.form.fields.creation_date.description=Year of creation of the health facility (dd/MM/YYYY)
chefferie.form.fields.email.description=Email address (work email)
chefferie.form.msg.invalid_value=Invalid value
chefferie.form.fields.environment.options.urban.title=Urban
chefferie.form.fields.environment.options.rural.title=Rural
chefferie.form.fields.region.title=Region
chefferie.form.fields.department.title=Division
chefferie.form.fields.department.description=Division in the region
chefferie.form.fields.communes.title=Town/City
chefferie.form.fields.quarter.title=Neighborhood
chefferie.form.fields.name.title=Name of the CHEFFERIE
chefferie.form.fields.classification.title=Classification
chefferie.form.fields.classification.description=Classification of the chefferie
chefferie.form.fields.distance.title=Distance to the nearest civil status center
chefferie.form.sections.geo_point.title=Geographic coordinates
chefferie.form.fields.classification.option.first=1ier degr� ou Lamidat
chefferie.form.fields.classification.option.second=2e degr�
chefferie.form.fields.fonction.title=Civil status function
chefferie.form.fields.fonction.description=Civil status function exercised by the chief or a notable in the chiefdom
chefferie.form.fields.benefit.title=Taking the oath
chefferie.form.fields.benefit.description=Swearing in of the chief or a notable of the chiefdom
chefferie.form.fields.conservation_place.title=Place of conservation
chefferie.form.fields.conservation_place.description=Place of conservation of civil status registers
chefferie.form.fields.training.title=Is the civil status officer trained
chefferie.form.fields.training.description=Training received on the civil status of the chief or a notable of the chiefdom
chefferie.form.fields.waiting_room.title=Space or waiting room available
chefferie.form.fields.waiting_room.description=Space or waiting room available for users
chefferie.form.fields.cs_actor_is_chief.title=Does the chief exercise the civil status function?
chefferie.form.fields.reception_location.description=User reception area in the chiefdom
chefferie.form.fields.toilets_accessible.title=Availability of toilets
chefferie.form.fields.toilets_accessible.description=Availability of toilets accessible to users
chefferie.form.fields.fonction.option.first=Yes, Civil Status Officer
chefferie.form.fields.fonction.option.second=Yes, Civil Status Secretary
chefferie.form.fields.fonction.option.third=No
chefferie.form.fields.benefit.option.first=Yes
chefferie.form.fields.benefit.option.second=No
chefferie.form.fields.conservation_place.option.first=In a reserved room
chefferie.form.fields.conservation_place.option.second=In the chief's house
chefferie.form.fields.conservation_place.option.third=Others (Please specify)
chefferie.form.fields.training.option.first=Yes
chefferie.form.fields.training.option.second=No
chefferie.form.fields.waiting_room.option.first=Yes
chefferie.form.fields.waiting_room.option.second=No
chefferie.form.fields.reception_location.option.first=Dans une salle r�serv�e
chefferie.form.fields.reception_location.option.second=Dans le domicile du chef
chefferie.form.fields.reception_location.option.third=Autres (A pr�ciser)
chefferie.form.fields.toilets_accessible.option.first=Yes
chefferie.form.fields.toilets_accessible.option.second=No
chefferie.form.fields.Functional_equipment.title=Functional equipment
chefferie.form.fields.Functional_equipment.description=Functional equipment in the chiefdom: types and quantities
chefferie.form.fields.equipment_question.title=Functional equipment in the chiefdom: types and quantities
chefferie.form.fields.equipment_quantity.computers=Computers
chefferie.form.fields.equipment_quantity.tablets=Tablets
chefferie.form.fields.equipment_quantity.printers=Printers
chefferie.form.fields.equipment_quantity.cars=Cars
chefferie.form.fields.equipment_quantity.motorcycles=Motorbikes
chefferie.form.fields.structure.title=Is the chiefdom building the chief's residence?
chefferie.form.fields.structure.description=Is the chiefdom building, the chief's residence?
chefferie.form.fields.connexion.title=Internet access
chefferie.form.fields.connexion.description=Chiefdom Internet Connection
chefferie.form.fields.typeConnexion.title=Internet connection type
chefferie.form.fields.typeConnexion.description=Type of internet connection available
chefferie.form.fields.eneoConnexion.title=ENEO acces
chefferie.form.fields.eneoConnexion.description=Connection of the chiefdom to the electricity network (ENEO)
chefferie.form.fields.waterAcces.title=Water availability
chefferie.form.fields.waterAcces.description=Availability of a water supply source in the chiefdom
chefferie.form.fields.waterType.title=Water source(s) available
chefferie.form.fields.waterType.description=Type of water supply source
chefferie.form.fields.extinguisher.title=Working fire extinguisher
chefferie.form.fields.extinguisher.description=Working fire extinguisher available in the chiefdom
chefferie.form.fields.equipment_quantity.computers.description=Number of computers
chefferie.form.fields.equipment_quantity.tablets.description=Number of tablets
chefferie.form.fields.equipment_quantity.printers.description=Number of printers
chefferie.form.fields.equipment_quantity.cars.description=Number of cars
chefferie.form.fields.equipment_quantity.motorcycles.description=Number of motorcycles
chefferie.form.fields.structure.option.first=Yes
chefferie.form.fields.structure.option.second=No
chefferie.form.fields.connexion.option.first=Yes
chefferie.form.fields.connexion.option.second=No
chefferie.form.fields.type.connexion.option.first=2G
chefferie.form.fields.type.connexion.option.second=3G
chefferie.form.fields.type.connexion.option.third=4G
chefferie.form.fields.type.connexion.option.fourth=ADSL (corded phone)
chefferie.form.fields.type.connexion.option.fith=Optical fiber
chefferie.form.fields.eneo.connexion.option.first=Yes
chefferie.form.fields.eneo.connexion.option.second=No
chefferie.form.fields.water.acces.option.first=Yes
chefferie.form.fields.water.acces.option.second=No
chefferie.form.fields.water.type.option.first=CAMWATER
chefferie.form.fields.water.type.option.second=Well constructed/Drilling
chefferie.form.fields.water.type.option.third=Undeveloped/Traditional Well
chefferie.form.fields.water.type.option.fourth=Watercourse
chefferie.form.fields.water.type.option.fith=Others (Please specify)
chefferie.form.fields.extinguisher.option.first=Yes
chefferie.form.fields.extinguisher.option.second=No
chefferie.form.fields.employer.title=Staff in charge of civil status
chefferie.form.fields.employer.description=How many staff members are in charge of civil status in the chiefdom?
services.auth.user_not_found=Invalid username or password
chefferie.form.fields.facility_name.title=Full name of chiefdom
chefferie.form.sections.extra.title=Comments & Extra
fosa.form.sections.extra.title=Comments & Extra
chefferie.form.fields.extra_info.description=Please use the space provided to add any additional relevant information.
chefferie.form.fields.extra_info.title=Extra information
chefferie.form.fields.index=Index
chefferie.form.fields.validation_code=Validation code
chefferie.form.fields.other_water_source.description=Other available drinking water supply
chefferie.form.fields.other_water_source.title=Specify the water source
chefferie.form.fields.cs_actor_is_chief.description=Is the civil status function performed by the chief or a notable in the chiefdom?
chefferie.form.fields.oath.title=Has the chief or notable taken oath?
chefferie.form.fields.cs_reg_location.title=Location of civil registers
chefferie.form.fields.other_cs_reg_location.title=Specify the civil status registry location
chefferie.form.fields.other_internet_type.title=Specify the internet connection type
chefferie.form.fields.degree.options.first_degree.title=1st degree or lamidat
chefferie.form.fields.degree.options.second_degree.title=Second Degree
chefferie.form.fields.other_waiting_room.title=Specify the waiting room's location
chefferie.form.fields.reception.title=User Reception
chefferie.form.sections.equipment.sections.equipment.title=Equipment Information
chefferie.form.sections.equipment.structure_info.title=Building information & facilities
chefferie.form.fields.other_recep.title=Specify the reception area
chefferie.form.title=
mapper.categories.forms.chefferie.base_fields.title=Base Fields
shell.menu.forms.csc=CSC Form
csc.submissions.title=Submissions - CSC
csc.add_submission=Add Submission
csc.columns.submitted=Submitted
csc.columns.recorded_at=Recorded At
csc.columns.last_updated_by=Last updated by
csc.columns.last_updated_at=Last updated at
submissions.context_menu.actions.delete=Delete
fosa.form.finish=
csc.form.sections.respondent.title=Respondent
csc.form.sections.identification.title=Structure Identification
csc.form.sections.accessibility.title=Accessibility of the Centre
csc.form.sections.infrastructure.title=Infrastructure and equipment of the Centre
csc.form.sections.areas.title=Areas devoted to civil status
csc.form.sections.equipment.title=Facilities of the Civil Registry Centre (Functional Equipment)
csc.form.sections.digitization.title=Digitization/Computerization of civil status
csc.form.sections.record_procurement.title=Procurement of Records
csc.form.sections.vital_stats.title=Financial resources related to vital statistics documents
csc.form.sections.deeds.title=Deeds drawn up, not withdrawn in the last 5 years
mapper.categories.forms.csc.base_fields.sections.deeds.title=Deeds drawn up, not withdrawn in the last 5 years
csc.form.sections.status_of_archived_records.title=Status of archived records
csc.form.sections.archiving_function.title=Archiving
csc.form.sections.personnel_info.title=Staff Status
csc.form.sections.comments.title=Comments & Extra
csc.form.sections.respondent.fields.position.title=Position
csc.form.sections.respondent.fields.position.description=Role of the respondent within the CSC
csc.form.sections.respondent.fields.phone.description=Register (preferably WhatsApp)
csc.form.sections.respondent.fields.phone.title=Phone Number
csc.form.sections.respondent.fields.email.title=Email Address
csc.form.sections.respondent.fields.email.description=Respondent's commonly used or professional email
csc.form.sections.respondent.fields.knows_creation_date.description=Do you know the date of creation of the CSC?
csc.form.sections.respondent.fields.knows_creation_date.title=Knows Creation Date?
csc.form.sections.identification.fields.division.description=Choose the department to which the civil status centre belongs
csc.form.sections.identification.fields.municipality.title=Commune/Municipality
csc.form.sections.identification.fields.municipality.description=Indicate the municipality of the civil status centre
csc.form.sections.identification.fields.quarter.title=Quarter
csc.form.sections.identification.fields.quarter.description=Enter the name of the neighbourhood where the CSC is located
csc.form.fields.index.title=Index
csc.form.fields.validation_code.title=Validation Code
csc.form.sections.identification.fields.facility.title=Facility Name
csc.form.sections.identification.fields.category.title=Category
csc.form.sections.identification.fields.council_size.title=Size of the council's municipality
csc.form.sections.identification.fields.milieu.title=Milieu
csc.form.sections.identification.fields.attached_centers.title=Number of Attached Centers
csc.form.sections.identification.fields.locality.title=Locality
csc.form.sections.identification.fields.creation_date.title=Date of Creation
csc.form.sections.identification.fields.functional.title=Is the Centre Functional?
csc.form.sections.identification.fields.non_function_reason.title=Why is the Centre not functional?
csc.form.sections.identification.fields.chiefdom_degree.title=Chiefdom Degree
csc.form.sections.identification.fields.other_non_function_reason.title=Specify the reason for non-functionality
csc.form.sections.identification.fields.fields.is_chiefdom.title=Is the Centre a Chiefdom?
csc.form.sections.identification.fields.non_function_duration.title=How long has the Centre been non-functional?
csc.form.sections.identification.fields.sec_creation_order.title=Secondary Creation Order
csc.form.sections.identification.fields.officer_appointment_order.title=Officer Appointment Order
csc.form.sections.identification.fields.officer_appointed.title=Is the Officer Appointed?
csc.form.sections.identification.fields.photo_url.title=Photo of the Center
csc.form.sections.identification.fields.gps_coords.title=GPS Coordinates
csc.form.sections.identification.fields.division.title=Division
csc.form.sections.respondent.fields.creation_date.title=Date of Creation
csc.form.sections.respondent.fields.name.title=First and last names
csc.form.sections.accessibility.fields.road_type.title=Type of Roads serving the Centre
csc.form.sections.accessibility.fields.road_deteriorates.title=Does the road deteriorate periodically?
csc.form.sections.accessibility.fields.obstacle.title=Barriers limiting access to the Centre
csc.form.sections.accessibility.fields.attached_villages_num.title=Number of villages attached to the Centre
csc.form.sections.accessibility.fields.cover_radius.title=Center coverage radius
csc.form.sections.accessibility.sub_forms.villages.fields.name.title=Village name
csc.form.sections.accessibility.sub_forms.villages.fields.avg_distance.title=Average distance from the CSC (in KM)
csc.form.section.accessibility.sub_forms.villages.fields.observations.title=Observations
csc.form.sections.infra.fields.occupancy_status.title=Occupancy
csc.form.sections.infra.fields.occupancy_status.description=Occupancy Status of the Center building
csc.form.sections.infra.fields.other_building.title=Is there another public building?
csc.form.sections.infra.fields.eneo_connection.title=ENEO Connection
csc.form.sections.infra.fields.eneo_connection.description=Is the centre connected to the national electricity grid (ENEO)?
csc.form.sections.infra.fields.power_outages.title=Frequent power interruptions?
csc.form.sections.infra.fields.power_outages.description=Are there often interruptions in electrical energy?
csc.form.sections.infra.fields.stable_power.title=Is the electricity supply stable?
csc.form.sections.infra.fields.backup_power_available.title=Are there other sources of electrical power?
csc.form.sections.infra.fields.backup_power.title=Select the functional complementary energy sources
csc.form.sections.infra.fields.other_backup_power.title=Specify the complementary source
csc.form.sections.infra.fields.water_sources.title=Which water source is available at the center?
csc.form.sections.infra.fields.toilets_available.title=Are there toilets available?
csc.form.sections.infra.fields.separate_toilets_available.title=Are the toilets separated by gender?
csc.form.sections.infra.fields.zone_operators.title=Which telecom operators are in the zone?
csc.form.sections.infra.fields.has_fiber.title=Is there a fiber optic connection?
csc.form.sections.infra.fields.other_zone_operators.title=Specify the telecom operators in the zone
csc.form.sections.infra.fields.has_internet.title=Is there an Internet connection?
csc.form.sections.infra.fields.internet_type.title=Which telecom operators provide the Internet connection?
csc.form.sections.infra.fields.other_internet_type.title=Specify the type of Internet provider
csc.form.sections.infra.fields.internet_sponsor.title=Who pays for the Internet connection?
csc.form.sections.areas.fields.office_count.title=# of Offices
csc.form.sections.areas.fields.dedicated_cs_rooms.title=Dedicated CS rooms?
csc.form.sections.areas.fields.dedicated_cs_rooms.description=Are there other dedicated rooms for civil status?
csc.form.sections.areas.fields.moving.title=Are there moving plans?
csc.form.sections.areas.fields.moving.description=Are there plans to move into a new building in the coming months?
csc.form.sections.areas.sub_forms.rooms.fields.number.title=Room number
csc.form.sections.areas.sub_forms.rooms.fields.name.title=Room name
csc.form.sections.areas.sub_forms.rooms.fields.condition.title=Condition
csc.form.sections.areas.sub_forms.rooms.fields.dimension.title=Dimensions
csc.form.sections.areas.sub_forms.rooms.fields.renovation.title=Nature of renovation work
csc.form.sections.equipment.fields.pc_count.title=# of Computers
csc.form.sections.equipment.fields.server_count.title=# of Servers
csc.form.sections.equipment.fields.printer_count.title=# of Printers
csc.form.sections.equipment.fields.scanner_count.title=# of Scanners
csc.form.sections.equipment.fields.inverters.title=# of Inverters
csc.form.sections.equipment.fields.conditioners.title=# of Conditioners
csc.form.sections.equipment.fields.fans.title=# of Fans
csc.form.sections.equipment.fields.projectors.title=# of Projectors
csc.form.sections.equipment.fields.office_tables.title=# of Office Tables
csc.form.sections.equipment.fields.chairs.title=# of Chairs
csc.form.sections.equipment.fields.cars.title=# of Cars
csc.form.sections.equipment.fields.bikes.title=# of Bikes
csc.form.sections.equipment.fields.tablets.title=# of Tablets
csc.form.sections.digitization.fields.using_info_sys_outside_cs.title=Using a System Outside CR
csc.form.sections.digitization.fields.using_info_sys_outside_cs.description=Apart from the civil registry, does any other department of the centre use a computerised system
csc.form.sections.digitization.fields.external_cr_uses_internet.title=If so, does this system use the Internet?
csc.form.sections.digitization.fields.has_cs_software.title=Software equipped?
csc.form.sections.digitization.fields.has_cs_software.description=Is the center equipped with one or more software for civil status?
csc.form.sections.digitization.fields.cs_software_name.title=What is the name(s) of the software?
csc.form.sections.digitization.fields.cs_software_license_sponsor.title=How was the software acquired?
csc.form.sections.digitization.fields.other_cs_software_license_sponsor.title=Specify the software acquisition method
csc.form.sections.digitization.fields.users_receive_digital_acts.title=Are digital documents given to users?
csc.form.sections.digitization.fields.software_activation_date.title=Software activation date
csc.form.sections.digitization.fields.software_feedback.title=What's your feedback on the software?
csc.form.sections.digitization.fields.software_trained_user_count.title=# of trained users
csc.form.sections.digitization.fields.software_recorded_marriage_count.title=# of marraige certificates
csc.form.sections.digitization.fields.software_recorded_marriage_count.description=# of marriage certificates registerd in the software
csc.form.sections.digitization.fields.software_recorded_birth_count.title=# of birth certificates
csc.form.sections.digitization.fields.software_recorded_birth_count.description=# of birth certificates registerd in the software
csc.form.sections.digitization.fields.software_recorded_death_count.title=# of death certificates
csc.form.sections.digitization.fields.software_recorded_death_count.description=# of death certificates registerd in the software
csc.form.sections.digitization.fields.software_is_functional.title=Is the software functional?
csc.form.sections.digitization.fields.software_dysfunction_reason.title=Why is the software not functional?
csc.form.sections.indexing.fields.records_scanned.title=CS records scanned?
csc.form.sections.indexing.fields.records_scanned.description=Have the civil status records been digitized (scanned) in this civil status center?
csc.form.sections.indexing.fields.staff_trained.title=Staff trained?
csc.form.sections.indexing.fields.staff_trained.description=Has the staff of the civil status center been trained in the use of the digitization software?
csc.form.sections.indexing.fields.document_scan_start_date.title=Scan starting date
csc.form.sections.indexing.fields.is_data_indexed.title=Has the data been indexed?
csc.form.sections.indexing.fields.marriages_indexed.title=# of marriages indexed
csc.form.sections.indexing.fields.deaths_indexed.title=# of deaths indexed
csc.form.sections.indexing.fields.births_indexed.title=# of births indexed
csc.form.sections.indexing.fields.marriages_scanned.title=# of marriages scanned
csc.form.sections.indexing.fields.births_scanned.title=# of births scanned
csc.form.sections.indexing.fields.deaths_scanned.title=# of deaths scanned
csc.form.sections.indexing.fields.is_data_in_use.title=Is the data in use?
csc.form.sections.indexing.fields.data_usage.title=How is the data used?
csc.form.sections.record_procurement.fields.lack_of_registers.title=Have there been a lack of registers?
csc.form.sections.record_procurement.fields.lack_of_registers.description=Have there been a lack of registers during these years?
csc.form.sections.record_procurement.fields.records_provider.title=Records Provider
csc.form.sections.record_procurement.fields.records_provider.description=Who provided you with records for this year 2025
csc.form.sections.record_procurement.fields.other_records_provider.title=Please specify the records provider
csc.form.sections.record_procurement.fields.non_compliant_registers_used.title=Usage of custom registers
csc.form.sections.record_procurement.fields.non_compliant_registers_used.description=Have you often had to buy the registers in the market for the establishment of the deeds?
csc.form.sections.record_procurement.fields.blank_registries.title=Blank Registries
csc.form.sections.record_procurement.fields.blank_marriages.title=# of blank marriage registers
csc.form.sections.record_procurement.fields.blank_births.title=# of blank birth registers
csc.form.sections.record_procurement.fields.blank_deaths.title=# of blank death registers
controls.file_picker.placeholder.txt=Click below to select a picture
csc.form.sections.vital_stats.fields.birth_cert_cost.title=Cost of birth certificates (FCFA)
csc.form.sections.vital_stats.fields.birth_cert_copy_cost.title=Cost of copy of birth certificates (FCFA)
csc.form.sections.vital_stats.fields.marriage_cert_copy_cost.title=Cost of copy of marriage certificates (FCFA)
csc.form.sections.vital_stats.fields.death_cert_copy_cost.title=Cost of copy of death certificates (FCFA)
csc.form.sections.vital_stats.fields.celibacy_cert_copy_cost.title=Cost of certificate of celibacy (FCFA)
csc.form.sections.vital_stats.fields.non_registered_certs.title=# of Certificates not registered
csc.form.sections.vital_stats.fields.rates_under_deliberation.title=Are rates under deliberation?
csc.form.sections.vital_stats.fields.rates_under_deliberation.description=Are these rates currently the subject of a deliberation by the municipal council?
csc.form.sections.vital_stats.fields.prices_displayed.title=Are these prices displayed?
csc.form.sections.vital_stats.fields.municipality_budget.title=2024 budget
csc.form.sections.vital_stats.fields.municipality_budget.description=What is the municipality's budget for the year 2024?
csc.form.sections.vital_stats.fields.cs_budget.title=Civil status share
csc.form.sections.vital_stats.fields.cs_budget.description=What was the share devoted to civil status in 2024?
csc.form.sections.vital_stats.fields.cs_revenue.title=
csc.form.sections.archiving.fields.archiving_room.title=Does the center have an Archiving room?
csc.form.sections.archiving.fields.archiving_room_electric_condition.title=What is the state of the electrical circuit in the main archive room?
csc.form.sections.archiving.fields.fire_extinguishers.title=Does the hall have one or more fire extinguishers?
csc.form.sections.archiving.fields.locked_door.title=Does the room in which the registers are archived have a locked door
csc.form.sections.archiving.fields.access_limited.title=Is access to the archive room limited to one category of staff?
csc.form.sections.archiving.fields.room_has_humidity.title=Sealing problems?
csc.form.sections.archiving.fields.room_has_humidity.description=Does the room in which the registers are archived show traces of humidity (sealing problems)?
csc.form.sections.archiving.fields.register_archiving_type.title=How are registers archived?
csc.form.sections.archiving.fields.other_register_archiving_type.title=Alternative Way of Archiving Records
csc.form.sections.archiving.fields.written_archiving_plan.title=Is there a written record archiving plan?
csc.form.sections.archiving.fields.registers_deposited.title=Have all the registers of the sub-prefecture been deposited at the town hall?
csc.form.sections.archiving.fields.registers_deposited_systematically.title=Are the registers systematically submitted to the Town Hall at the end of the year?
csc.form.sections.archiving.fields.vandalized.title=Vandalization
csc.form.sections.archiving.fields.vandalized.description=Have the archives been the subject of theft or acts of vandalism?
csc.form.sections.archiving.fields.vandalized_date.title=Can you describe the context and the date?
csc.form.sections.archiving.sections.general.title=General
csc.form.sections.accessibility.sections.general.title=General
csc.form.sections.personnel.sections.general.title=General
csc.form.sections.personnel.sections.personnel.title=List of personnel (officers and non-officers)
csc.form.sections.accessibility.sections.villages.title=Attached Villages
csc.form.sections.archiving.sections.deeds.title=Deeds drawn up, not withdrawn in the last 5 years
csc.form.sections.comments.fields.relevant_info.title=Relevant Information
csc.form.sections.deeds.fields.year.title=Year
csc.form.sections.deeds.fields.birth_certs_drawn.title=Birth certificates drawn up
csc.form.sections.deeds.fields.births_certs_not_withdrawn.title=Birth certificates not withdrawn
csc.form.sections.deeds.fields.marriage_certs_drawn.title=Marriage certificates drawn up
csc.form.sections.deeds.fields.marriage_certs_not_withdrawn.title=Marriage certificates not withdrawn
csc.form.sections.deeds.fields.death_certs_drawn.title=Death certificates drawn
csc.form.sections.deeds.fields.death_certs_not_withdrawn.title=Death certificates not withdrawn
csc.form.sections.archive_stats.fields.year.title=Year
csc.form.sections.archive_stats.fields.birth_count.title=# of Birth Registers Archived
csc.form.sections.archive_stats.fields.marriage_count.title=# of Marriage Registers Archived
csc.form.sections.archive_stats.fields.death_count.title=# of Death Registers Archived
csc.form.sections.personnel_info.fields.male_count.title=# of Males
csc.form.sections.personnel_info.fields.female_count.title=# of Females
csc.form.sections.personnel_info.fields.non_officer_male_count.title=Male non-officers
csc.form.sections.personnel_info.fields.non_officer_female_count.title=Female non-officers
csc.form.sections.personnel_info.sub_forms.officers.fields.other_position.title=Alternative position
csc.form.sections.personnel_info.sub_forms.officers.fields.status.title=Status
csc.form.sections.personnel_info.sub_forms.officers.fields.other_status.title=Alternative status
csc.form.sections.personnel_info.sub_forms.officers.fields.allowance_2022.title=Allowance (2022)
csc.form.sections.personnel_info.sub_forms.officers.fields.revenue_2022.title=Revenue (2022)
csc.form.sections.personnel_info.sub_forms.officers.fields.archiving_training.title=Has archiving training
csc.form.sections.personnel_info.sub_forms.officers.fields.seniority.title=Seniority
data_personnel.columns.status.title=Professional Status
data_personnel.columns.ec_training.title=Has Civil status training
data_personnel.columns.has_pc_training.title=Has computer training
data_personnel.columns.archiving_training.title=Has archiving training
data_personnel.columns.monthly_revenue.title=Monthly revenue
range_0_100=min = 0, max = 100
range_1_50=min = 1, max = 50
range_1980_current_year=min = 1980, max = current year
range_0_80000=min = 0, max = 80000
csc.form.base_fields.sections.accessibility.sub_forms.villages.title=List of attached villages
mapper.categories.forms.csc.base_fields.sections.infrastructure.title=Infrastructure and equipment of the Centre
mapper.categories.forms.csc.base_fields.sections.respondent.title=The Respondent
mapper.categories.forms.csc.base_fields.sections.identification.title=Identification of the Center
mapper.categories.forms.csc.base_fields.sections.accessibility.title=Accessibility to the Center
mapper.categories.forms.csc.base_fields.sections.accessibility.sub_forms.villages.title=Attached Villages
mapper.categories.forms.csc.base_fields.sections.areas.title=Areas devoted for civil status
mapper.categories.forms.csc.base_fields.sections.areas.sub_forms.rooms.title=State of rooms devoted to civil status
mapper.categories.forms.csc.base_fields.sections.equipment.title=Facilities of the Civil Registry Centre (Functional Equipment)
mapper.categories.forms.csc.base_fields.sections.digitization.title=Digitization/Computerization of civil status
mapper.categories.forms.csc.base_fields.sections.record_procurement.title=Procurement of Records
mapper.categories.forms.csc.base_fields.sections.stats.title=Financial resources related to vital statistics documents
controls.gps.conn_notice=Cannot connect to the Internet. Please check your connection.
csc.form.sections.indexing.title=Scanning of records and indexing
csc.form.sections.areas.fields.office_count.description=How many rooms are dedicated to civil status?
csc.form.base_fields.sections.areas.sub_forms.rooms.title=Status of spaces dedicated to civil status
mapper.categories.forms.csc.base_fields.sections.indexing.title=Document scanning/indexing
mapper.categories.forms.csc.base_fields.sections.archiving.title=Archiving
mapper.categories.forms.csc.base_fields.sections.records.title=Number of archived records (2020 to 2024)
mapper.categories.forms.csc.base_fields.sections.comments.title=Comments & Extra
mapper.categories.forms.csc.base_fields.sections.personnel.sub_forms.personnel_info.title=Staff Status
mapper.categories.forms.csc.base_fields.sections.personnel.sub_forms.personnel_info.sections.general.title=General
mapper.categories.forms.csc.base_fields.sections.personnel.sub_forms.personnel_info.sections.staff.title=List of personnel (officers and non-officers)
submissions.columns.index=Index
submissions.columns.facility_name=Facility Name
filters.facility_name.title=Facility Name
filters.index.title=Index
submissions.filter.prompt=Filter by "Facility Name", "Validation Code", "Index"
`;
const fr = `
login.username=Nom d'utilisateur
login.forgot_password=Mot de passe oublié?
login.lets_continue_your_journey=Continuons votre voyage
login.password=Mot de passe
login.powered_by=Alimenté par
login.settings=Paramètres
login.sign_in=Se connecter
login.welcome_back=Content de te revoir
settings.advanced.title=Avancé
settings.advanced.db.pwd=Mot de passe
settings.advanced.db.host=Hôte
settings.advanced.db.user=Nom d'utilisateur
settings.advanced.db.title=Base de données
settings.general=Général
settings.language=Langue
settings.language.en=Anglais
settings.language.fr=Français
settings.title=Paramètres
settings.advanced.db.port=Port
settings.msg.invalid_port=Numéro de port non valide (plage: 1025 - 65535)
settings.msg.value_required=Ce champ est obligatoire
settings.advanced.db.ssl=SSL
settings.advanced.storage.title=Stockage
settings.msg.invalid_url=URL non valide
settings.msg.value_too_short=La valeur est trop courte
settings.advanced.storage.endpoint=Point de terminaison API (S3 compatible)
settings.advanced.storage.access_key=Clé d'accès
settings.advanced.storage.secret_key=Clé secrète
settings.advanced.api.origin=Origine de l'API
settings.advanced.api.title=Paramètres de l'API
csc.add_new=Ajouter un nouveau
shell.filter=Filtre
shell.sign_out=se déconnecter
shell.menu.forms.fosa=Forme fossante
shell.menu.forms.chefferie=CHEFFERIE Form
fosa.submissions.title=Soumissions
shell.menu.forms.title=Formes
fosa.add_submission=Ajouter la soumission
fosa.columns.validated=Est valide
fosa.columns.recorded_at=Enregistré à
fosa.columns.last_updated_by=Dernière mise à jour par
fosa.columns.last_updated_at=Dernière mise à jour à
fosa.form.filter=Filtre
fosa.form.title=Soumission des pieds
fosa.form.sections.respondent.title=Intimé
fosa.form.sections.respondent.description=Des informations sur le répondant
forms.validation.msg.field_required=Ce champ est obligatoire
fosa.form.sections.structure_identification.title=Identification de la structure
fosa.form.sections.reg_cs_events.title=Enregistrement des événements de statut civil
fosa.form.sections.infra_eq.title=Infrastructure et équipement
fosa.form.sections.personnel_status.title=Personnel Status
fosa.form.fields.names.title=Noms de premier et de famille
fosa.form.fields.position.title=Fonction
fosa.form.fields.position.description=Position / fonction dans l'établissement de santé
fosa.form.fields.phone.title=Numéro de téléphone
fosa.form.fields.phone.description=Numéro de téléphone (de préférence WhatsApp)
fosa.form.fields.email.title=E-mail
fosa.form.fields.creation_date.title=Créé à
fosa.form.fields.creation_date.description=Année de création de l'établissement de santé (DD / mm / yyyy)
fosa.form.fields.email.description=Adresse e-mail (e-mail de travail)
forms.msg.invalid_value=Valeur non valide
fosa.form.fields.department.title=Division
fosa.form.fields.department.description=Division dans la région
fosa.form.fields.communes.title=Ville / ville
fosa.form.fields.quarter.title=Quartier
fosa.form.fields.locality.title=Localité
fosa.form.fields.fosa_name.title=Nom de l'installation
fosa.form.fields.fosa_name.description=Nom complet de l'installation FOSA
fosa.form.fields.district.title=District de santé
fosa.form.fields.district.description=District de santé associé
fosa.form.fields.health_area.title=Domaine de santé
fosa.form.fields.environment.title=Type d'environnement
fosa.form.fields.fosa_type.title=Type d'installation
fosa.form.fields.fosa_status.title=Statut de l'établissement
fosa.form.fields.has_maternity.title=A la maternité
fosa.form.fields.has_maternity.description=Existence d'une maternité dans l'établissement de santé
fosa.form.fields.csc_reg.title=CSC associé
fosa.form.fields.csc_reg.description=Bureau de registre local
fosa.form.fields.distance_csc.title=Proximité du CSC
fosa.form.fields.distance_csc.description=Distance moyenne du bureau du registre
fosa.form.fields.environment.options.urban.title=Urbain
fosa.form.fields.environment.options.rural.title=Rural
fosa.form.fields.region.title=Région
forms.footer.actions.finish=Enregistrer les modifications
forms.footer.actions.discard=Jeter les changements
fosa.columns.year=Année
fosa.columns.births=# des naissances enregistrées
fosa.columns.deaths=# des décès enregistrés
fosa.columns.observation=Observations
fosa.form.fields.dhis2_usage.title=DHIS2 Usage
fosa.form.fields.dhis2_usage.description=Utilisation de DHIS2 dans la formation en santé
fosa.form.fields.uses_bunec_birth_form.title=Utilise le formulaire de naissance de Bunec
fosa.form.fields.uses_bunec_birth_form.description=Enregistrement des naissances sur le formulaire standardisé fourni par BUNEC
fosa.form.fields.uses_dhis2_form.title=Utilise des formulaires DHIS2
fosa.form.fields.uses_dhis2_form.description=Formation à l'utilisation du formulaire standardisé DHIS2
fosa.form.fields.birth_declaration_transmission_to_csc.title=Déclarations de naissance à CSC
fosa.form.fields.birth_declaration_transmission_to_csc.description=Transmission des déclarations de naissance au bureau du registre
fosa.form.fields.csc_event_reg_type.title=Enregistrer les événements de statut civil?
fosa.form.fields.csc_event_reg_type.description=Comment enregistrez-vous les événements de statut civil?
fosa.form.fields.stats.title=Statistiques essentielles depuis 5 ans
controls.stats_collector.actions.add_new=Ajouter
controls.stats_collector.actions.remove_selection=Supprimer sélectionné
fosa.form.fields.toilet_present.title=A des toilettes?
fosa.form.fields.toilet_resent.description=Présence de toilettes accessibles pour les utilisateurs de l'établissement
fosa.form.fields.has_eneo_connection.title=Connexion d'emplacement?
fosa.form.fields.has_eneo_connection.description=L'installation est-elle connectée au réseau électrique (ENEO)?
fosa.form.fields.has_power_source.title=A une source d'alimentation d'urgence?
fosa.form.fields.has_power_source.description=Le centre a-t-il une source d'urgence ou alternative de puissance
fosa.form.fields.alternative_power.title=Sources d'alimentation de sauvegarde
fosa.form.fields.internet_conn.title=A une connexion Internet?
fosa.form.fields.has_water_source.title=Source d'eau alternative?
fosa.form.fields.has_water_source.description=Disponibilité d'un alternative en eau pour l'installation
fosa.form.fields.water_source.title=Sources d'eau
controls.inventory.columns.quantity=Quantité
controls.inventory.columns.equipment=Nom de l'équipement
fosa.form.fields.inventory.title=Équipement fonctionnel dans l'inventaire
data_personnel.columns.name.title=Noms
data_personnel.columns.role.title=Position
data_personnel.columns.gender.title=Sexe
data_personnel.columns.phone.title=Numéro de téléphone (WhatsApp)
data_personnel.columns.age.title=Âge
data_personnel.columns.has_cs_training.title=Formation CS
data_personnel.columns.education_level.title=Niveau d'éducation
data_personnel.columns.pc_knowledge.title=Compétences informatiques
data_chefferie_personnel.columns.name.title=Noms
data_chefferie_personnel.columns.role.title=Position
data_chefferie_personnel.columns.gender.title=Sexe
data_chefferie_personnel.columns.phone.title=Numéro de téléphone (WhatsApp)
data_chefferie_personnel.columns.age.title=Âge
data_chefferie_personnel.columns.has_cs_training.title=Formation CS
data_chefferie_personnel.columns.email.title=E-mail
data_chefferie_personnel.columns.education_level.title=Niveau d'éducation
data_chefferie_personnel.columns.pc_knowledge.title=Compétences informatiques
fosa.form.fields.personnel_status.title=Liste du personnel du registre civil
fosa.form.fields.key_personnel_count.title=Personnel clé pour les décès / naissances
fosa.form.fields.key_personnel_count.description=Combien de membres du personnel clé sont en charge du registre civil (départements de maternité et de décès)
fosa.form.msg.value_out_of_range=Valeur hors de portée
fosa.form.sections.geo_point.title=Coordonnées GPS
controls.gps.lat=Latitude
controls.gps.lon=Longitude
controls.gps.acc=Précision (mètres)
controls.gps.alt=Altitude (mètres)
fosa.columns.validation_code=Code de validation
fosa.columns.recorded_by=Enregistré par
fosa.open_filters=Filtres
fosa.submissions.form_type.prompt_text=Sélectionner le type de formulaire
fosa.submissions.msg.delete_confirmation=Êtes-vous sûr de vouloir supprimer les éléments sélectionnés?
filters.validation.title=Statut de validation
filters.user.recorded_by.title=Enregistré par
filters.validation.valid=Validé
filters.validation.invalid=Non validé
filters.validation.any=N'importe lequel
fosa.columns.recorded_on=Date
filters.title=Filtres
loading.txt=Chargement...
filters.validation.status=Statut de validation
filters.validation.code=Code de validation
filters.submitted_at.region.title=Région
filters.recorded_on.title=Enregistré sur
filters.controls.operator.prompt_text=Choisissez un opérateur
Dialog.filters.clear=Réinitialiser
filter.operators.eq=Équivaut à
filter.operators.ne=Pas égal à
filter.operators.gt=Supérieur à
filter.operators.lt=Moins que
filter.operators.before=Avant
filter.operators.before_or_today=Avant ou sur
filter.operators.after=Après
filter.operators.after_or_today=Après ou sur
filter.operators.between=Entre
filter.operators.contains=Contient
filter.operators.gte=Plus grand ou égal
filter.operators.lte=Moins que ou égaux
filter.operators.start_with=Commence par
filter.operators.ends_with=Se termine par
filter.operators.in=Dans
filter.operators.is_null=Est nul
and=et
filter.operators.nn=N'est pas nul
filters.sorting.title=Tri
msg.restart_notice=Configuration à l'échelle du système mise à jour. L'application doit être redémarrée pour appliquer les modifications.
stage.notificationPane.restart.actions.text=Redémarrage
settings.advanced.db.name=Nom de base de données
fosa.submissions.context_menu.actions.edit=Modifier
choices.region.west=Région ouest
choices.region.south_west=Sud-ouest
fosa.form.fields.bike_count.title=Vélos
fosa.form.fields.car_count.title=Voitures
fosa.form.fields.tablet_count.title=Comprimés
fosa.form.fields.printer_count.title=Imprimantes
fosa.form.fields.pc_count.title=Ordinateur
msg.discard_msg.txt=Êtes-vous sûr de vouloir éliminer les modifications que vous avez apportées?
choices.gender.male=Homme
choices.gender.female=Femme
choices.ed_level.secondary=Secondaire
choices.ed_level.advanced=Plus haut
choices.ed_level.primary=Primaire
choices.ed_level.none=Aucun
choices.nz2pr56.v_good=Très bien
choices.nz2pr56.average=Moyenne
choices.nz2pr56.none=Aucun
choices.nz2pr56.good=Bien
data_personnel.columns.email.title=E-mail
msg.ok=D'accord
forms.header.actions.navigation.prev=Crévuré
forms.header.actions.navigation.next=Suivant
forms.header.controls.index=Indice
fosa.form.fields.index=Indice
forms.header.controls.validation_code=Code de validation
forms.header.date.new=Nouvelle soumission
forms.header.index_search.prompt=Recherche d'index
field_mapper.title=Formez du mappeur sur le terrain
mapper.categories.forms.fosa.base_fields.title=Champs de base
mapper.categories.forms.any.sub_forms.title=Sous-formulaires
mapper.categories.forms.fosa.sub_forms.title=Sous-formulaires
mapper.categories.forms.chefferie.sub_forms.title=Sous-formulaires
mapper.categories.forms.fosa.sub_forms.data_personnel.title=Personnel Info
mapper.categories.forms.chefferie.sub_forms.data_personnel.title=Personnel Info
fosa.form.fields.validation_code=Code de validation
mapper.categories.forms.fosa.sub_forms.stats_0.title=Statistiques vitales (ligne 1)
mapper.categories.forms.fosa.sub_forms.stats_1.title=Statistiques vitales (ligne 2)
mapper.categories.forms.fosa.sub_forms.stats_2.title=Statistiques vitales (ligne 3)
mapper.categories.forms.fosa.sub_forms.stats_3.title=Statistiques vitales (ligne 4)
mapper.categories.forms.fosa.sub_forms.stats_4.title=Statistiques vitales (ligne 5)
fosa.columns.year.0=Année
fosa.columns.year.1=Année
fosa.columns.year.2=Année
fosa.columns.year.3=Année
fosa.columns.year.4=Année
fosa.columns.deaths.0=# des décès enregistrés
fosa.columns.deaths.1=# des décès enregistrés
fosa.columns.deaths.2=# des décès enregistrés
fosa.columns.deaths.3=# des décès enregistrés
fosa.columns.deaths.4=# des décès enregistrés
fosa.columns.births.0=# des naissances enregistrées
fosa.columns.births.1=# des naissances enregistrées
fosa.columns.births.2=# des naissances enregistrées
fosa.columns.births.3=# des naissances enregistrées
fosa.columns.births.4=# des naissances enregistrées
fosa.form.fields.responding_device.title=Quel appareil utilisez-vous pour remplir le questionnaire?
chefferie.submissions.title=Submission - CHEFFERIE
chefferie.columns.submitted=Ajouter la soumission
chefferie.columns.recorded_at=Soumis
chefferie.columns.last_updated_by=Enregistré à
chefferie.columns.last_updated_at=Dernière mise à jour par
chefferie.add_submission=Dernière mise à jour à
chefferie.form.sections.respondent.title=Intimé
chefferie.form.sections.structure_identification.title=Identification de la structure
chefferie.form.sections.service_offered_and_amenities.title=Services offerts et équipements
chefferie.form.sections.infra_eq.title=Infrastructure et équipement
chefferie.form.sections.personnel_status.title=Personnel Status
chefferie.form.finish=Finition
chefferie.form.discard=Jeter
chefferie.form.fields.names.title=Noms de premier et de famille
chefferie.form.fields.position.title=Fonction
chefferie.form.fields.position.description=Position / fonction dans l'établissement de santé
chefferie.form.fields.phone.title=Numéro de téléphone
chefferie.form.fields.phone.description=Numéro de téléphone (de préférence WhatsApp)
chefferie.form.fields.email.title=E-mail
chefferie.form.fields.creation_date.title=Créé à
chefferie.form.fields.creation_date.description=Année de création de l'établissement de santé (DD / mm / yyyy)
chefferie.form.fields.email.description=Adresse e-mail (e-mail de travail)
chefferie.form.msg.invalid_value=Valeur non valide
chefferie.form.fields.environment.options.urban.title=Urbain
chefferie.form.fields.environment.options.rural.title=Rural
chefferie.form.fields.region.title=Région
chefferie.form.fields.department.title=Division
chefferie.form.fields.department.description=Division dans la région
chefferie.form.fields.communes.title=Ville / ville
chefferie.form.fields.quarter.title=Quartier
chefferie.form.fields.name.title=Nom de la Cheffery
chefferie.form.fields.classification.title=Classification
chefferie.form.fields.classification.description=Classification of the chefferie
chefferie.form.fields.distance.title=Distance du centre de statut civil le plus proche
chefferie.form.sections.geo_point.title=Coordonnées géographiques
chefferie.form.fields.classification.option.first=1ier degr� ou Lamidat
chefferie.form.fields.classification.option.second=2e degr
chefferie.form.fields.fonction.title=Fonction de statut civil
chefferie.form.fields.fonction.description=Fonction de statut civil exercé par le chef ou une notable dans la chefferie
chefferie.form.fields.benefit.title=Prestation de serment
chefferie.form.fields.benefit.description=Jurer dans le chef ou notable de la chefferie
chefferie.form.fields.conservation_place.title=Lieu de conservation
chefferie.form.fields.conservation_place.description=Lieu de conservation des registres de statut civil
chefferie.form.fields.training.title=L'officier de statut civil est-il formé
chefferie.form.fields.training.description=Formation reçue sur le statut civil du chef ou une notable de la chefferie
chefferie.form.fields.waiting_room.title=Espace ou salle d'attente disponible
chefferie.form.fields.waiting_room.description=Espace ou salle d'attente disponible pour les utilisateurs
chefferie.form.fields.cs_actor_is_chief.title=Le chef exerce-t-il le statut civil?
chefferie.form.fields.reception_location.description=Zone de réception des utilisateurs dans la chefferie
chefferie.form.fields.toilets_accessible.title=Disponibilité des toilettes
chefferie.form.fields.toilets_accessible.description=Disponibilité des toilettes accessibles aux utilisateurs
chefferie.form.fields.fonction.option.first=Oui, officier de statut civil
chefferie.form.fields.fonction.option.second=Oui, secrétaire du statut civil
chefferie.form.fields.fonction.option.third=Non
chefferie.form.fields.benefit.option.first=Oui
chefferie.form.fields.benefit.option.second=Non
chefferie.form.fields.conservation_place.option.first=Dans une pièce réservée
chefferie.form.fields.conservation_place.option.second=Dans la maison du chef
chefferie.form.fields.conservation_place.option.third=D'autres (veuillez spécifier)
chefferie.form.fields.training.option.first=Oui
chefferie.form.fields.training.option.second=Non
chefferie.form.fields.waiting_room.option.first=Oui
chefferie.form.fields.waiting_room.option.second=Non
chefferie.form.fields.reception_location.option.first=Dans une salle r�serv�e
chefferie.form.fields.reception_location.option.second=Dans le domicile du chef
chefferie.form.fields.reception_location.option.third=Autres (A pr�ciser)
chefferie.form.fields.toilets_accessible.option.first=Oui
chefferie.form.fields.toilets_accessible.option.second=Non
chefferie.form.fields.Functional_equipment.title=Équipement fonctionnel
chefferie.form.fields.Functional_equipment.description=Équipement fonctionnel dans la chefferie: types et quantités
chefferie.form.fields.equipment_question.title=Équipement fonctionnel dans la chefferie: types et quantités
chefferie.form.fields.equipment_quantity.computers=Ordinateur
chefferie.form.fields.equipment_quantity.tablets=Comprimés
chefferie.form.fields.equipment_quantity.printers=Imprimantes
chefferie.form.fields.equipment_quantity.cars=Voitures
chefferie.form.fields.equipment_quantity.motorcycles=Motos
chefferie.form.fields.structure.title=La chefferie est-elle la résidence du chef?
chefferie.form.fields.structure.description=Le bâtiment de chefferie est-il, la résidence du chef?
chefferie.form.fields.connexion.title=accès Internet
chefferie.form.fields.connexion.description=Chefferie connexion Internet
chefferie.form.fields.typeConnexion.title=Type de connexion Internet
chefferie.form.fields.typeConnexion.description=Type de connexion Internet disponible
chefferie.form.fields.eneoConnexion.title=Accès ENEO
chefferie.form.fields.eneoConnexion.description=Connexion de la chefferie au réseau d'électricité (ENEO)
chefferie.form.fields.waterAcces.title=Disponibilité de l'eau
chefferie.form.fields.waterAcces.description=Disponibilité d'une source d'approvisionnement en eau dans la chefferie
chefferie.form.fields.waterType.title=Source d'eau disponible (s) disponible
chefferie.form.fields.waterType.description=Type de source d'alimentation en eau
chefferie.form.fields.extinguisher.title=Extincteur de feu
chefferie.form.fields.extinguisher.description=Extincteur de feu de travail disponible dans la chefferie
chefferie.form.fields.equipment_quantity.computers.description=Nombre d'ordinateurs
chefferie.form.fields.equipment_quantity.tablets.description=Nombre de comprimés
chefferie.form.fields.equipment_quantity.printers.description=Nombre d'imprimantes
chefferie.form.fields.equipment_quantity.cars.description=Nombre de voitures
chefferie.form.fields.equipment_quantity.motorcycles.description=Nombre de motos
chefferie.form.fields.structure.option.first=Oui
chefferie.form.fields.structure.option.second=Non
chefferie.form.fields.connexion.option.first=Oui
chefferie.form.fields.connexion.option.second=Non
chefferie.form.fields.type.connexion.option.first=2G
chefferie.form.fields.type.connexion.option.second=Zg
chefferie.form.fields.type.connexion.option.third=Hgu
chefferie.form.fields.type.connexion.option.fourth=ADSL (téléphone filaire)
chefferie.form.fields.type.connexion.option.fith=Fibre optique
chefferie.form.fields.eneo.connexion.option.first=Oui
chefferie.form.fields.eneo.connexion.option.second=Non
chefferie.form.fields.water.acces.option.first=Oui
chefferie.form.fields.water.acces.option.second=Non
chefferie.form.fields.water.type.option.first=Ewater
chefferie.form.fields.water.type.option.second=Bien construit / forage
chefferie.form.fields.water.type.option.third=Puits non développé / traditionnel
chefferie.form.fields.water.type.option.fourth=Cours d'eau
chefferie.form.fields.water.type.option.fith=D'autres (veuillez spécifier)
chefferie.form.fields.extinguisher.option.first=Oui
chefferie.form.fields.extinguisher.option.second=Non
chefferie.form.fields.employer.title=Personnel en charge de l'état civil
chefferie.form.fields.employer.description=Combien de membres du personnel sont chargés du statut civil dans la chefferie?
services.auth.user_not_found=Nom d'utilisateur ou mot de passe non valide
chefferie.form.fields.facility_name.title=Nom complet de la chefferie
chefferie.form.sections.extra.title=Commentaires et supplémentaires
fosa.form.sections.extra.title=Commentaires et supplémentaires
chefferie.form.fields.extra_info.description=Veuillez utiliser l'espace fourni pour ajouter toute information pertinente supplémentaire.
chefferie.form.fields.extra_info.title=Des informations supplémentaires
chefferie.form.fields.index=Indice
chefferie.form.fields.validation_code=Code de validation
chefferie.form.fields.other_water_source.description=Autres aliments disponibles en eau potable
chefferie.form.fields.other_water_source.title=Spécifiez la source d'eau
chefferie.form.fields.cs_actor_is_chief.description=La fonction de statut civil est-elle remplie par le chef ou notable dans la chefferie?
chefferie.form.fields.oath.title=Le chef ou le notable a-t-il prêté serment?
chefferie.form.fields.cs_reg_location.title=Emplacement des registres civils
chefferie.form.fields.other_cs_reg_location.title=Spécifiez le lieu du registre de l'état civil
chefferie.form.fields.other_internet_type.title=Spécifiez le type de connexion Internet
chefferie.form.fields.degree.options.first_degree.title=1er degré ou lamidat
chefferie.form.fields.degree.options.second_degree.title=Deuxième degré
chefferie.form.fields.other_waiting_room.title=Spécifiez l'emplacement de la salle d'attente
chefferie.form.fields.reception.title=Réception des utilisateurs
chefferie.form.sections.equipment.sections.equipment.title=Informations sur l'équipement
chefferie.form.sections.equipment.structure_info.title=Informations et installations du bâtiment
chefferie.form.fields.other_recep.title=Spécifiez la zone de réception
mapper.categories.forms.chefferie.base_fields.title=Champs de base
shell.menu.forms.csc=Formulaire CSC
csc.submissions.title=Soumissions - CSC
csc.add_submission=Ajouter la soumission
csc.columns.submitted=Soumis
csc.columns.recorded_at=Enregistré à
csc.columns.last_updated_by=Dernière mise à jour par
csc.columns.last_updated_at=Dernière mise à jour à
submissions.context_menu.actions.delete=Supprimer
csc.form.sections.respondent.title=Intimé
csc.form.sections.identification.title=Identification de la structure
csc.form.sections.accessibility.title=Accessibilité du centre
csc.form.sections.infrastructure.title=Infrastructure et équipement du centre
csc.form.sections.areas.title=Zones consacrées au statut civil
csc.form.sections.equipment.title=Installations du Civil Registry Center (équipement fonctionnel)
csc.form.sections.digitization.title=Numérisation / informatisation du statut civil
csc.form.sections.record_procurement.title=L'approvisionnement des dossiers
csc.form.sections.vital_stats.title=Ressources financières liées aux documents de statistiques cibles
csc.form.sections.deeds.title=Les actes réunis, non retirés au cours des 5 dernières années
mapper.categories.forms.csc.base_fields.sections.deeds.title=Les actes réunis, non retirés au cours des 5 dernières années
csc.form.sections.status_of_archived_records.title=Statut des enregistrements archivés
csc.form.sections.archiving_function.title=Archivage
csc.form.sections.personnel_info.title=Statut du personnel
csc.form.sections.comments.title=Commentaires et supplémentaires
csc.form.sections.respondent.fields.position.title=Position
csc.form.sections.respondent.fields.position.description=Rôle du répondant au sein du CSC
csc.form.sections.respondent.fields.phone.description=Inscrivez-vous (de préférence WhatsApp)
csc.form.sections.respondent.fields.phone.title=Numéro de téléphone
csc.form.sections.respondent.fields.email.title=Adresse email
csc.form.sections.respondent.fields.email.description=E-mail couramment utilisé ou professionnel du répondant
csc.form.sections.respondent.fields.knows_creation_date.description=Connaissez-vous la date de création du CSC?
csc.form.sections.respondent.fields.knows_creation_date.title=Connaît la date de création?
csc.form.sections.identification.fields.division.description=Choisissez le département auquel appartient le Civil Status Center
csc.form.sections.identification.fields.municipality.title=Commune / Municipalité
csc.form.sections.identification.fields.municipality.description=Indiquez la municipalité du Civil Status Center
csc.form.sections.identification.fields.quarter.title=Quart
csc.form.sections.identification.fields.quarter.description=Entrez le nom du quartier où se trouve le CSC
csc.form.fields.index.title=Indice
csc.form.fields.validation_code.title=Code de validation
csc.form.sections.identification.fields.facility.title=Nom de l'installation
csc.form.sections.identification.fields.category.title=Catégorie
csc.form.sections.identification.fields.council_size.title=Taille de la municipalité du Conseil
csc.form.sections.identification.fields.milieu.title=Milieu
csc.form.sections.identification.fields.attached_centers.title=Nombre de centres attachés
csc.form.sections.identification.fields.locality.title=Localité
csc.form.sections.identification.fields.creation_date.title=Date de création
csc.form.sections.identification.fields.functional.title=Le centre est-il fonctionnel?
csc.form.sections.identification.fields.non_function_reason.title=Pourquoi le centre n'est-il pas fonctionnel?
csc.form.sections.identification.fields.chiefdom_degree.title=Chefferie
csc.form.sections.identification.fields.other_non_function_reason.title=Spécifiez la raison de la non-fonctionnalité
csc.form.sections.identification.fields.fields.is_chiefdom.title=Le centre est-il une chefferie?
csc.form.sections.identification.fields.non_function_duration.title=Depuis combien de temps le centre est-il non fonctionnel?
csc.form.sections.identification.fields.sec_creation_order.title=Ordre de création secondaire
csc.form.sections.identification.fields.officer_appointment_order.title=Ordonnance de nomination des officiers
csc.form.sections.identification.fields.officer_appointed.title=L'officier est-il nommé?
csc.form.sections.identification.fields.photo_url.title=Photo du centre
csc.form.sections.identification.fields.gps_coords.title=Coordonnées GPS
csc.form.sections.identification.fields.division.title=Division
csc.form.sections.respondent.fields.creation_date.title=Date de création
csc.form.sections.respondent.fields.name.title=Noms de premier et de famille
csc.form.sections.accessibility.fields.road_type.title=Type de routes servant le centre
csc.form.sections.accessibility.fields.road_deteriorates.title=La route se détériore-t-elle périodiquement?
csc.form.sections.accessibility.fields.obstacle.title=Barrières limitant l'accès au centre
csc.form.sections.accessibility.fields.attached_villages_num.title=Nombre de villages attachés au centre
csc.form.sections.accessibility.fields.cover_radius.title=Rayon de couverture centrale
csc.form.sections.accessibility.sub_forms.villages.fields.name.title=Nom du village
csc.form.sections.accessibility.sub_forms.villages.fields.avg_distance.title=Distance moyenne de la CSC (en km)
csc.form.section.accessibility.sub_forms.villages.fields.observations.title=Observations
csc.form.sections.infra.fields.occupancy_status.title=Occupation
csc.form.sections.infra.fields.occupancy_status.description=Statut d'occupation du bâtiment central
csc.form.sections.infra.fields.other_building.title=Y a-t-il un autre bâtiment public?
csc.form.sections.infra.fields.eneo_connection.title=Zone de connexion
csc.form.sections.infra.fields.eneo_connection.description=Le centre est-il connecté au réseau national d'électricité (ENEO)?
csc.form.sections.infra.fields.power_outages.title=Interruptions de puissance fréquentes?
csc.form.sections.infra.fields.power_outages.description=Y a-t-il souvent des interruptions de l'énergie électrique?
csc.form.sections.infra.fields.stable_power.title=L'alimentation en électricité est-elle stable?
csc.form.sections.infra.fields.backup_power_available.title=Y a-t-il d'autres sources d'énergie électrique?
csc.form.sections.infra.fields.backup_power.title=Sélectionnez les sources d'énergie complémentaires fonctionnelles
csc.form.sections.infra.fields.other_backup_power.title=Spécifiez la source complémentaire
csc.form.sections.infra.fields.water_sources.title=Quelle source d'eau est disponible au centre?
csc.form.sections.infra.fields.toilets_available.title=Y a-t-il des toilettes disponibles?
csc.form.sections.infra.fields.separate_toilets_available.title=Les toilettes sont-elles séparées par sexe?
csc.form.sections.infra.fields.zone_operators.title=Quels opérateurs de télécommunications sont dans la zone?
csc.form.sections.infra.fields.has_fiber.title=Y a-t-il une connexion à fibre optique?
csc.form.sections.infra.fields.other_zone_operators.title=Spécifiez les opérateurs de télécommunications dans la zone
csc.form.sections.infra.fields.has_internet.title=Y a-t-il une connexion Internet?
csc.form.sections.infra.fields.internet_type.title=Quels opérateurs de télécommunications fournissent la connexion Internet?
csc.form.sections.infra.fields.other_internet_type.title=Spécifiez le type de fournisseur Internet
csc.form.sections.infra.fields.internet_sponsor.title=Qui paie pour la connexion Internet?
csc.form.sections.areas.fields.office_count.title=# des bureaux
csc.form.sections.areas.fields.dedicated_cs_rooms.title=Rooms CS dédiés?
csc.form.sections.areas.fields.dedicated_cs_rooms.description=Y a-t-il d'autres chambres dédiées pour le statut civil?
csc.form.sections.areas.fields.moving.title=Y a-t-il des plans émouvants?
csc.form.sections.areas.fields.moving.description=Est-il prévu d'emménager dans un nouveau bâtiment dans les prochains mois?
csc.form.sections.areas.sub_forms.rooms.fields.number.title=Numéro de chambre
csc.form.sections.areas.sub_forms.rooms.fields.name.title=Nom de chambre
csc.form.sections.areas.sub_forms.rooms.fields.condition.title=Condition
csc.form.sections.areas.sub_forms.rooms.fields.dimension.title=Dimensions
csc.form.sections.areas.sub_forms.rooms.fields.renovation.title=Nature du travail de rénovation
csc.form.sections.equipment.fields.pc_count.title=# des ordinateurs
csc.form.sections.equipment.fields.server_count.title=# des serveurs
csc.form.sections.equipment.fields.printer_count.title=# des imprimantes
csc.form.sections.equipment.fields.scanner_count.title=# de scanners
csc.form.sections.equipment.fields.inverters.title=# des onduleurs
csc.form.sections.equipment.fields.conditioners.title=# de conditionneurs
csc.form.sections.equipment.fields.fans.title=# de fans
csc.form.sections.equipment.fields.projectors.title=# de projecteurs
csc.form.sections.equipment.fields.office_tables.title=# des tables de bureau
csc.form.sections.equipment.fields.chairs.title=# de chaises
csc.form.sections.equipment.fields.cars.title=# de voitures
csc.form.sections.equipment.fields.bikes.title=# de vélos
csc.form.sections.equipment.fields.tablets.title=# de tablettes
csc.form.sections.digitization.fields.using_info_sys_outside_cs.title=Utilisation d'un système à l'extérieur de CR
csc.form.sections.digitization.fields.using_info_sys_outside_cs.description=En dehors du registre civil, tout autre département du centre utilise-t-il un système informatisé
csc.form.sections.digitization.fields.external_cr_uses_internet.title=Si oui, ce système utilise-t-il Internet?
csc.form.sections.digitization.fields.has_cs_software.title=Logiciel équipé?
csc.form.sections.digitization.fields.has_cs_software.description=Le centre est-il équipé d'un ou plusieurs logiciels pour le statut civil?
csc.form.sections.digitization.fields.cs_software_name.title=Quel est le (s) nom (s) du logiciel?
csc.form.sections.digitization.fields.cs_software_license_sponsor.title=Comment le logiciel a-t-il été acquis?
csc.form.sections.digitization.fields.other_cs_software_license_sponsor.title=Spécifiez la méthode d'acquisition du logiciel
csc.form.sections.digitization.fields.users_receive_digital_acts.title=Les documents numériques sont-ils donnés aux utilisateurs?
csc.form.sections.digitization.fields.software_activation_date.title=Date d'activation du logiciel
csc.form.sections.digitization.fields.software_feedback.title=Quels sont vos commentaires sur le logiciel?
csc.form.sections.digitization.fields.software_trained_user_count.title=# d'utilisateurs formés
csc.form.sections.digitization.fields.software_recorded_marriage_count.title=# de certificats de mariage
csc.form.sections.digitization.fields.software_recorded_marriage_count.description=# des certificats de mariage enregistrer dans le logiciel
csc.form.sections.digitization.fields.software_recorded_birth_count.title=# des certificats de naissance
csc.form.sections.digitization.fields.software_recorded_birth_count.description=# des certificats de naissance Registre dans le logiciel
csc.form.sections.digitization.fields.software_recorded_death_count.title=# des certificats de décès
csc.form.sections.digitization.fields.software_recorded_death_count.description=# des certificats de décès enregistrer dans le logiciel
csc.form.sections.digitization.fields.software_is_functional.title=Le logiciel est-il fonctionnel?
csc.form.sections.digitization.fields.software_dysfunction_reason.title=Pourquoi le logiciel n'est-il pas fonctionnel?
csc.form.sections.indexing.fields.records_scanned.title=CS Records scanned?
csc.form.sections.indexing.fields.records_scanned.description=Les dossiers du statut civil ont-ils été numérisés (scannés) dans ce centre de statut civil?
csc.form.sections.indexing.fields.staff_trained.title=Le personnel formé?
csc.form.sections.indexing.fields.staff_trained.description=Le personnel du Civil Status Center a-t-il été formé à l'utilisation du logiciel de numérisation?
csc.form.sections.indexing.fields.document_scan_start_date.title=Analyser la date de début
csc.form.sections.indexing.fields.is_data_indexed.title=Les données ont-elles été indexées?
csc.form.sections.indexing.fields.marriages_indexed.title=# des mariages indexés
csc.form.sections.indexing.fields.deaths_indexed.title=# des décès indexés
csc.form.sections.indexing.fields.births_indexed.title=# des naissances indexées
csc.form.sections.indexing.fields.marriages_scanned.title=# des mariages numérisés
csc.form.sections.indexing.fields.births_scanned.title=# des naissances scannées
csc.form.sections.indexing.fields.deaths_scanned.title=# de décès scannés
csc.form.sections.indexing.fields.is_data_in_use.title=Les données sont-elles utilisées?
csc.form.sections.indexing.fields.data_usage.title=Comment les données sont-elles utilisées?
csc.form.sections.record_procurement.fields.lack_of_registers.title=Y a-t-il eu un manque de registres?
csc.form.sections.record_procurement.fields.lack_of_registers.description=Y a-t-il eu un manque de registres au cours de ces années?
csc.form.sections.record_procurement.fields.records_provider.title=Fournisseur de dossiers
csc.form.sections.record_procurement.fields.records_provider.description=Qui vous a fourni des records pour cette année 2025
csc.form.sections.record_procurement.fields.other_records_provider.title=Veuillez spécifier le fournisseur de dossiers
csc.form.sections.record_procurement.fields.non_compliant_registers_used.title=Utilisation des registres personnalisés
csc.form.sections.record_procurement.fields.non_compliant_registers_used.description=Avez-vous souvent dû acheter les registres sur le marché pour la création des actes?
csc.form.sections.record_procurement.fields.blank_registries.title=Registres vierges
csc.form.sections.record_procurement.fields.blank_marriages.title=# de registres de mariage vide
csc.form.sections.record_procurement.fields.blank_births.title=# de registres de naissance vierges
csc.form.sections.record_procurement.fields.blank_deaths.title=# de registres de mort vierges
controls.file_picker.placeholder.txt=Cliquez ci-dessous pour sélectionner une image
csc.form.sections.vital_stats.fields.birth_cert_cost.title=Coût des certificats de naissance (FCFA)
csc.form.sections.vital_stats.fields.birth_cert_copy_cost.title=Coût de la copie des certificats de naissance (FCFA)
csc.form.sections.vital_stats.fields.marriage_cert_copy_cost.title=Coût de la copie des certificats de mariage (FCFA)
csc.form.sections.vital_stats.fields.death_cert_copy_cost.title=Coût de la copie des certificats de décès (FCFA)
csc.form.sections.vital_stats.fields.celibacy_cert_copy_cost.title=Coût du certificat de célibat (FCFA)
csc.form.sections.vital_stats.fields.non_registered_certs.title=# de certificats non enregistrés
csc.form.sections.vital_stats.fields.rates_under_deliberation.title=Les tarifs sont-ils sous délibération?
csc.form.sections.vital_stats.fields.rates_under_deliberation.description=Ces taux sont-ils actuellement l'objet d'une délibération par le Conseil municipal?
csc.form.sections.vital_stats.fields.prices_displayed.title=Ces prix sont-ils affichés?
csc.form.sections.vital_stats.fields.municipality_budget.title=2024 Budget
csc.form.sections.vital_stats.fields.municipality_budget.description=Quel est le budget de la municipalité pour l'année 2024?
csc.form.sections.vital_stats.fields.cs_budget.title=Part de statut civil
csc.form.sections.vital_stats.fields.cs_budget.description=Quelle a été la part consacrée au statut civil en 2024?
csc.form.sections.archiving.fields.archiving_room.title=Le centre a-t-il une salle d'archivage?
csc.form.sections.archiving.fields.archiving_room_electric_condition.title=Quel est l'état du circuit électrique dans la salle d'archives principale?
csc.form.sections.archiving.fields.fire_extinguishers.title=La salle a-t-elle un ou plusieurs extincteurs?
csc.form.sections.archiving.fields.locked_door.title=Est-ce que la pièce dans laquelle les registres sont archivés ont une porte verrouillée
csc.form.sections.archiving.fields.access_limited.title=L'accès à la salle des archives est-il limité à une catégorie de personnel?
csc.form.sections.archiving.fields.room_has_humidity.title=Problèmes d'étanchéité?
csc.form.sections.archiving.fields.room_has_humidity.description=La pièce dans laquelle les registres sont archivés montrent-ils des traces d'humidité (problèmes d'étanchéité)?
csc.form.sections.archiving.fields.register_archiving_type.title=Comment les registres sont-ils archivés?
csc.form.sections.archiving.fields.other_register_archiving_type.title=Façon alternative d'archiver les dossiers
csc.form.sections.archiving.fields.written_archiving_plan.title=Y a-t-il un plan d'archivage enregistré écrit?
csc.form.sections.archiving.fields.registers_deposited.title=Tous les registres de la sous-préfecture ont-ils été déposés à la mairie?
csc.form.sections.archiving.fields.registers_deposited_systematically.title=Les registres sont-ils systématiquement soumis à la mairie à la fin de l'année?
csc.form.sections.archiving.fields.vandalized.title=Vandalisation
csc.form.sections.archiving.fields.vandalized.description=Les archives ont-elles fait l'objet de vols ou d'actes de vandalisme?
csc.form.sections.archiving.fields.vandalized_date.title=Pouvez-vous décrire le contexte et la date?
csc.form.sections.archiving.sections.general.title=Général
csc.form.sections.accessibility.sections.general.title=Général
csc.form.sections.personnel.sections.general.title=Général
csc.form.sections.personnel.sections.personnel.title=Liste du personnel (officiers et non-officiers)
csc.form.sections.accessibility.sections.villages.title=Villages attachés
csc.form.sections.archiving.sections.deeds.title=Les actes réunis, non retirés au cours des 5 dernières années
csc.form.sections.comments.fields.relevant_info.title=Informations pertinentes
csc.form.sections.deeds.fields.year.title=Année
csc.form.sections.deeds.fields.birth_certs_drawn.title=Certificats de naissance rédigés
csc.form.sections.deeds.fields.births_certs_not_withdrawn.title=Certificats de naissance non retirés
csc.form.sections.deeds.fields.marriage_certs_drawn.title=Certificats de mariage rédigés
csc.form.sections.deeds.fields.marriage_certs_not_withdrawn.title=Certificats de mariage non retirés
csc.form.sections.deeds.fields.death_certs_drawn.title=Certificats de décès tirés
csc.form.sections.deeds.fields.death_certs_not_withdrawn.title=Certificats de décès non retirés
csc.form.sections.archive_stats.fields.year.title=Année
csc.form.sections.archive_stats.fields.birth_count.title=# des registres de naissance archivés
csc.form.sections.archive_stats.fields.marriage_count.title=# des registres de mariage archivés
csc.form.sections.archive_stats.fields.death_count.title=# des registres de la mort archivés
csc.form.sections.personnel_info.fields.male_count.title=# des hommes
csc.form.sections.personnel_info.fields.female_count.title=# des femmes
csc.form.sections.personnel_info.fields.non_officer_male_count.title=Non-officiers masculins
csc.form.sections.personnel_info.fields.non_officer_female_count.title=Non-officiers féminins
csc.form.sections.personnel_info.sub_forms.officers.fields.other_position.title=Position alternative
csc.form.sections.personnel_info.sub_forms.officers.fields.status.title=Statut
csc.form.sections.personnel_info.sub_forms.officers.fields.other_status.title=Statut alternatif
csc.form.sections.personnel_info.sub_forms.officers.fields.allowance_2022.title=Allocation (2022)
csc.form.sections.personnel_info.sub_forms.officers.fields.revenue_2022.title=Revenus (2022)
csc.form.sections.personnel_info.sub_forms.officers.fields.archiving_training.title=A une formation d'archivage
csc.form.sections.personnel_info.sub_forms.officers.fields.seniority.title=Ancienneté
data_personnel.columns.status.title=Statut professionnel
data_personnel.columns.ec_training.title=A une formation sur le statut civil
data_personnel.columns.has_pc_training.title=A une formation informatique
data_personnel.columns.archiving_training.title=A une formation d'archivage
data_personnel.columns.monthly_revenue.title=Revenus mensuels
range_0_100=min
range_1_50=min
range_1980_current_year=min
range_0_80000=min
csc.form.base_fields.sections.accessibility.sub_forms.villages.title=Liste des villages ci-joints
mapper.categories.forms.csc.base_fields.sections.infrastructure.title=Infrastructure et équipement du centre
mapper.categories.forms.csc.base_fields.sections.respondent.title=L'intimé
mapper.categories.forms.csc.base_fields.sections.identification.title=Identification du centre
mapper.categories.forms.csc.base_fields.sections.accessibility.title=Accessibilité au centre
mapper.categories.forms.csc.base_fields.sections.accessibility.sub_forms.villages.title=Villages attachés
mapper.categories.forms.csc.base_fields.sections.areas.title=Zones consacrées au statut civil
mapper.categories.forms.csc.base_fields.sections.areas.sub_forms.rooms.title=État des chambres consacrées au statut civil
mapper.categories.forms.csc.base_fields.sections.equipment.title=Installations du Civil Registry Center (équipement fonctionnel)
mapper.categories.forms.csc.base_fields.sections.digitization.title=Numérisation / informatisation du statut civil
mapper.categories.forms.csc.base_fields.sections.record_procurement.title=L'approvisionnement des dossiers
mapper.categories.forms.csc.base_fields.sections.stats.title=Ressources financières liées aux documents de statistiques cibles
controls.gps.conn_notice=Impossible de se connecter à Internet. Veuillez vérifier votre connexion.
csc.form.sections.indexing.title=Analyse des enregistrements et indexation
csc.form.sections.areas.fields.office_count.description=Combien de chambres sont dédiées au statut civil?
csc.form.base_fields.sections.areas.sub_forms.rooms.title=Statut des espaces dédiés au statut civil
mapper.categories.forms.csc.base_fields.sections.indexing.title=Analyse / indexation des documents
mapper.categories.forms.csc.base_fields.sections.archiving.title=Archivage
mapper.categories.forms.csc.base_fields.sections.records.title=Nombre de dossiers archivés (2020 à 2024)
mapper.categories.forms.csc.base_fields.sections.comments.title=Commentaires et supplémentaires
mapper.categories.forms.csc.base_fields.sections.personnel.sub_forms.personnel_info.title=Statut du personnel
mapper.categories.forms.csc.base_fields.sections.personnel.sub_forms.personnel_info.sections.general.title=Général
mapper.categories.forms.csc.base_fields.sections.personnel.sub_forms.personnel_info.sections.staff.title=Liste du personnel (officiers et non-officiers)
submissions.columns.index=Indice
submissions.columns.facility_name=Nom de l'installation
filters.facility_name.title=Nom de l'installation
filters.index.title=Indice
submissions.filter.prompt=Filtre par "nom de l'installation", "code de validation", "index"
`;

from([{key: 'en', data: en}, {key: 'fr', data: fr}]).pipe(
  groupBy(v => v.key),
  mergeMap($group => $group.pipe(
    mergeMap(({data}) => data.split('\n')),
    filter(v => v.length > 0),
    map(v => v.split('=')),
    reduce((acc, [path, value]) => {
      return set(acc, path, value);
    }, {}),
    map(stringify),
    map(yaml => ({key: $group.key, yaml}))
  ))
).subscribe(async ({key, yaml}) => {
  const path = join(__dirname, 'projects', 'electron', 'assets', 'i18n', `${key}.yml`);
  const dir = resolve(path, '..');
  if (!existsSync(dir))
    await mkdir(dir);
  await writeFile(path, yaml);
  console.log('done');
});
