/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */

export type FindSparseIndexRangesParams = {
/**
 * @minimum 1
 */
limit?: number;
after?: string;
includeArchived?: boolean;
};
