/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */

export type ToggleSubmissionApprovalStatusParams = {
	/**
	 * The form identifier
	 */
	form: string;
	/**
	 * The form version to use, leave empty to use the latest or current version
	 */
	fv?: string;
	/**
	 * The submission version to use, leave empty to use the latest or current version
	 */
	sv?: string;
};
