/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import {
  PullDocumentChanges200,
  PushDocumentChanges200
} from '../../../../../../libs/sdk/models';
import type {
  PullDocumentChanges200Output,
  PullDocumentChangesParams,
  PushDocumentChange,
  PushDocumentChanges200Output
} from '../../../../../../libs/sdk/models';

import {
  map
} from 'rxjs';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
): Record<string, AngularHttpParamValueWithNullable> {
  const filteredParams: Record<string, AngularHttpParamValueWithNullable> = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      preserveRequiredNullables &&
      value === null &&
      requiredNullableKeys.has(key)
    ) {
      filteredParams[key] = null;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}





@Injectable()
export class DocumentsService {
  private readonly http = inject(HttpClient);
/**
 * Pull changes from after a checkpoint
 * @summary Pull document changes
 */
 pullDocumentChanges<TData = PullDocumentChanges200Output>(collection: string,
    params?: PullDocumentChangesParams, options?: HttpClientBodyOptions): Observable<TData>;
 pullDocumentChanges<TData = PullDocumentChanges200Output>(collection: string,
    params?: PullDocumentChangesParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 pullDocumentChanges<TData = PullDocumentChanges200Output>(collection: string,
    params?: PullDocumentChangesParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  pullDocumentChanges<TData = PullDocumentChanges200Output>(
    collection: string,
    params?: PullDocumentChangesParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/docs/${collection}/pull`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: PullDocumentChanges200.parse(event.body) as TData }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/docs/${collection}/pull`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    ).pipe(map(response => response.clone({ body: PullDocumentChanges200.parse(response.body) as TData })));
    }

    return this.http.get<TData>(
      `/api/docs/${collection}/pull`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    ).pipe(map(data => PullDocumentChanges200.parse(data) as TData));
  }
/**
 * @summary Push document changes
 */
 pushDocumentChanges<TData = PushDocumentChanges200Output>(pushDocumentChange: PushDocumentChange[], options?: HttpClientBodyOptions): Observable<TData>;
 pushDocumentChanges<TData = PushDocumentChanges200Output>(pushDocumentChange: PushDocumentChange[], options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 pushDocumentChanges<TData = PushDocumentChanges200Output>(pushDocumentChange: PushDocumentChange[], options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  pushDocumentChanges<TData = PushDocumentChanges200Output>(
    pushDocumentChange: PushDocumentChange[], options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/docs/push`,
      pushDocumentChange,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: PushDocumentChanges200.parse(event.body) as TData }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/docs/push`,
      pushDocumentChange,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    ).pipe(map(response => response.clone({ body: PushDocumentChanges200.parse(response.body) as TData })));
    }

    return this.http.post<TData>(
      `/api/docs/push`,
      pushDocumentChange,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    ).pipe(map(data => PushDocumentChanges200.parse(data) as TData));
  }
};

