/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFormVersionDefinitionFromDiscriminatorValue, type FormVersionDefinition } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/forms/{form}/definition
 */
export interface DefinitionRequestBuilder extends BaseRequestBuilder<DefinitionRequestBuilder> {
    /**
     * Get a form's definition by version
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FormVersionDefinition>}
     */
     get(requestConfiguration?: RequestConfiguration<DefinitionRequestBuilderGetQueryParameters> | undefined) : Promise<FormVersionDefinition | undefined>;
    /**
     * Get a form's definition by version
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<DefinitionRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get a form's definition by version
 */
export interface DefinitionRequestBuilderGetQueryParameters {
    version?: string;
}
/**
 * Uri template for the request builder.
 */
export const DefinitionRequestBuilderUriTemplate = "{+baseurl}/api/forms/{form}/definition{?version*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const DefinitionRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DefinitionRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createFormVersionDefinitionFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
