/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const baseDateFieldPropsOneRequiredDefault = true;
export const baseDateFieldPropsOneReadonlyDefault = false;
export const baseDateFieldPropsOneTitleDefault = ``;
export const baseDateFieldPropsOneDescriptionDefault = null;
export const baseDateFieldPropsOneDataKeyDefault = null;
export const baseDateFieldPropsTwoMinDefault = null;
export const baseDateFieldPropsTwoMaxDefault = null;
export const BaseDateFieldProps = zod.object({
  "required": zod.boolean().nullable().default(baseDateFieldPropsOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(baseDateFieldPropsOneReadonlyDefault),
  "title": zod.string().default(baseDateFieldPropsOneTitleDefault),
  "description": zod.string().nullish().default(baseDateFieldPropsOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(baseDateFieldPropsOneDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(baseDateFieldPropsTwoMinDefault),
  "max": zod.number().nullable().default(baseDateFieldPropsTwoMaxDefault)
}))

export type BaseDateFieldProps = zod.input<typeof BaseDateFieldProps>;
