/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const baseFormItemDefinitionWithoutIdPathDefault = null;
export const baseFormItemDefinitionWithoutIdTagsDefault = [];
export const baseFormItemDefinitionWithoutIdRelevanceEnabledDefault = true;
export const baseFormItemDefinitionWithoutIdRelevanceOperatorDefault = `and`;
export const baseFormItemDefinitionWithoutIdRelevanceLogicItemExpressionsItemFieldDefault = null;
export const baseFormItemDefinitionWithoutIdRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const baseFormItemDefinitionWithoutIdRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const baseFormItemDefinitionWithoutIdRelevanceLogicItemExpressionsItemValueDefault = null;
export const BaseFormItemDefinitionWithoutId = zod.object({
  "path": zod.string().nullable().default(baseFormItemDefinitionWithoutIdPathDefault),
  "tags": zod.array(zod.string()).default(baseFormItemDefinitionWithoutIdTagsDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(baseFormItemDefinitionWithoutIdRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(baseFormItemDefinitionWithoutIdRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(baseFormItemDefinitionWithoutIdRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(baseFormItemDefinitionWithoutIdRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(baseFormItemDefinitionWithoutIdRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(baseFormItemDefinitionWithoutIdRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
})

export type BaseFormItemDefinitionWithoutId = zod.input<typeof BaseFormItemDefinitionWithoutId>;
