/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const baseFormItemGroupOnePathDefault = null;
export const baseFormItemGroupOneTagsItemKeyDefault = null;
export const baseFormItemGroupOneTagsItemValueDefault = null;
export const baseFormItemGroupOneTagsDefault = [];
export const baseFormItemGroupOneMetaTagDefault = null;
export const baseFormItemGroupOneRelevanceEnabledDefault = true;
export const baseFormItemGroupOneRelevanceOperatorDefault = `and`;
export const baseFormItemGroupOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const baseFormItemGroupOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const baseFormItemGroupOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const baseFormItemGroupOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const BaseFormItemGroup = zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(baseFormItemGroupOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(baseFormItemGroupOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(baseFormItemGroupOneTagsItemValueDefault)
})).default(baseFormItemGroupOneTagsDefault),
  "metaTag": zod.string().nullish().default(baseFormItemGroupOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(baseFormItemGroupOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(baseFormItemGroupOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(baseFormItemGroupOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(baseFormItemGroupOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(baseFormItemGroupOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(baseFormItemGroupOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['group'])
}))

export type BaseFormItemGroup = zod.input<typeof BaseFormItemGroup>;
export type BaseFormItemGroupOutput = zod.output<typeof BaseFormItemGroup>;
