/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const baseFieldPropsRequiredDefault = true;
export const baseFieldPropsReadonlyDefault = false;
export const baseFieldPropsTitleDefault = ``;
export const baseFieldPropsDescriptionDefault = null;
export const baseFieldPropsDataKeyDefault = null;
export const BaseFieldProps = zod.object({
  "required": zod.boolean().nullable().default(baseFieldPropsRequiredDefault),
  "readonly": zod.boolean().nullable().default(baseFieldPropsReadonlyDefault),
  "title": zod.string().default(baseFieldPropsTitleDefault),
  "description": zod.string().nullish().default(baseFieldPropsDescriptionDefault),
  "dataKey": zod.string().nullish().default(baseFieldPropsDataKeyDefault)
})

export type BaseFieldProps = zod.input<typeof BaseFieldProps>;
