/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const ChangedDocumentItem = zod.object({
  "collection": zod.string(),
  "data": zod.record(zod.string(), zod.unknown())
})

export type ChangedDocumentItem = zod.input<typeof ChangedDocumentItem>;
export type ChangedDocumentItemOutput = zod.output<typeof ChangedDocumentItem>;
