/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const CreateNewForm201 = zod.object({
  "slug": zod.string(),
  "version": zod.uuid()
})

export type CreateNewForm201 = zod.input<typeof CreateNewForm201>;
export type CreateNewForm201Output = zod.output<typeof CreateNewForm201>;
