/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const findFormDefinitionByVersionParamsArchivedDefault = false;
export const FindFormDefinitionByVersionParams = zod.object({
  "archived": zod.boolean().default(findFormDefinitionByVersionParamsArchivedDefault),
  "version": zod.uuid().optional()
})

export type FindFormDefinitionByVersionParams = zod.input<typeof FindFormDefinitionByVersionParams>;
