/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const formItemNoteUpdateOneOneInLibraryDefault = false;
export const formItemNoteUpdateOneTwoOnePathDefault = null;
export const formItemNoteUpdateOneTwoOneTagsItemKeyDefault = null;
export const formItemNoteUpdateOneTwoOneTagsItemValueDefault = null;
export const formItemNoteUpdateOneTwoOneTagsDefault = [];
export const formItemNoteUpdateOneTwoOneMetaTagDefault = null;
export const formItemNoteUpdateOneTwoOneRelevanceEnabledDefault = true;
export const formItemNoteUpdateOneTwoOneRelevanceOperatorDefault = `and`;
export const formItemNoteUpdateOneTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemNoteUpdateOneTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemNoteUpdateOneTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemNoteUpdateOneTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemNoteUpdateOneThreeOnePathDefault = null;
export const formItemNoteUpdateOneThreeOneTagsItemKeyDefault = null;
export const formItemNoteUpdateOneThreeOneTagsItemValueDefault = null;
export const formItemNoteUpdateOneThreeOneTagsDefault = [];
export const formItemNoteUpdateOneThreeOneMetaTagDefault = null;
export const formItemNoteUpdateOneThreeOneRelevanceEnabledDefault = true;
export const formItemNoteUpdateOneThreeOneRelevanceOperatorDefault = `and`;
export const formItemNoteUpdateOneThreeOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemNoteUpdateOneThreeOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemNoteUpdateOneThreeOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemNoteUpdateOneThreeOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemNoteUpdateOneThreeTwoConfigFontSizeDefault = 13;
export const FormItemNoteUpdate = zod.object({
  "inLibrary": zod.boolean().default(formItemNoteUpdateOneOneInLibraryDefault)
}).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemNoteUpdateOneTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemNoteUpdateOneTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemNoteUpdateOneTwoOneTagsItemValueDefault)
})).default(formItemNoteUpdateOneTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemNoteUpdateOneTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemNoteUpdateOneTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemNoteUpdateOneTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemNoteUpdateOneTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemNoteUpdateOneTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemNoteUpdateOneTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemNoteUpdateOneTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
}))).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemNoteUpdateOneThreeOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemNoteUpdateOneThreeOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemNoteUpdateOneThreeOneTagsItemValueDefault)
})).default(formItemNoteUpdateOneThreeOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemNoteUpdateOneThreeOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemNoteUpdateOneThreeOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemNoteUpdateOneThreeOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemNoteUpdateOneThreeOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemNoteUpdateOneThreeOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemNoteUpdateOneThreeOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemNoteUpdateOneThreeOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['note']),
  "config": zod.object({
  "fontSize": zod.number().default(formItemNoteUpdateOneThreeTwoConfigFontSizeDefault)
})
})).and(zod.object({
  "type": zod.enum(['note'])
}))).and(zod.object({
  "type": zod.enum(['note'])
})).and(zod.object({
  "type": zod.enum(['note'])
}))

export type FormItemNoteUpdate = zod.input<typeof FormItemNoteUpdate>;
export type FormItemNoteUpdateOutput = zod.output<typeof FormItemNoteUpdate>;
