/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const formItemDefinitionOneOneOnePathDefault = null;
export const formItemDefinitionOneOneOneTagsItemKeyDefault = null;
export const formItemDefinitionOneOneOneTagsItemValueDefault = null;
export const formItemDefinitionOneOneOneTagsDefault = [];
export const formItemDefinitionOneOneOneMetaTagDefault = null;
export const formItemDefinitionOneOneOneRelevanceEnabledDefault = true;
export const formItemDefinitionOneOneOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionOneOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionOneOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionOneOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionOneOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionOneTwoOnePathDefault = null;
export const formItemDefinitionOneTwoOneTagsItemKeyDefault = null;
export const formItemDefinitionOneTwoOneTagsItemValueDefault = null;
export const formItemDefinitionOneTwoOneTagsDefault = [];
export const formItemDefinitionOneTwoOneMetaTagDefault = null;
export const formItemDefinitionOneTwoOneRelevanceEnabledDefault = true;
export const formItemDefinitionOneTwoOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionOneTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionOneTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionOneTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionOneTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionOneThreeConfigOneTitleDefault = null;
export const formItemDefinitionOneThreeConfigOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigOneRepeatableDefault = false;
export const formItemDefinitionOneThreeConfigOneDivisionCountDefault = 1;

export const formItemDefinitionOneThreeConfigOneOrientationDefault = `vertical`;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOnePathDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneTagsItemKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneTagsItemValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneTagsDefault = [];
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneMetaTagDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceEnabledDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOnePathDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneTagsItemKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneTagsItemValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneTagsDefault = [];
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneMetaTagDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneRelevanceEnabledDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoParentIdDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneOneAutoDataKeyDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneTwoDefaultValueLatMax = 90;

export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneTwoDefaultValueLongMax = 180;

export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneTwoDefaultValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoOneAutoDataKeyDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoTwoMinDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoTwoMaxDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoTwoDefaultValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigThreeOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigThreeOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigThreeOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigThreeOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigThreeOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigThreeOneAutoDataKeyDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigThreeTwoDefaultValueDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigThreeTwoRenderAsDefault = `checkbox`;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourOneAutoDataKeyDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourTwoPlaceholderDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourTwoPatternDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourTwoMinlengthDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourTwoMaxlengthDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourTwoDefaultValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveOneAutoDataKeyDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveTwoItemSourceRefDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveTwoDefaultValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveTwoHardItemsItemLabelDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveTwoHardItemsItemValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveTwoHardItemsDefault = [];
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixOneAutoDataKeyDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixTwoItemSourceRefDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixTwoDefaultValueDefault = [];
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixTwoHardItemsItemLabelDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixTwoHardItemsItemValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixTwoHardItemsDefault = [];
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenOneOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenOneOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenOneOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenOneOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenOneOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenOneOneAutoDataKeyDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenOneTwoMinDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenOneTwoMaxDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenTwoMinSelectionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenTwoMaxSelectionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenTwoDefaultValueDefault = [];
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightOneOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightOneOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightOneOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightOneOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightOneOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightOneOneAutoDataKeyDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightOneTwoMinDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightOneTwoMaxDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightTwoDefaultValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineOneOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineOneOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineOneOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineOneOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineOneOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineOneOneAutoDataKeyDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineOneTwoMinDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineOneTwoMaxDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineTwoDefaultValueDefault = { start: null, end: null };
export const formItemDefinitionOneThreeConfigTwoFieldsDefault = [];
export const formItemDefinitionTwoOneOnePathDefault = null;
export const formItemDefinitionTwoOneOneTagsItemKeyDefault = null;
export const formItemDefinitionTwoOneOneTagsItemValueDefault = null;
export const formItemDefinitionTwoOneOneTagsDefault = [];
export const formItemDefinitionTwoOneOneMetaTagDefault = null;
export const formItemDefinitionTwoOneOneRelevanceEnabledDefault = true;
export const formItemDefinitionTwoOneOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionTwoOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionTwoOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionTwoOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionTwoOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionTwoTwoOnePathDefault = null;
export const formItemDefinitionTwoTwoOneTagsItemKeyDefault = null;
export const formItemDefinitionTwoTwoOneTagsItemValueDefault = null;
export const formItemDefinitionTwoTwoOneTagsDefault = [];
export const formItemDefinitionTwoTwoOneMetaTagDefault = null;
export const formItemDefinitionTwoTwoOneRelevanceEnabledDefault = true;
export const formItemDefinitionTwoTwoOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionTwoTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionTwoTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionTwoTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionTwoTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionTwoTwoTwoConfigFontSizeDefault = 13;
export const formItemDefinitionThreeOneOnePathDefault = null;
export const formItemDefinitionThreeOneOneTagsItemKeyDefault = null;
export const formItemDefinitionThreeOneOneTagsItemValueDefault = null;
export const formItemDefinitionThreeOneOneTagsDefault = [];
export const formItemDefinitionThreeOneOneMetaTagDefault = null;
export const formItemDefinitionThreeOneOneRelevanceEnabledDefault = true;
export const formItemDefinitionThreeOneOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionThreeOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionThreeOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionThreeOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionThreeOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionThreeTwoOnePathDefault = null;
export const formItemDefinitionThreeTwoOneTagsItemKeyDefault = null;
export const formItemDefinitionThreeTwoOneTagsItemValueDefault = null;
export const formItemDefinitionThreeTwoOneTagsDefault = [];
export const formItemDefinitionThreeTwoOneMetaTagDefault = null;
export const formItemDefinitionThreeTwoOneRelevanceEnabledDefault = true;
export const formItemDefinitionThreeTwoOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionThreeTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionThreeTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionThreeTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionThreeTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionThreeTwoTwoParentIdDefault = null;
export const formItemDefinitionThreeTwoTwoConfigOneOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigOneOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigOneOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigOneOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigOneOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigOneOneAutoDataKeyDefault = true;
export const formItemDefinitionThreeTwoTwoConfigOneTwoDefaultValueLatMax = 90;

export const formItemDefinitionThreeTwoTwoConfigOneTwoDefaultValueLongMax = 180;

export const formItemDefinitionThreeTwoTwoConfigOneTwoDefaultValueDefault = null;
export const formItemDefinitionThreeTwoTwoConfigTwoOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigTwoOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigTwoOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigTwoOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigTwoOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigTwoOneAutoDataKeyDefault = true;
export const formItemDefinitionThreeTwoTwoConfigTwoTwoMinDefault = null;
export const formItemDefinitionThreeTwoTwoConfigTwoTwoMaxDefault = null;
export const formItemDefinitionThreeTwoTwoConfigTwoTwoDefaultValueDefault = null;
export const formItemDefinitionThreeTwoTwoConfigThreeOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigThreeOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigThreeOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigThreeOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigThreeOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigThreeOneAutoDataKeyDefault = true;
export const formItemDefinitionThreeTwoTwoConfigThreeTwoDefaultValueDefault = false;
export const formItemDefinitionThreeTwoTwoConfigThreeTwoRenderAsDefault = `checkbox`;
export const formItemDefinitionThreeTwoTwoConfigFourOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigFourOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigFourOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigFourOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFourOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFourOneAutoDataKeyDefault = true;
export const formItemDefinitionThreeTwoTwoConfigFourTwoPlaceholderDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFourTwoPatternDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFourTwoMinlengthDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFourTwoMaxlengthDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFourTwoDefaultValueDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFiveOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigFiveOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigFiveOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigFiveOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFiveOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFiveOneAutoDataKeyDefault = true;
export const formItemDefinitionThreeTwoTwoConfigFiveTwoItemSourceRefDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFiveTwoDefaultValueDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFiveTwoHardItemsItemLabelDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFiveTwoHardItemsItemValueDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFiveTwoHardItemsDefault = [];
export const formItemDefinitionThreeTwoTwoConfigSixOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigSixOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigSixOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigSixOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSixOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSixOneAutoDataKeyDefault = true;
export const formItemDefinitionThreeTwoTwoConfigSixTwoItemSourceRefDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSixTwoDefaultValueDefault = [];
export const formItemDefinitionThreeTwoTwoConfigSixTwoHardItemsItemLabelDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSixTwoHardItemsItemValueDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSixTwoHardItemsDefault = [];
export const formItemDefinitionThreeTwoTwoConfigSevenOneOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigSevenOneOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigSevenOneOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigSevenOneOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSevenOneOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSevenOneOneAutoDataKeyDefault = true;
export const formItemDefinitionThreeTwoTwoConfigSevenOneTwoMinDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSevenOneTwoMaxDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSevenTwoMinSelectionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSevenTwoMaxSelectionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSevenTwoDefaultValueDefault = [];
export const formItemDefinitionThreeTwoTwoConfigEightOneOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigEightOneOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigEightOneOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigEightOneOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigEightOneOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigEightOneOneAutoDataKeyDefault = true;
export const formItemDefinitionThreeTwoTwoConfigEightOneTwoMinDefault = null;
export const formItemDefinitionThreeTwoTwoConfigEightOneTwoMaxDefault = null;
export const formItemDefinitionThreeTwoTwoConfigEightTwoDefaultValueDefault = null;
export const formItemDefinitionThreeTwoTwoConfigNineOneOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigNineOneOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigNineOneOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigNineOneOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigNineOneOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigNineOneOneAutoDataKeyDefault = true;
export const formItemDefinitionThreeTwoTwoConfigNineOneTwoMinDefault = null;
export const formItemDefinitionThreeTwoTwoConfigNineOneTwoMaxDefault = null;
export const formItemDefinitionThreeTwoTwoConfigNineTwoDefaultValueDefault = { start: null, end: null };
export const formItemDefinitionFourOneOnePathDefault = null;
export const formItemDefinitionFourOneOneTagsItemKeyDefault = null;
export const formItemDefinitionFourOneOneTagsItemValueDefault = null;
export const formItemDefinitionFourOneOneTagsDefault = [];
export const formItemDefinitionFourOneOneMetaTagDefault = null;
export const formItemDefinitionFourOneOneRelevanceEnabledDefault = true;
export const formItemDefinitionFourOneOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionFourOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionFourOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionFourOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionFourOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionFourTwoOnePathDefault = null;
export const formItemDefinitionFourTwoOneTagsItemKeyDefault = null;
export const formItemDefinitionFourTwoOneTagsItemValueDefault = null;
export const formItemDefinitionFourTwoOneTagsDefault = [];
export const formItemDefinitionFourTwoOneMetaTagDefault = null;
export const formItemDefinitionFourTwoOneRelevanceEnabledDefault = true;
export const formItemDefinitionFourTwoOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionFourTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionFourTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionFourTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionFourTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionFourTwoTwoConfigWidthDefault = 10;
export const formItemDefinitionFourTwoTwoConfigWidthMin = 10;

export const formItemDefinitionFourTwoTwoConfigCaptionDefault = null;
export const formItemDefinitionFourTwoTwoConfigHeightDefault = null;
export const formItemDefinitionFourTwoTwoConfigAspectRatioDefault = null;
export const formItemDefinitionFourTwoTwoConfigFilterDefault = null;
export const formItemDefinitionFiveOneOnePathDefault = null;
export const formItemDefinitionFiveOneOneTagsItemKeyDefault = null;
export const formItemDefinitionFiveOneOneTagsItemValueDefault = null;
export const formItemDefinitionFiveOneOneTagsDefault = [];
export const formItemDefinitionFiveOneOneMetaTagDefault = null;
export const formItemDefinitionFiveOneOneRelevanceEnabledDefault = true;
export const formItemDefinitionFiveOneOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionFiveOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionFiveOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionFiveOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionFiveOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionFiveTwoOnePathDefault = null;
export const formItemDefinitionFiveTwoOneTagsItemKeyDefault = null;
export const formItemDefinitionFiveTwoOneTagsItemValueDefault = null;
export const formItemDefinitionFiveTwoOneTagsDefault = [];
export const formItemDefinitionFiveTwoOneMetaTagDefault = null;
export const formItemDefinitionFiveTwoOneRelevanceEnabledDefault = true;
export const formItemDefinitionFiveTwoOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionFiveTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionFiveTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionFiveTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionFiveTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionFiveTwoTwoConfigOrientationDefault = `vertical`;
export const FormItemDefinition = zod.union([zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionOneOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionOneOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionOneOneOneTagsItemValueDefault)
})).default(formItemDefinitionOneOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionOneOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionOneOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionOneOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionOneOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionOneOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionOneOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemDefinitionOneOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionOneTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionOneTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionOneTwoOneTagsItemValueDefault)
})).default(formItemDefinitionOneTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionOneTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionOneTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionOneTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionOneTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionOneTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionOneTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemDefinitionOneTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['group'])
}))).and(zod.object({
  "config": zod.object({
  "title": zod.string().nullable().default(formItemDefinitionOneThreeConfigOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigOneDescriptionDefault),
  "repeatable": zod.boolean().default(formItemDefinitionOneThreeConfigOneRepeatableDefault),
  "divisionCount": zod.number().min(1).default(formItemDefinitionOneThreeConfigOneDivisionCountDefault),
  "orientation": zod.enum(['horizonal', 'vertical']).default(formItemDefinitionOneThreeConfigOneOrientationDefault)
}).and(zod.object({
  "fields": zod.array(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneTagsItemValueDefault)
})).default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneTagsItemValueDefault)
})).default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['field']),
  "parentId": zod.uuid().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoParentIdDefault),
  "config": zod.union([zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['geo-point']),
  "defaultValue": zod.object({
  "lat": zod.number().max(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneTwoDefaultValueLatMax),
  "long": zod.number().max(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneTwoDefaultValueLongMax)
}).nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigOneTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['geo-point'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['integer', 'float']),
  "min": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoTwoMinDefault),
  "max": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoTwoMaxDefault),
  "defaultValue": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigTwoTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['integer', 'float'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigThreeOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigThreeOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigThreeOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigThreeOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigThreeOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigThreeOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['boolean']),
  "defaultValue": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigThreeTwoDefaultValueDefault),
  "renderAs": zod.enum(['select', 'checkbox']).nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigThreeTwoRenderAsDefault)
})).and(zod.object({
  "type": zod.enum(['boolean'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['text', 'multiline']),
  "placeholder": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourTwoPlaceholderDefault),
  "pattern": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourTwoPatternDefault),
  "minlength": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourTwoMinlengthDefault),
  "maxlength": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourTwoMaxlengthDefault),
  "defaultValue": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFourTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['text', 'multiline'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['single-select']),
  "itemSourceRef": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveTwoItemSourceRefDefault),
  "defaultValue": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveTwoDefaultValueDefault),
  "hardItems": zod.array(zod.object({
  "label": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveTwoHardItemsItemLabelDefault),
  "value": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveTwoHardItemsItemValueDefault)
})).default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigFiveTwoHardItemsDefault)
})).and(zod.object({
  "type": zod.enum(['single-select'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['multi-select']),
  "itemSourceRef": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixTwoItemSourceRefDefault),
  "defaultValue": zod.array(zod.string()).nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixTwoDefaultValueDefault),
  "hardItems": zod.array(zod.object({
  "label": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixTwoHardItemsItemLabelDefault),
  "value": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixTwoHardItemsItemValueDefault)
})).default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSixTwoHardItemsDefault)
})).and(zod.object({
  "type": zod.enum(['multi-select'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenOneOneAutoDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date']),
  "minSelection": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenTwoMinSelectionDefault),
  "maxSelection": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenTwoMaxSelectionDefault),
  "defaultValue": zod.array(zod.number()).nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigSevenTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightOneOneAutoDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time']),
  "defaultValue": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigEightTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineOneOneAutoDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date-range']),
  "defaultValue": zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
}).default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoConfigNineTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date-range'])
}))])
})).and(zod.object({
  "type": zod.enum(['field'])
}))).and(zod.object({
  "type": zod.enum(['field'])
}))).default(formItemDefinitionOneThreeConfigTwoFieldsDefault)
}))
})).and(zod.object({
  "type": zod.enum(['group'])
})),zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionTwoOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionTwoOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionTwoOneOneTagsItemValueDefault)
})).default(formItemDefinitionTwoOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionTwoOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionTwoOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionTwoOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionTwoOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionTwoOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionTwoOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemDefinitionTwoOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionTwoTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionTwoTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionTwoTwoOneTagsItemValueDefault)
})).default(formItemDefinitionTwoTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionTwoTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionTwoTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionTwoTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionTwoTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionTwoTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionTwoTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemDefinitionTwoTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['note']),
  "config": zod.object({
  "fontSize": zod.number().default(formItemDefinitionTwoTwoTwoConfigFontSizeDefault)
})
})).and(zod.object({
  "type": zod.enum(['note'])
}))).and(zod.object({
  "type": zod.enum(['note'])
})),zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionThreeOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionThreeOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionThreeOneOneTagsItemValueDefault)
})).default(formItemDefinitionThreeOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionThreeOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionThreeOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionThreeOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionThreeOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionThreeOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionThreeOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemDefinitionThreeOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionThreeTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionThreeTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionThreeTwoOneTagsItemValueDefault)
})).default(formItemDefinitionThreeTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionThreeTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionThreeTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionThreeTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionThreeTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionThreeTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionThreeTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemDefinitionThreeTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['field']),
  "parentId": zod.uuid().nullish().default(formItemDefinitionThreeTwoTwoParentIdDefault),
  "config": zod.union([zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionThreeTwoTwoConfigOneOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['geo-point']),
  "defaultValue": zod.object({
  "lat": zod.number().max(formItemDefinitionThreeTwoTwoConfigOneTwoDefaultValueLatMax),
  "long": zod.number().max(formItemDefinitionThreeTwoTwoConfigOneTwoDefaultValueLongMax)
}).nullish().default(formItemDefinitionThreeTwoTwoConfigOneTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['geo-point'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigTwoOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigTwoOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigTwoOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigTwoOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigTwoOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionThreeTwoTwoConfigTwoOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['integer', 'float']),
  "min": zod.number().nullish().default(formItemDefinitionThreeTwoTwoConfigTwoTwoMinDefault),
  "max": zod.number().nullish().default(formItemDefinitionThreeTwoTwoConfigTwoTwoMaxDefault),
  "defaultValue": zod.number().nullish().default(formItemDefinitionThreeTwoTwoConfigTwoTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['integer', 'float'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigThreeOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigThreeOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigThreeOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigThreeOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigThreeOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionThreeTwoTwoConfigThreeOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['boolean']),
  "defaultValue": zod.boolean().default(formItemDefinitionThreeTwoTwoConfigThreeTwoDefaultValueDefault),
  "renderAs": zod.enum(['select', 'checkbox']).nullable().default(formItemDefinitionThreeTwoTwoConfigThreeTwoRenderAsDefault)
})).and(zod.object({
  "type": zod.enum(['boolean'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigFourOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigFourOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigFourOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFourOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFourOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionThreeTwoTwoConfigFourOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['text', 'multiline']),
  "placeholder": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFourTwoPlaceholderDefault),
  "pattern": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFourTwoPatternDefault),
  "minlength": zod.number().nullish().default(formItemDefinitionThreeTwoTwoConfigFourTwoMinlengthDefault),
  "maxlength": zod.number().nullish().default(formItemDefinitionThreeTwoTwoConfigFourTwoMaxlengthDefault),
  "defaultValue": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFourTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['text', 'multiline'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigFiveOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigFiveOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigFiveOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFiveOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFiveOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionThreeTwoTwoConfigFiveOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['single-select']),
  "itemSourceRef": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFiveTwoItemSourceRefDefault),
  "defaultValue": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFiveTwoDefaultValueDefault),
  "hardItems": zod.array(zod.object({
  "label": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFiveTwoHardItemsItemLabelDefault),
  "value": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFiveTwoHardItemsItemValueDefault)
})).default(formItemDefinitionThreeTwoTwoConfigFiveTwoHardItemsDefault)
})).and(zod.object({
  "type": zod.enum(['single-select'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigSixOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigSixOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigSixOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigSixOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigSixOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionThreeTwoTwoConfigSixOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['multi-select']),
  "itemSourceRef": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigSixTwoItemSourceRefDefault),
  "defaultValue": zod.array(zod.string()).nullish().default(formItemDefinitionThreeTwoTwoConfigSixTwoDefaultValueDefault),
  "hardItems": zod.array(zod.object({
  "label": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigSixTwoHardItemsItemLabelDefault),
  "value": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigSixTwoHardItemsItemValueDefault)
})).default(formItemDefinitionThreeTwoTwoConfigSixTwoHardItemsDefault)
})).and(zod.object({
  "type": zod.enum(['multi-select'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigSevenOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigSevenOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigSevenOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigSevenOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigSevenOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionThreeTwoTwoConfigSevenOneOneAutoDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemDefinitionThreeTwoTwoConfigSevenOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemDefinitionThreeTwoTwoConfigSevenOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date']),
  "minSelection": zod.number().nullish().default(formItemDefinitionThreeTwoTwoConfigSevenTwoMinSelectionDefault),
  "maxSelection": zod.number().nullish().default(formItemDefinitionThreeTwoTwoConfigSevenTwoMaxSelectionDefault),
  "defaultValue": zod.array(zod.number()).nullish().default(formItemDefinitionThreeTwoTwoConfigSevenTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigEightOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigEightOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigEightOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigEightOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigEightOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionThreeTwoTwoConfigEightOneOneAutoDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemDefinitionThreeTwoTwoConfigEightOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemDefinitionThreeTwoTwoConfigEightOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time']),
  "defaultValue": zod.number().nullish().default(formItemDefinitionThreeTwoTwoConfigEightTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigNineOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigNineOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigNineOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigNineOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigNineOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemDefinitionThreeTwoTwoConfigNineOneOneAutoDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemDefinitionThreeTwoTwoConfigNineOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemDefinitionThreeTwoTwoConfigNineOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date-range']),
  "defaultValue": zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
}).default(formItemDefinitionThreeTwoTwoConfigNineTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date-range'])
}))])
})).and(zod.object({
  "type": zod.enum(['field'])
}))).and(zod.object({
  "type": zod.enum(['field'])
})),zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionFourOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionFourOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionFourOneOneTagsItemValueDefault)
})).default(formItemDefinitionFourOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionFourOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionFourOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionFourOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionFourOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionFourOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionFourOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemDefinitionFourOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionFourTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionFourTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionFourTwoOneTagsItemValueDefault)
})).default(formItemDefinitionFourTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionFourTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionFourTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionFourTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionFourTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionFourTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionFourTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemDefinitionFourTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['image']),
  "config": zod.object({
  "url": zod.string(),
  "width": zod.number().min(formItemDefinitionFourTwoTwoConfigWidthMin).default(formItemDefinitionFourTwoTwoConfigWidthDefault),
  "caption": zod.string().nullish().default(formItemDefinitionFourTwoTwoConfigCaptionDefault),
  "height": zod.number().nullish().default(formItemDefinitionFourTwoTwoConfigHeightDefault),
  "aspectRatio": zod.number().nullish().default(formItemDefinitionFourTwoTwoConfigAspectRatioDefault),
  "filter": zod.enum(['none', 'shadow']).nullish().default(formItemDefinitionFourTwoTwoConfigFilterDefault)
})
})).and(zod.object({
  "type": zod.enum(['image'])
}))).and(zod.object({
  "type": zod.enum(['image'])
})),zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionFiveOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionFiveOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionFiveOneOneTagsItemValueDefault)
})).default(formItemDefinitionFiveOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionFiveOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionFiveOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionFiveOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionFiveOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionFiveOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionFiveOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemDefinitionFiveOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionFiveTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionFiveTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionFiveTwoOneTagsItemValueDefault)
})).default(formItemDefinitionFiveTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionFiveTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionFiveTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionFiveTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionFiveTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionFiveTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionFiveTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemDefinitionFiveTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "config": zod.object({
  "orientation": zod.enum(['vertical', 'horizontal']).default(formItemDefinitionFiveTwoTwoConfigOrientationDefault)
}).optional(),
  "type": zod.enum(['separator'])
})).and(zod.object({
  "type": zod.enum(['separator'])
}))).and(zod.object({
  "type": zod.enum(['separator'])
}))])

export type FormItemDefinition = zod.input<typeof FormItemDefinition>;
