/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const FormLookup = zod.object({
  "slug": zod.string(),
  "title": zod.string(),
  "createdBy": zod.string().nullish(),
  "updatedAt": zod.iso.datetime({}),
  "currentVersion": zod.object({
  "id": zod.uuid().optional()
}).nullish()
})

export type FormLookup = zod.input<typeof FormLookup>;
