/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const formItemFieldUpdateOneOneOnePathDefault = null;
export const formItemFieldUpdateOneOneOneTagsItemKeyDefault = null;
export const formItemFieldUpdateOneOneOneTagsItemValueDefault = null;
export const formItemFieldUpdateOneOneOneTagsDefault = [];
export const formItemFieldUpdateOneOneOneMetaTagDefault = null;
export const formItemFieldUpdateOneOneOneRelevanceEnabledDefault = true;
export const formItemFieldUpdateOneOneOneRelevanceOperatorDefault = `and`;
export const formItemFieldUpdateOneOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemFieldUpdateOneOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemFieldUpdateOneOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemFieldUpdateOneOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemFieldUpdateOneOneOneRelevanceLogicDefault = [];
export const formItemFieldUpdateOneTwoOnePathDefault = null;
export const formItemFieldUpdateOneTwoOneTagsItemKeyDefault = null;
export const formItemFieldUpdateOneTwoOneTagsItemValueDefault = null;
export const formItemFieldUpdateOneTwoOneTagsDefault = [];
export const formItemFieldUpdateOneTwoOneMetaTagDefault = null;
export const formItemFieldUpdateOneTwoOneRelevanceEnabledDefault = true;
export const formItemFieldUpdateOneTwoOneRelevanceOperatorDefault = `and`;
export const formItemFieldUpdateOneTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemFieldUpdateOneTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemFieldUpdateOneTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemFieldUpdateOneTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemFieldUpdateOneTwoOneRelevanceLogicDefault = [];
export const formItemFieldUpdateOneTwoTwoParentIdDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigOneOneOneDataKeyDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigOneOneOneAutoDataKeyDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigOneOneTwoRequiredDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigOneOneTwoReadonlyDefault = false;
export const formItemFieldUpdateOneTwoTwoConfigOneOneTwoTitleDefault = ``;
export const formItemFieldUpdateOneTwoTwoConfigOneOneTwoDescriptionDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigOneTwoDefaultValueLatMax = 90;

export const formItemFieldUpdateOneTwoTwoConfigOneTwoDefaultValueLongMax = 180;

export const formItemFieldUpdateOneTwoTwoConfigOneTwoDefaultValueDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigTwoOneOneDataKeyDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigTwoOneOneAutoDataKeyDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigTwoOneTwoRequiredDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigTwoOneTwoReadonlyDefault = false;
export const formItemFieldUpdateOneTwoTwoConfigTwoOneTwoTitleDefault = ``;
export const formItemFieldUpdateOneTwoTwoConfigTwoOneTwoDescriptionDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigTwoTwoMinDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigTwoTwoMaxDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigTwoTwoDefaultValueDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigThreeOneOneDataKeyDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigThreeOneOneAutoDataKeyDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigThreeOneTwoRequiredDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigThreeOneTwoReadonlyDefault = false;
export const formItemFieldUpdateOneTwoTwoConfigThreeOneTwoTitleDefault = ``;
export const formItemFieldUpdateOneTwoTwoConfigThreeOneTwoDescriptionDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigThreeTwoDefaultValueDefault = false;
export const formItemFieldUpdateOneTwoTwoConfigThreeTwoRenderAsDefault = `checkbox`;
export const formItemFieldUpdateOneTwoTwoConfigFourOneOneDataKeyDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigFourOneOneAutoDataKeyDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigFourOneTwoRequiredDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigFourOneTwoReadonlyDefault = false;
export const formItemFieldUpdateOneTwoTwoConfigFourOneTwoTitleDefault = ``;
export const formItemFieldUpdateOneTwoTwoConfigFourOneTwoDescriptionDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigFourTwoPlaceholderDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigFourTwoPatternDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigFourTwoMinlengthDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigFourTwoMaxlengthDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigFourTwoDefaultValueDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigFiveOneOneDataKeyDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigFiveOneOneAutoDataKeyDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigFiveOneTwoRequiredDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigFiveOneTwoReadonlyDefault = false;
export const formItemFieldUpdateOneTwoTwoConfigFiveOneTwoTitleDefault = ``;
export const formItemFieldUpdateOneTwoTwoConfigFiveOneTwoDescriptionDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigFiveTwoItemSourceRefDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigFiveTwoDefaultValueDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigFiveTwoHardItemsItemLabelDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigFiveTwoHardItemsItemValueDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigFiveTwoHardItemsDefault = [];
export const formItemFieldUpdateOneTwoTwoConfigSixOneOneDataKeyDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigSixOneOneAutoDataKeyDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigSixOneTwoRequiredDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigSixOneTwoReadonlyDefault = false;
export const formItemFieldUpdateOneTwoTwoConfigSixOneTwoTitleDefault = ``;
export const formItemFieldUpdateOneTwoTwoConfigSixOneTwoDescriptionDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigSixTwoItemSourceRefDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigSixTwoDefaultValueDefault = [];
export const formItemFieldUpdateOneTwoTwoConfigSixTwoHardItemsItemLabelDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigSixTwoHardItemsItemValueDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigSixTwoHardItemsDefault = [];
export const formItemFieldUpdateOneTwoTwoConfigSevenOneOneOneDataKeyDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigSevenOneOneOneAutoDataKeyDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigSevenOneOneTwoRequiredDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigSevenOneOneTwoReadonlyDefault = false;
export const formItemFieldUpdateOneTwoTwoConfigSevenOneOneTwoTitleDefault = ``;
export const formItemFieldUpdateOneTwoTwoConfigSevenOneOneTwoDescriptionDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigSevenOneTwoMinDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigSevenOneTwoMaxDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigSevenTwoMinSelectionDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigSevenTwoMaxSelectionDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigSevenTwoDefaultValueDefault = [];
export const formItemFieldUpdateOneTwoTwoConfigEightOneOneOneDataKeyDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigEightOneOneOneAutoDataKeyDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigEightOneOneTwoRequiredDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigEightOneOneTwoReadonlyDefault = false;
export const formItemFieldUpdateOneTwoTwoConfigEightOneOneTwoTitleDefault = ``;
export const formItemFieldUpdateOneTwoTwoConfigEightOneOneTwoDescriptionDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigEightOneTwoMinDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigEightOneTwoMaxDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigEightTwoDefaultValueDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigNineOneOneOneDataKeyDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigNineOneOneOneAutoDataKeyDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigNineOneOneTwoRequiredDefault = true;
export const formItemFieldUpdateOneTwoTwoConfigNineOneOneTwoReadonlyDefault = false;
export const formItemFieldUpdateOneTwoTwoConfigNineOneOneTwoTitleDefault = ``;
export const formItemFieldUpdateOneTwoTwoConfigNineOneOneTwoDescriptionDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigNineOneTwoMinDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigNineOneTwoMaxDefault = null;
export const formItemFieldUpdateOneTwoTwoConfigNineTwoDefaultValueDefault = { start: null, end: null };
export const formItemFieldUpdateOneThreeInLibraryDefault = false;
export const FormItemFieldUpdate = zod.object({
  "itemId": zod.uuid().nullable(),
  "path": zod.string().nullable().default(formItemFieldUpdateOneOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemFieldUpdateOneOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemFieldUpdateOneOneOneTagsItemValueDefault)
})).default(formItemFieldUpdateOneOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemFieldUpdateOneOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemFieldUpdateOneOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemFieldUpdateOneOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemFieldUpdateOneOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemFieldUpdateOneOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemFieldUpdateOneOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemFieldUpdateOneOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
})).default(formItemFieldUpdateOneOneOneRelevanceLogicDefault)
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemFieldUpdateOneTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemFieldUpdateOneTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemFieldUpdateOneTwoOneTagsItemValueDefault)
})).default(formItemFieldUpdateOneTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemFieldUpdateOneTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemFieldUpdateOneTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemFieldUpdateOneTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemFieldUpdateOneTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemFieldUpdateOneTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemFieldUpdateOneTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemFieldUpdateOneTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
})).default(formItemFieldUpdateOneTwoOneRelevanceLogicDefault)
})
}).and(zod.object({
  "type": zod.enum(['field']),
  "parentId": zod.uuid().nullish().default(formItemFieldUpdateOneTwoTwoParentIdDefault),
  "config": zod.union([zod.object({
  "dataKey": zod.string().nullable().default(formItemFieldUpdateOneTwoTwoConfigOneOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemFieldUpdateOneTwoTwoConfigOneOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigOneOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigOneOneTwoReadonlyDefault),
  "title": zod.string().default(formItemFieldUpdateOneTwoTwoConfigOneOneTwoTitleDefault),
  "description": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigOneOneTwoDescriptionDefault)
})).and(zod.object({
  "type": zod.enum(['geo-point']),
  "defaultValue": zod.object({
  "lat": zod.number().max(formItemFieldUpdateOneTwoTwoConfigOneTwoDefaultValueLatMax),
  "long": zod.number().max(formItemFieldUpdateOneTwoTwoConfigOneTwoDefaultValueLongMax)
}).nullish().default(formItemFieldUpdateOneTwoTwoConfigOneTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['geo-point'])
})),zod.object({
  "dataKey": zod.string().nullable().default(formItemFieldUpdateOneTwoTwoConfigTwoOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemFieldUpdateOneTwoTwoConfigTwoOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigTwoOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigTwoOneTwoReadonlyDefault),
  "title": zod.string().default(formItemFieldUpdateOneTwoTwoConfigTwoOneTwoTitleDefault),
  "description": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigTwoOneTwoDescriptionDefault)
})).and(zod.object({
  "type": zod.enum(['integer', 'float']),
  "min": zod.number().nullish().default(formItemFieldUpdateOneTwoTwoConfigTwoTwoMinDefault),
  "max": zod.number().nullish().default(formItemFieldUpdateOneTwoTwoConfigTwoTwoMaxDefault),
  "defaultValue": zod.number().nullish().default(formItemFieldUpdateOneTwoTwoConfigTwoTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['integer', 'float'])
})),zod.object({
  "dataKey": zod.string().nullable().default(formItemFieldUpdateOneTwoTwoConfigThreeOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemFieldUpdateOneTwoTwoConfigThreeOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigThreeOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigThreeOneTwoReadonlyDefault),
  "title": zod.string().default(formItemFieldUpdateOneTwoTwoConfigThreeOneTwoTitleDefault),
  "description": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigThreeOneTwoDescriptionDefault)
})).and(zod.object({
  "type": zod.enum(['boolean']),
  "defaultValue": zod.boolean().default(formItemFieldUpdateOneTwoTwoConfigThreeTwoDefaultValueDefault),
  "renderAs": zod.enum(['select', 'checkbox']).nullable().default(formItemFieldUpdateOneTwoTwoConfigThreeTwoRenderAsDefault)
})).and(zod.object({
  "type": zod.enum(['boolean'])
})),zod.object({
  "dataKey": zod.string().nullable().default(formItemFieldUpdateOneTwoTwoConfigFourOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemFieldUpdateOneTwoTwoConfigFourOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigFourOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigFourOneTwoReadonlyDefault),
  "title": zod.string().default(formItemFieldUpdateOneTwoTwoConfigFourOneTwoTitleDefault),
  "description": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigFourOneTwoDescriptionDefault)
})).and(zod.object({
  "type": zod.enum(['text', 'multiline']),
  "placeholder": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigFourTwoPlaceholderDefault),
  "pattern": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigFourTwoPatternDefault),
  "minlength": zod.number().nullish().default(formItemFieldUpdateOneTwoTwoConfigFourTwoMinlengthDefault),
  "maxlength": zod.number().nullish().default(formItemFieldUpdateOneTwoTwoConfigFourTwoMaxlengthDefault),
  "defaultValue": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigFourTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['text', 'multiline'])
})),zod.object({
  "dataKey": zod.string().nullable().default(formItemFieldUpdateOneTwoTwoConfigFiveOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemFieldUpdateOneTwoTwoConfigFiveOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigFiveOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigFiveOneTwoReadonlyDefault),
  "title": zod.string().default(formItemFieldUpdateOneTwoTwoConfigFiveOneTwoTitleDefault),
  "description": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigFiveOneTwoDescriptionDefault)
})).and(zod.object({
  "type": zod.enum(['single-select']),
  "itemSourceRef": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigFiveTwoItemSourceRefDefault),
  "defaultValue": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigFiveTwoDefaultValueDefault),
  "hardItems": zod.array(zod.object({
  "label": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigFiveTwoHardItemsItemLabelDefault),
  "value": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigFiveTwoHardItemsItemValueDefault)
})).default(formItemFieldUpdateOneTwoTwoConfigFiveTwoHardItemsDefault)
})).and(zod.object({
  "type": zod.enum(['single-select'])
})),zod.object({
  "dataKey": zod.string().nullable().default(formItemFieldUpdateOneTwoTwoConfigSixOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemFieldUpdateOneTwoTwoConfigSixOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigSixOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigSixOneTwoReadonlyDefault),
  "title": zod.string().default(formItemFieldUpdateOneTwoTwoConfigSixOneTwoTitleDefault),
  "description": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigSixOneTwoDescriptionDefault)
})).and(zod.object({
  "type": zod.enum(['multi-select']),
  "itemSourceRef": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigSixTwoItemSourceRefDefault),
  "defaultValue": zod.array(zod.string()).nullish().default(formItemFieldUpdateOneTwoTwoConfigSixTwoDefaultValueDefault),
  "hardItems": zod.array(zod.object({
  "label": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigSixTwoHardItemsItemLabelDefault),
  "value": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigSixTwoHardItemsItemValueDefault)
})).default(formItemFieldUpdateOneTwoTwoConfigSixTwoHardItemsDefault)
})).and(zod.object({
  "type": zod.enum(['multi-select'])
})),zod.object({
  "dataKey": zod.string().nullable().default(formItemFieldUpdateOneTwoTwoConfigSevenOneOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemFieldUpdateOneTwoTwoConfigSevenOneOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigSevenOneOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigSevenOneOneTwoReadonlyDefault),
  "title": zod.string().default(formItemFieldUpdateOneTwoTwoConfigSevenOneOneTwoTitleDefault),
  "description": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigSevenOneOneTwoDescriptionDefault)
})).and(zod.object({
  "min": zod.number().nullable().default(formItemFieldUpdateOneTwoTwoConfigSevenOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemFieldUpdateOneTwoTwoConfigSevenOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date']),
  "minSelection": zod.number().nullish().default(formItemFieldUpdateOneTwoTwoConfigSevenTwoMinSelectionDefault),
  "maxSelection": zod.number().nullish().default(formItemFieldUpdateOneTwoTwoConfigSevenTwoMaxSelectionDefault),
  "defaultValue": zod.array(zod.number()).nullish().default(formItemFieldUpdateOneTwoTwoConfigSevenTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date'])
})),zod.object({
  "dataKey": zod.string().nullable().default(formItemFieldUpdateOneTwoTwoConfigEightOneOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemFieldUpdateOneTwoTwoConfigEightOneOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigEightOneOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigEightOneOneTwoReadonlyDefault),
  "title": zod.string().default(formItemFieldUpdateOneTwoTwoConfigEightOneOneTwoTitleDefault),
  "description": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigEightOneOneTwoDescriptionDefault)
})).and(zod.object({
  "min": zod.number().nullable().default(formItemFieldUpdateOneTwoTwoConfigEightOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemFieldUpdateOneTwoTwoConfigEightOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time']),
  "defaultValue": zod.number().nullish().default(formItemFieldUpdateOneTwoTwoConfigEightTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time'])
})),zod.object({
  "dataKey": zod.string().nullable().default(formItemFieldUpdateOneTwoTwoConfigNineOneOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemFieldUpdateOneTwoTwoConfigNineOneOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigNineOneOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemFieldUpdateOneTwoTwoConfigNineOneOneTwoReadonlyDefault),
  "title": zod.string().default(formItemFieldUpdateOneTwoTwoConfigNineOneOneTwoTitleDefault),
  "description": zod.string().nullish().default(formItemFieldUpdateOneTwoTwoConfigNineOneOneTwoDescriptionDefault)
})).and(zod.object({
  "min": zod.number().nullable().default(formItemFieldUpdateOneTwoTwoConfigNineOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemFieldUpdateOneTwoTwoConfigNineOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date-range']),
  "defaultValue": zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
}).default(formItemFieldUpdateOneTwoTwoConfigNineTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date-range'])
}))])
})).and(zod.object({
  "type": zod.enum(['field'])
}))).and(zod.object({
  "inLibrary": zod.boolean().default(formItemFieldUpdateOneThreeInLibraryDefault)
})).and(zod.object({
  "type": zod.enum(['field'])
})).and(zod.object({
  "type": zod.enum(['field'])
}))

export type FormItemFieldUpdate = zod.input<typeof FormItemFieldUpdate>;
export type FormItemFieldUpdateOutput = zod.output<typeof FormItemFieldUpdate>;
