/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const formItemSeparatorOneOnePathDefault = null;
export const formItemSeparatorOneOneTagsItemKeyDefault = null;
export const formItemSeparatorOneOneTagsItemValueDefault = null;
export const formItemSeparatorOneOneTagsDefault = [];
export const formItemSeparatorOneOneMetaTagDefault = null;
export const formItemSeparatorOneOneRelevanceEnabledDefault = true;
export const formItemSeparatorOneOneRelevanceOperatorDefault = `and`;
export const formItemSeparatorOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemSeparatorOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemSeparatorOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemSeparatorOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemSeparatorTwoOnePathDefault = null;
export const formItemSeparatorTwoOneTagsItemKeyDefault = null;
export const formItemSeparatorTwoOneTagsItemValueDefault = null;
export const formItemSeparatorTwoOneTagsDefault = [];
export const formItemSeparatorTwoOneMetaTagDefault = null;
export const formItemSeparatorTwoOneRelevanceEnabledDefault = true;
export const formItemSeparatorTwoOneRelevanceOperatorDefault = `and`;
export const formItemSeparatorTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemSeparatorTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemSeparatorTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemSeparatorTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemSeparatorTwoTwoConfigOrientationDefault = `vertical`;
export const FormItemSeparator = zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemSeparatorOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemSeparatorOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemSeparatorOneOneTagsItemValueDefault)
})).default(formItemSeparatorOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemSeparatorOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemSeparatorOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemSeparatorOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemSeparatorOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemSeparatorOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemSeparatorOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemSeparatorOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemSeparatorTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemSeparatorTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemSeparatorTwoOneTagsItemValueDefault)
})).default(formItemSeparatorTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemSeparatorTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemSeparatorTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemSeparatorTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemSeparatorTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemSeparatorTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemSeparatorTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemSeparatorTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "config": zod.object({
  "orientation": zod.enum(['vertical', 'horizontal']).default(formItemSeparatorTwoTwoConfigOrientationDefault)
}).optional(),
  "type": zod.enum(['separator'])
})).and(zod.object({
  "type": zod.enum(['separator'])
}))).and(zod.object({
  "type": zod.enum(['separator'])
}))

export type FormItemSeparator = zod.input<typeof FormItemSeparator>;
