/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const formItemImageOneOnePathDefault = null;
export const formItemImageOneOneTagsItemKeyDefault = null;
export const formItemImageOneOneTagsItemValueDefault = null;
export const formItemImageOneOneTagsDefault = [];
export const formItemImageOneOneMetaTagDefault = null;
export const formItemImageOneOneRelevanceEnabledDefault = true;
export const formItemImageOneOneRelevanceOperatorDefault = `and`;
export const formItemImageOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemImageOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemImageOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemImageOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemImageTwoOnePathDefault = null;
export const formItemImageTwoOneTagsItemKeyDefault = null;
export const formItemImageTwoOneTagsItemValueDefault = null;
export const formItemImageTwoOneTagsDefault = [];
export const formItemImageTwoOneMetaTagDefault = null;
export const formItemImageTwoOneRelevanceEnabledDefault = true;
export const formItemImageTwoOneRelevanceOperatorDefault = `and`;
export const formItemImageTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemImageTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemImageTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemImageTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemImageTwoTwoConfigWidthDefault = 10;
export const formItemImageTwoTwoConfigWidthMin = 10;

export const formItemImageTwoTwoConfigCaptionDefault = null;
export const formItemImageTwoTwoConfigHeightDefault = null;
export const formItemImageTwoTwoConfigAspectRatioDefault = null;
export const formItemImageTwoTwoConfigFilterDefault = null;
export const FormItemImage = zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemImageOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemImageOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemImageOneOneTagsItemValueDefault)
})).default(formItemImageOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemImageOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemImageOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemImageOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemImageOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemImageOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemImageOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(formItemImageOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemImageTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemImageTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemImageTwoOneTagsItemValueDefault)
})).default(formItemImageTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemImageTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemImageTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemImageTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemImageTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemImageTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemImageTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(formItemImageTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['image']),
  "config": zod.object({
  "url": zod.string(),
  "width": zod.number().min(formItemImageTwoTwoConfigWidthMin).default(formItemImageTwoTwoConfigWidthDefault),
  "caption": zod.string().nullish().default(formItemImageTwoTwoConfigCaptionDefault),
  "height": zod.number().nullish().default(formItemImageTwoTwoConfigHeightDefault),
  "aspectRatio": zod.number().nullish().default(formItemImageTwoTwoConfigAspectRatioDefault),
  "filter": zod.enum(['none', 'shadow']).nullish().default(formItemImageTwoTwoConfigFilterDefault)
})
})).and(zod.object({
  "type": zod.enum(['image'])
}))).and(zod.object({
  "type": zod.enum(['image'])
}))

export type FormItemImage = zod.input<typeof FormItemImage>;
