/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const formItemDefinitionOneOneOnePathDefault = null;
export const formItemDefinitionOneOneOneTagsItemKeyDefault = null;
export const formItemDefinitionOneOneOneTagsItemValueDefault = null;
export const formItemDefinitionOneOneOneTagsDefault = [];
export const formItemDefinitionOneOneOneMetaTagDefault = null;
export const formItemDefinitionOneOneOneRelevanceEnabledDefault = true;
export const formItemDefinitionOneOneOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionOneOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionOneOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionOneOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionOneOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionOneTwoOnePathDefault = null;
export const formItemDefinitionOneTwoOneTagsItemKeyDefault = null;
export const formItemDefinitionOneTwoOneTagsItemValueDefault = null;
export const formItemDefinitionOneTwoOneTagsDefault = [];
export const formItemDefinitionOneTwoOneMetaTagDefault = null;
export const formItemDefinitionOneTwoOneRelevanceEnabledDefault = true;
export const formItemDefinitionOneTwoOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionOneTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionOneTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionOneTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionOneTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionOneThreeConfigOneTitleDefault = null;
export const formItemDefinitionOneThreeConfigOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigOneRepeatableDefault = true;
export const formItemDefinitionOneThreeConfigOneDivisionCountDefault = 1;

export const formItemDefinitionOneThreeConfigOneOrientationDefault = `vertical`;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOnePathDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneTagsItemKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneTagsItemValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneTagsDefault = [];
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneMetaTagDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceEnabledDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigOneOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigOneOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigOneOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigOneOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigOneOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigOneTwoDefaultValueLatMax = 90;

export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigOneTwoDefaultValueLongMax = 180;

export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigOneTwoDefaultValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigTwoOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigTwoOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigTwoOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigTwoOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigTwoOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigTwoTwoMinDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigTwoTwoMaxDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigTwoTwoDefaultValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigThreeOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigThreeOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigThreeOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigThreeOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigThreeOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigThreeTwoDefaultValueDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigThreeTwoRenderAsDefault = `checkbox`;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourTwoPatternDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourTwoMinlengthDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourTwoMaxlengthDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourTwoDefaultValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveTwoItemSourceRefDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveTwoDefaultValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveTwoHardItemsItemLabelDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveTwoHardItemsItemValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveTwoHardItemsDefault = [];
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixOneOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixOneOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixOneOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixOneOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixOneOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixOneTwoMinDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixOneTwoMaxDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixTwoMinSelectionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixTwoMaxSelectionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixTwoDefaultValueDefault = [];
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSevenOneOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSevenOneOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSevenOneOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSevenOneOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSevenOneOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSevenOneTwoMinDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSevenOneTwoMaxDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSevenTwoDefaultValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigEightOneOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigEightOneOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigEightOneOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigEightOneOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigEightOneOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigEightOneTwoMinDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigEightOneTwoMaxDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigEightTwoDefaultValueDefault = { start: null, end: null };
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOnePathDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneTagsItemKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneTagsItemValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneTagsDefault = [];
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneMetaTagDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneRelevanceEnabledDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOnePathDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneTagsItemKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneTagsItemValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneTagsDefault = [];
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneMetaTagDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneRelevanceEnabledDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigOneOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigOneOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigOneOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigOneOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigOneOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigOneTwoDefaultValueLatMax = 90;

export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigOneTwoDefaultValueLongMax = 180;

export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigOneTwoDefaultValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigTwoOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigTwoOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigTwoOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigTwoOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigTwoOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigTwoTwoMinDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigTwoTwoMaxDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigTwoTwoDefaultValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigThreeOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigThreeOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigThreeOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigThreeOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigThreeOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigThreeTwoDefaultValueDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigThreeTwoRenderAsDefault = `checkbox`;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourTwoPatternDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourTwoMinlengthDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourTwoMaxlengthDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourTwoDefaultValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveTwoItemSourceRefDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveTwoDefaultValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveTwoHardItemsItemLabelDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveTwoHardItemsItemValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveTwoHardItemsDefault = [];
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixOneOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixOneOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixOneOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixOneOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixOneOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixOneTwoMinDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixOneTwoMaxDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixTwoMinSelectionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixTwoMaxSelectionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixTwoDefaultValueDefault = [];
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSevenOneOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSevenOneOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSevenOneOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSevenOneOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSevenOneOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSevenOneTwoMinDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSevenOneTwoMaxDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSevenTwoDefaultValueDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigEightOneOneRequiredDefault = true;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigEightOneOneReadonlyDefault = false;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigEightOneOneTitleDefault = ``;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigEightOneOneDescriptionDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigEightOneOneDataKeyDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigEightOneTwoMinDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigEightOneTwoMaxDefault = null;
export const formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigEightTwoDefaultValueDefault = { start: null, end: null };
export const formItemDefinitionOneThreeConfigTwoFieldsDefault = [];
export const formItemDefinitionTwoOneOnePathDefault = null;
export const formItemDefinitionTwoOneOneTagsItemKeyDefault = null;
export const formItemDefinitionTwoOneOneTagsItemValueDefault = null;
export const formItemDefinitionTwoOneOneTagsDefault = [];
export const formItemDefinitionTwoOneOneMetaTagDefault = null;
export const formItemDefinitionTwoOneOneRelevanceEnabledDefault = true;
export const formItemDefinitionTwoOneOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionTwoOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionTwoOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionTwoOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionTwoOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionTwoTwoOnePathDefault = null;
export const formItemDefinitionTwoTwoOneTagsItemKeyDefault = null;
export const formItemDefinitionTwoTwoOneTagsItemValueDefault = null;
export const formItemDefinitionTwoTwoOneTagsDefault = [];
export const formItemDefinitionTwoTwoOneMetaTagDefault = null;
export const formItemDefinitionTwoTwoOneRelevanceEnabledDefault = true;
export const formItemDefinitionTwoTwoOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionTwoTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionTwoTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionTwoTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionTwoTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionTwoTwoTwoConfigFontSizeDefault = 13;
export const formItemDefinitionThreeOneOnePathDefault = null;
export const formItemDefinitionThreeOneOneTagsItemKeyDefault = null;
export const formItemDefinitionThreeOneOneTagsItemValueDefault = null;
export const formItemDefinitionThreeOneOneTagsDefault = [];
export const formItemDefinitionThreeOneOneMetaTagDefault = null;
export const formItemDefinitionThreeOneOneRelevanceEnabledDefault = true;
export const formItemDefinitionThreeOneOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionThreeOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionThreeOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionThreeOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionThreeOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionThreeTwoOnePathDefault = null;
export const formItemDefinitionThreeTwoOneTagsItemKeyDefault = null;
export const formItemDefinitionThreeTwoOneTagsItemValueDefault = null;
export const formItemDefinitionThreeTwoOneTagsDefault = [];
export const formItemDefinitionThreeTwoOneMetaTagDefault = null;
export const formItemDefinitionThreeTwoOneRelevanceEnabledDefault = true;
export const formItemDefinitionThreeTwoOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionThreeTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionThreeTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionThreeTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionThreeTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionThreeTwoTwoConfigOneOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigOneOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigOneOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigOneOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigOneOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigOneTwoDefaultValueLatMax = 90;

export const formItemDefinitionThreeTwoTwoConfigOneTwoDefaultValueLongMax = 180;

export const formItemDefinitionThreeTwoTwoConfigOneTwoDefaultValueDefault = null;
export const formItemDefinitionThreeTwoTwoConfigTwoOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigTwoOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigTwoOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigTwoOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigTwoOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigTwoTwoMinDefault = null;
export const formItemDefinitionThreeTwoTwoConfigTwoTwoMaxDefault = null;
export const formItemDefinitionThreeTwoTwoConfigTwoTwoDefaultValueDefault = null;
export const formItemDefinitionThreeTwoTwoConfigThreeOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigThreeOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigThreeOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigThreeOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigThreeOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigThreeTwoDefaultValueDefault = false;
export const formItemDefinitionThreeTwoTwoConfigThreeTwoRenderAsDefault = `checkbox`;
export const formItemDefinitionThreeTwoTwoConfigFourOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigFourOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigFourOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigFourOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFourOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFourTwoPatternDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFourTwoMinlengthDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFourTwoMaxlengthDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFourTwoDefaultValueDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFiveOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigFiveOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigFiveOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigFiveOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFiveOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFiveTwoItemSourceRefDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFiveTwoDefaultValueDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFiveTwoHardItemsItemLabelDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFiveTwoHardItemsItemValueDefault = null;
export const formItemDefinitionThreeTwoTwoConfigFiveTwoHardItemsDefault = [];
export const formItemDefinitionThreeTwoTwoConfigSixOneOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigSixOneOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigSixOneOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigSixOneOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSixOneOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSixOneTwoMinDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSixOneTwoMaxDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSixTwoMinSelectionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSixTwoMaxSelectionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSixTwoDefaultValueDefault = [];
export const formItemDefinitionThreeTwoTwoConfigSevenOneOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigSevenOneOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigSevenOneOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigSevenOneOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSevenOneOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSevenOneTwoMinDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSevenOneTwoMaxDefault = null;
export const formItemDefinitionThreeTwoTwoConfigSevenTwoDefaultValueDefault = null;
export const formItemDefinitionThreeTwoTwoConfigEightOneOneRequiredDefault = true;
export const formItemDefinitionThreeTwoTwoConfigEightOneOneReadonlyDefault = false;
export const formItemDefinitionThreeTwoTwoConfigEightOneOneTitleDefault = ``;
export const formItemDefinitionThreeTwoTwoConfigEightOneOneDescriptionDefault = null;
export const formItemDefinitionThreeTwoTwoConfigEightOneOneDataKeyDefault = null;
export const formItemDefinitionThreeTwoTwoConfigEightOneTwoMinDefault = null;
export const formItemDefinitionThreeTwoTwoConfigEightOneTwoMaxDefault = null;
export const formItemDefinitionThreeTwoTwoConfigEightTwoDefaultValueDefault = { start: null, end: null };
export const formItemDefinitionFourOneOnePathDefault = null;
export const formItemDefinitionFourOneOneTagsItemKeyDefault = null;
export const formItemDefinitionFourOneOneTagsItemValueDefault = null;
export const formItemDefinitionFourOneOneTagsDefault = [];
export const formItemDefinitionFourOneOneMetaTagDefault = null;
export const formItemDefinitionFourOneOneRelevanceEnabledDefault = true;
export const formItemDefinitionFourOneOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionFourOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionFourOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionFourOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionFourOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionFourTwoOnePathDefault = null;
export const formItemDefinitionFourTwoOneTagsItemKeyDefault = null;
export const formItemDefinitionFourTwoOneTagsItemValueDefault = null;
export const formItemDefinitionFourTwoOneTagsDefault = [];
export const formItemDefinitionFourTwoOneMetaTagDefault = null;
export const formItemDefinitionFourTwoOneRelevanceEnabledDefault = true;
export const formItemDefinitionFourTwoOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionFourTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionFourTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionFourTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionFourTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionFourTwoTwoConfigWidthDefault = 10;
export const formItemDefinitionFourTwoTwoConfigWidthMin = 10;

export const formItemDefinitionFourTwoTwoConfigCaptionDefault = null;
export const formItemDefinitionFourTwoTwoConfigHeightDefault = null;
export const formItemDefinitionFourTwoTwoConfigAspectRatioDefault = null;
export const formItemDefinitionFourTwoTwoConfigFilterDefault = null;
export const formItemDefinitionFiveOneOnePathDefault = null;
export const formItemDefinitionFiveOneOneTagsItemKeyDefault = null;
export const formItemDefinitionFiveOneOneTagsItemValueDefault = null;
export const formItemDefinitionFiveOneOneTagsDefault = [];
export const formItemDefinitionFiveOneOneMetaTagDefault = null;
export const formItemDefinitionFiveOneOneRelevanceEnabledDefault = true;
export const formItemDefinitionFiveOneOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionFiveOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionFiveOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionFiveOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionFiveOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionFiveTwoOnePathDefault = null;
export const formItemDefinitionFiveTwoOneTagsItemKeyDefault = null;
export const formItemDefinitionFiveTwoOneTagsItemValueDefault = null;
export const formItemDefinitionFiveTwoOneTagsDefault = [];
export const formItemDefinitionFiveTwoOneMetaTagDefault = null;
export const formItemDefinitionFiveTwoOneRelevanceEnabledDefault = true;
export const formItemDefinitionFiveTwoOneRelevanceOperatorDefault = `and`;
export const formItemDefinitionFiveTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemDefinitionFiveTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemDefinitionFiveTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemDefinitionFiveTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemDefinitionFiveTwoTwoConfigOrientationDefault = `vertical`;
export const FormItemDefinition = zod.union([zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionOneOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionOneOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionOneOneOneTagsItemValueDefault)
})).default(formItemDefinitionOneOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionOneOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionOneOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionOneOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionOneOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionOneOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionOneOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(formItemDefinitionOneOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionOneTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionOneTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionOneTwoOneTagsItemValueDefault)
})).default(formItemDefinitionOneTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionOneTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionOneTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionOneTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionOneTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionOneTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionOneTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(formItemDefinitionOneTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['group'])
}))).and(zod.object({
  "config": zod.object({
  "title": zod.string().nullable().default(formItemDefinitionOneThreeConfigOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigOneDescriptionDefault),
  "repeatable": zod.boolean().default(formItemDefinitionOneThreeConfigOneRepeatableDefault),
  "divisionCount": zod.number().min(1).default(formItemDefinitionOneThreeConfigOneDivisionCountDefault),
  "orientation": zod.enum(['horizonal', 'vertical']).default(formItemDefinitionOneThreeConfigOneOrientationDefault)
}).and(zod.object({
  "fields": zod.array(zod.union([zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneTagsItemValueDefault)
})).default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['field']),
  "config": zod.union([zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigOneOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['geo-point']),
  "defaultValue": zod.object({
  "lat": zod.number().max(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigOneTwoDefaultValueLatMax),
  "long": zod.number().max(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigOneTwoDefaultValueLongMax)
}).nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigOneTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['geo-point'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigTwoOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigTwoOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigTwoOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigTwoOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigTwoOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['integer', 'float']),
  "min": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigTwoTwoMinDefault),
  "max": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigTwoTwoMaxDefault),
  "defaultValue": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigTwoTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['integer', 'float'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigThreeOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigThreeOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigThreeOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigThreeOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigThreeOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['boolean']),
  "defaultValue": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigThreeTwoDefaultValueDefault),
  "renderAs": zod.enum(['select', 'checkbox']).nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigThreeTwoRenderAsDefault)
})).and(zod.object({
  "type": zod.enum(['boolean'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['text', 'multiline']),
  "pattern": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourTwoPatternDefault),
  "minlength": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourTwoMinlengthDefault),
  "maxlength": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourTwoMaxlengthDefault),
  "defaultValue": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFourTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['text', 'multiline'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['single-select', 'multi-select']),
  "itemSourceRef": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveTwoItemSourceRefDefault),
  "defaultValue": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveTwoDefaultValueDefault),
  "hardItems": zod.array(zod.object({
  "label": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveTwoHardItemsItemLabelDefault),
  "value": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveTwoHardItemsItemValueDefault)
})).default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigFiveTwoHardItemsDefault)
})).and(zod.object({
  "type": zod.enum(['single-select', 'multi-select'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixOneOneDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date']),
  "minSelection": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixTwoMinSelectionDefault),
  "maxSelection": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixTwoMaxSelectionDefault),
  "defaultValue": zod.array(zod.number()).nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSixTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSevenOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSevenOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSevenOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSevenOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSevenOneOneDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSevenOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSevenOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time']),
  "defaultValue": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigSevenTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigEightOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigEightOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigEightOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigEightOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigEightOneOneDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigEightOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigEightOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date-range']),
  "defaultValue": zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
}).default(formItemDefinitionOneThreeConfigTwoFieldsItemOneTwoConfigEightTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date-range'])
}))])
})).and(zod.object({
  "type": zod.enum(['field'])
})),zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneTagsItemValueDefault)
})).default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneTagsItemValueDefault)
})).default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['field']),
  "config": zod.union([zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigOneOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['geo-point']),
  "defaultValue": zod.object({
  "lat": zod.number().max(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigOneTwoDefaultValueLatMax),
  "long": zod.number().max(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigOneTwoDefaultValueLongMax)
}).nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigOneTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['geo-point'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigTwoOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigTwoOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigTwoOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigTwoOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigTwoOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['integer', 'float']),
  "min": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigTwoTwoMinDefault),
  "max": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigTwoTwoMaxDefault),
  "defaultValue": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigTwoTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['integer', 'float'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigThreeOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigThreeOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigThreeOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigThreeOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigThreeOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['boolean']),
  "defaultValue": zod.boolean().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigThreeTwoDefaultValueDefault),
  "renderAs": zod.enum(['select', 'checkbox']).nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigThreeTwoRenderAsDefault)
})).and(zod.object({
  "type": zod.enum(['boolean'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['text', 'multiline']),
  "pattern": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourTwoPatternDefault),
  "minlength": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourTwoMinlengthDefault),
  "maxlength": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourTwoMaxlengthDefault),
  "defaultValue": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFourTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['text', 'multiline'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['single-select', 'multi-select']),
  "itemSourceRef": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveTwoItemSourceRefDefault),
  "defaultValue": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveTwoDefaultValueDefault),
  "hardItems": zod.array(zod.object({
  "label": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveTwoHardItemsItemLabelDefault),
  "value": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveTwoHardItemsItemValueDefault)
})).default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigFiveTwoHardItemsDefault)
})).and(zod.object({
  "type": zod.enum(['single-select', 'multi-select'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixOneOneDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date']),
  "minSelection": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixTwoMinSelectionDefault),
  "maxSelection": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixTwoMaxSelectionDefault),
  "defaultValue": zod.array(zod.number()).nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSixTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSevenOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSevenOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSevenOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSevenOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSevenOneOneDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSevenOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSevenOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time']),
  "defaultValue": zod.number().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigSevenTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigEightOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigEightOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigEightOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigEightOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigEightOneOneDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigEightOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigEightOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date-range']),
  "defaultValue": zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
}).default(formItemDefinitionOneThreeConfigTwoFieldsItemTwoTwoTwoConfigEightTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date-range'])
}))])
})).and(zod.object({
  "type": zod.enum(['field'])
}))).and(zod.object({
  "type": zod.enum(['field'])
}))])).default(formItemDefinitionOneThreeConfigTwoFieldsDefault)
}))
})).and(zod.object({
  "type": zod.enum(['group'])
})),zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionTwoOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionTwoOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionTwoOneOneTagsItemValueDefault)
})).default(formItemDefinitionTwoOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionTwoOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionTwoOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionTwoOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionTwoOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionTwoOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionTwoOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(formItemDefinitionTwoOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionTwoTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionTwoTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionTwoTwoOneTagsItemValueDefault)
})).default(formItemDefinitionTwoTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionTwoTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionTwoTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionTwoTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionTwoTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionTwoTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionTwoTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(formItemDefinitionTwoTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['note']),
  "config": zod.object({
  "fontSize": zod.number().default(formItemDefinitionTwoTwoTwoConfigFontSizeDefault)
})
})).and(zod.object({
  "type": zod.enum(['note'])
}))).and(zod.object({
  "type": zod.enum(['note'])
})),zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionThreeOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionThreeOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionThreeOneOneTagsItemValueDefault)
})).default(formItemDefinitionThreeOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionThreeOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionThreeOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionThreeOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionThreeOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionThreeOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionThreeOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(formItemDefinitionThreeOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionThreeTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionThreeTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionThreeTwoOneTagsItemValueDefault)
})).default(formItemDefinitionThreeTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionThreeTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionThreeTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionThreeTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionThreeTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionThreeTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionThreeTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(formItemDefinitionThreeTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['field']),
  "config": zod.union([zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigOneOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['geo-point']),
  "defaultValue": zod.object({
  "lat": zod.number().max(formItemDefinitionThreeTwoTwoConfigOneTwoDefaultValueLatMax),
  "long": zod.number().max(formItemDefinitionThreeTwoTwoConfigOneTwoDefaultValueLongMax)
}).nullish().default(formItemDefinitionThreeTwoTwoConfigOneTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['geo-point'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigTwoOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigTwoOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigTwoOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigTwoOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigTwoOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['integer', 'float']),
  "min": zod.number().nullish().default(formItemDefinitionThreeTwoTwoConfigTwoTwoMinDefault),
  "max": zod.number().nullish().default(formItemDefinitionThreeTwoTwoConfigTwoTwoMaxDefault),
  "defaultValue": zod.number().nullish().default(formItemDefinitionThreeTwoTwoConfigTwoTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['integer', 'float'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigThreeOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigThreeOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigThreeOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigThreeOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigThreeOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['boolean']),
  "defaultValue": zod.boolean().default(formItemDefinitionThreeTwoTwoConfigThreeTwoDefaultValueDefault),
  "renderAs": zod.enum(['select', 'checkbox']).nullable().default(formItemDefinitionThreeTwoTwoConfigThreeTwoRenderAsDefault)
})).and(zod.object({
  "type": zod.enum(['boolean'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigFourOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigFourOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigFourOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFourOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFourOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['text', 'multiline']),
  "pattern": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFourTwoPatternDefault),
  "minlength": zod.number().nullish().default(formItemDefinitionThreeTwoTwoConfigFourTwoMinlengthDefault),
  "maxlength": zod.number().nullish().default(formItemDefinitionThreeTwoTwoConfigFourTwoMaxlengthDefault),
  "defaultValue": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFourTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['text', 'multiline'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigFiveOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigFiveOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigFiveOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFiveOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFiveOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['single-select', 'multi-select']),
  "itemSourceRef": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFiveTwoItemSourceRefDefault),
  "defaultValue": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFiveTwoDefaultValueDefault),
  "hardItems": zod.array(zod.object({
  "label": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFiveTwoHardItemsItemLabelDefault),
  "value": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigFiveTwoHardItemsItemValueDefault)
})).default(formItemDefinitionThreeTwoTwoConfigFiveTwoHardItemsDefault)
})).and(zod.object({
  "type": zod.enum(['single-select', 'multi-select'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigSixOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigSixOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigSixOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigSixOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigSixOneOneDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemDefinitionThreeTwoTwoConfigSixOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemDefinitionThreeTwoTwoConfigSixOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date']),
  "minSelection": zod.number().nullish().default(formItemDefinitionThreeTwoTwoConfigSixTwoMinSelectionDefault),
  "maxSelection": zod.number().nullish().default(formItemDefinitionThreeTwoTwoConfigSixTwoMaxSelectionDefault),
  "defaultValue": zod.array(zod.number()).nullish().default(formItemDefinitionThreeTwoTwoConfigSixTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigSevenOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigSevenOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigSevenOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigSevenOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigSevenOneOneDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemDefinitionThreeTwoTwoConfigSevenOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemDefinitionThreeTwoTwoConfigSevenOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time']),
  "defaultValue": zod.number().nullish().default(formItemDefinitionThreeTwoTwoConfigSevenTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigEightOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemDefinitionThreeTwoTwoConfigEightOneOneReadonlyDefault),
  "title": zod.string().default(formItemDefinitionThreeTwoTwoConfigEightOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigEightOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemDefinitionThreeTwoTwoConfigEightOneOneDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemDefinitionThreeTwoTwoConfigEightOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemDefinitionThreeTwoTwoConfigEightOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date-range']),
  "defaultValue": zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
}).default(formItemDefinitionThreeTwoTwoConfigEightTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date-range'])
}))])
})).and(zod.object({
  "type": zod.enum(['field'])
}))).and(zod.object({
  "type": zod.enum(['field'])
})),zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionFourOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionFourOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionFourOneOneTagsItemValueDefault)
})).default(formItemDefinitionFourOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionFourOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionFourOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionFourOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionFourOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionFourOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionFourOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(formItemDefinitionFourOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionFourTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionFourTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionFourTwoOneTagsItemValueDefault)
})).default(formItemDefinitionFourTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionFourTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionFourTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionFourTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionFourTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionFourTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionFourTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(formItemDefinitionFourTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['image']),
  "config": zod.object({
  "url": zod.string(),
  "width": zod.number().min(formItemDefinitionFourTwoTwoConfigWidthMin).default(formItemDefinitionFourTwoTwoConfigWidthDefault),
  "caption": zod.string().nullish().default(formItemDefinitionFourTwoTwoConfigCaptionDefault),
  "height": zod.number().nullish().default(formItemDefinitionFourTwoTwoConfigHeightDefault),
  "aspectRatio": zod.number().nullish().default(formItemDefinitionFourTwoTwoConfigAspectRatioDefault),
  "filter": zod.enum(['none', 'shadow']).nullish().default(formItemDefinitionFourTwoTwoConfigFilterDefault)
})
})).and(zod.object({
  "type": zod.enum(['image'])
}))).and(zod.object({
  "type": zod.enum(['image'])
})),zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionFiveOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionFiveOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionFiveOneOneTagsItemValueDefault)
})).default(formItemDefinitionFiveOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionFiveOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionFiveOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionFiveOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionFiveOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionFiveOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionFiveOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(formItemDefinitionFiveOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemDefinitionFiveTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemDefinitionFiveTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemDefinitionFiveTwoOneTagsItemValueDefault)
})).default(formItemDefinitionFiveTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemDefinitionFiveTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemDefinitionFiveTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemDefinitionFiveTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemDefinitionFiveTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemDefinitionFiveTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemDefinitionFiveTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(formItemDefinitionFiveTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "config": zod.object({
  "orientation": zod.enum(['vertical', 'horizontal']).default(formItemDefinitionFiveTwoTwoConfigOrientationDefault)
}).optional(),
  "type": zod.enum(['separator'])
})).and(zod.object({
  "type": zod.enum(['separator'])
}))).and(zod.object({
  "type": zod.enum(['separator'])
}))])

export type FormItemDefinition = zod.input<typeof FormItemDefinition>;
