/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const formItemGroupOneOnePathDefault = null;
export const formItemGroupOneOneTagsItemKeyDefault = null;
export const formItemGroupOneOneTagsItemValueDefault = null;
export const formItemGroupOneOneTagsDefault = [];
export const formItemGroupOneOneMetaTagDefault = null;
export const formItemGroupOneOneRelevanceEnabledDefault = true;
export const formItemGroupOneOneRelevanceOperatorDefault = `and`;
export const formItemGroupOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemGroupOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemGroupOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemGroupOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemGroupTwoOnePathDefault = null;
export const formItemGroupTwoOneTagsItemKeyDefault = null;
export const formItemGroupTwoOneTagsItemValueDefault = null;
export const formItemGroupTwoOneTagsDefault = [];
export const formItemGroupTwoOneMetaTagDefault = null;
export const formItemGroupTwoOneRelevanceEnabledDefault = true;
export const formItemGroupTwoOneRelevanceOperatorDefault = `and`;
export const formItemGroupTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemGroupTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemGroupTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemGroupTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemGroupThreeInLibraryDefault = false;
export const formItemGroupFourConfigOneTitleDefault = null;
export const formItemGroupFourConfigOneDescriptionDefault = null;
export const formItemGroupFourConfigOneRepeatableDefault = false;
export const formItemGroupFourConfigOneDivisionCountDefault = 1;

export const formItemGroupFourConfigOneOrientationDefault = `vertical`;
export const formItemGroupFourConfigTwoFieldsItemOneOnePathDefault = null;
export const formItemGroupFourConfigTwoFieldsItemOneOneTagsItemKeyDefault = null;
export const formItemGroupFourConfigTwoFieldsItemOneOneTagsItemValueDefault = null;
export const formItemGroupFourConfigTwoFieldsItemOneOneTagsDefault = [];
export const formItemGroupFourConfigTwoFieldsItemOneOneMetaTagDefault = null;
export const formItemGroupFourConfigTwoFieldsItemOneOneRelevanceEnabledDefault = true;
export const formItemGroupFourConfigTwoFieldsItemOneOneRelevanceOperatorDefault = `and`;
export const formItemGroupFourConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemGroupFourConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemGroupFourConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemGroupFourConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoOnePathDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoOneTagsItemKeyDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoOneTagsItemValueDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoOneTagsDefault = [];
export const formItemGroupFourConfigTwoFieldsItemTwoOneMetaTagDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoOneRelevanceEnabledDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoOneRelevanceOperatorDefault = `and`;
export const formItemGroupFourConfigTwoFieldsItemTwoOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const formItemGroupFourConfigTwoFieldsItemTwoOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoParentIdDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneOneRequiredDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneOneReadonlyDefault = false;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneOneTitleDefault = ``;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneOneDescriptionDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneOneDataKeyDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneOneAutoDataKeyDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneTwoDefaultValueLatMax = 90;

export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneTwoDefaultValueLongMax = 180;

export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneTwoDefaultValueDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoOneRequiredDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoOneReadonlyDefault = false;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoOneTitleDefault = ``;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoOneDescriptionDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoOneDataKeyDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoOneAutoDataKeyDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoTwoMinDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoTwoMaxDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoTwoDefaultValueDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigThreeOneRequiredDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigThreeOneReadonlyDefault = false;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigThreeOneTitleDefault = ``;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigThreeOneDescriptionDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigThreeOneDataKeyDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigThreeOneAutoDataKeyDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigThreeTwoDefaultValueDefault = false;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigThreeTwoRenderAsDefault = `checkbox`;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourOneRequiredDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourOneReadonlyDefault = false;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourOneTitleDefault = ``;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourOneDescriptionDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourOneDataKeyDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourOneAutoDataKeyDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourTwoPlaceholderDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourTwoPatternDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourTwoMinlengthDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourTwoMaxlengthDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourTwoDefaultValueDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveOneRequiredDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveOneReadonlyDefault = false;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveOneTitleDefault = ``;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveOneDescriptionDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveOneDataKeyDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveOneAutoDataKeyDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveTwoItemSourceRefDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveTwoDefaultValueDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveTwoHardItemsItemLabelDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveTwoHardItemsItemValueDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveTwoHardItemsDefault = [];
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixOneRequiredDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixOneReadonlyDefault = false;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixOneTitleDefault = ``;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixOneDescriptionDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixOneDataKeyDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixOneAutoDataKeyDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixTwoItemSourceRefDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixTwoDefaultValueDefault = [];
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixTwoHardItemsItemLabelDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixTwoHardItemsItemValueDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixTwoHardItemsDefault = [];
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenOneOneRequiredDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenOneOneReadonlyDefault = false;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenOneOneTitleDefault = ``;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenOneOneDescriptionDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenOneOneDataKeyDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenOneOneAutoDataKeyDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenOneTwoMinDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenOneTwoMaxDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenTwoMinSelectionDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenTwoMaxSelectionDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenTwoDefaultValueDefault = [];
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightOneOneRequiredDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightOneOneReadonlyDefault = false;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightOneOneTitleDefault = ``;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightOneOneDescriptionDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightOneOneDataKeyDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightOneOneAutoDataKeyDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightOneTwoMinDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightOneTwoMaxDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightTwoDefaultValueDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineOneOneRequiredDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineOneOneReadonlyDefault = false;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineOneOneTitleDefault = ``;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineOneOneDescriptionDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineOneOneDataKeyDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineOneOneAutoDataKeyDefault = true;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineOneTwoMinDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineOneTwoMaxDefault = null;
export const formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineTwoDefaultValueDefault = { start: null, end: null };
export const formItemGroupFourConfigTwoFieldsItemThreeInLibraryDefault = false;
export const formItemGroupFourConfigTwoFieldsDefault = [];
export const FormItemGroup = zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemGroupOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemGroupOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemGroupOneOneTagsItemValueDefault)
})).default(formItemGroupOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemGroupOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemGroupOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemGroupOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemGroupOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemGroupOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemGroupOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemGroupOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemGroupTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemGroupTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemGroupTwoOneTagsItemValueDefault)
})).default(formItemGroupTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemGroupTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemGroupTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemGroupTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemGroupTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemGroupTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemGroupTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemGroupTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['group'])
}))).and(zod.object({
  "inLibrary": zod.boolean().default(formItemGroupThreeInLibraryDefault)
})).and(zod.object({
  "config": zod.object({
  "title": zod.string().nullable().default(formItemGroupFourConfigOneTitleDefault),
  "description": zod.string().nullish().default(formItemGroupFourConfigOneDescriptionDefault),
  "repeatable": zod.boolean().default(formItemGroupFourConfigOneRepeatableDefault),
  "divisionCount": zod.number().min(1).default(formItemGroupFourConfigOneDivisionCountDefault),
  "orientation": zod.enum(['horizonal', 'vertical']).default(formItemGroupFourConfigOneOrientationDefault)
}).and(zod.object({
  "fields": zod.array(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemGroupFourConfigTwoFieldsItemOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemGroupFourConfigTwoFieldsItemOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemGroupFourConfigTwoFieldsItemOneOneTagsItemValueDefault)
})).default(formItemGroupFourConfigTwoFieldsItemOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemGroupFourConfigTwoFieldsItemOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemGroupFourConfigTwoFieldsItemOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemGroupFourConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemGroupFourConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemGroupFourConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemGroupFourConfigTwoFieldsItemOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "id": zod.uuid(),
  "addedAt": zod.string(),
  "updatedAt": zod.string(),
  "itemId": zod.uuid()
})).and(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoOneTagsItemValueDefault)
})).default(formItemGroupFourConfigTwoFieldsItemTwoOneTagsDefault),
  "metaTag": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(formItemGroupFourConfigTwoFieldsItemTwoOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(formItemGroupFourConfigTwoFieldsItemTwoOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(formItemGroupFourConfigTwoFieldsItemTwoOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(formItemGroupFourConfigTwoFieldsItemTwoOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(formItemGroupFourConfigTwoFieldsItemTwoOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['field']),
  "parentId": zod.uuid().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoParentIdDefault),
  "config": zod.union([zod.object({
  "required": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneOneReadonlyDefault),
  "title": zod.string().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['geo-point']),
  "defaultValue": zod.object({
  "lat": zod.number().max(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneTwoDefaultValueLatMax),
  "long": zod.number().max(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneTwoDefaultValueLongMax)
}).nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigOneTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['geo-point'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoOneReadonlyDefault),
  "title": zod.string().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoOneTitleDefault),
  "description": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['integer', 'float']),
  "min": zod.number().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoTwoMinDefault),
  "max": zod.number().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoTwoMaxDefault),
  "defaultValue": zod.number().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigTwoTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['integer', 'float'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigThreeOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigThreeOneReadonlyDefault),
  "title": zod.string().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigThreeOneTitleDefault),
  "description": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigThreeOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigThreeOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigThreeOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['boolean']),
  "defaultValue": zod.boolean().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigThreeTwoDefaultValueDefault),
  "renderAs": zod.enum(['select', 'checkbox']).nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigThreeTwoRenderAsDefault)
})).and(zod.object({
  "type": zod.enum(['boolean'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourOneReadonlyDefault),
  "title": zod.string().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourOneTitleDefault),
  "description": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['text', 'multiline']),
  "placeholder": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourTwoPlaceholderDefault),
  "pattern": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourTwoPatternDefault),
  "minlength": zod.number().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourTwoMinlengthDefault),
  "maxlength": zod.number().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourTwoMaxlengthDefault),
  "defaultValue": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFourTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['text', 'multiline'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveOneReadonlyDefault),
  "title": zod.string().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveOneTitleDefault),
  "description": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['single-select']),
  "itemSourceRef": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveTwoItemSourceRefDefault),
  "defaultValue": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveTwoDefaultValueDefault),
  "hardItems": zod.array(zod.object({
  "label": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveTwoHardItemsItemLabelDefault),
  "value": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveTwoHardItemsItemValueDefault)
})).default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigFiveTwoHardItemsDefault)
})).and(zod.object({
  "type": zod.enum(['single-select'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixOneReadonlyDefault),
  "title": zod.string().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixOneTitleDefault),
  "description": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['multi-select']),
  "itemSourceRef": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixTwoItemSourceRefDefault),
  "defaultValue": zod.array(zod.string()).nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixTwoDefaultValueDefault),
  "hardItems": zod.array(zod.object({
  "label": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixTwoHardItemsItemLabelDefault),
  "value": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixTwoHardItemsItemValueDefault)
})).default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSixTwoHardItemsDefault)
})).and(zod.object({
  "type": zod.enum(['multi-select'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenOneOneReadonlyDefault),
  "title": zod.string().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenOneOneAutoDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date']),
  "minSelection": zod.number().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenTwoMinSelectionDefault),
  "maxSelection": zod.number().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenTwoMaxSelectionDefault),
  "defaultValue": zod.array(zod.number()).nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigSevenTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightOneOneReadonlyDefault),
  "title": zod.string().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightOneOneAutoDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time']),
  "defaultValue": zod.number().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigEightTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time'])
})),zod.object({
  "required": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineOneOneReadonlyDefault),
  "title": zod.string().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineOneOneTitleDefault),
  "description": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineOneOneAutoDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineOneTwoMinDefault),
  "max": zod.number().nullable().default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date-range']),
  "defaultValue": zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
}).default(formItemGroupFourConfigTwoFieldsItemTwoTwoConfigNineTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date-range'])
}))])
})).and(zod.object({
  "type": zod.enum(['field'])
}))).and(zod.object({
  "inLibrary": zod.boolean().default(formItemGroupFourConfigTwoFieldsItemThreeInLibraryDefault)
})).and(zod.object({
  "type": zod.enum(['field'])
}))).default(formItemGroupFourConfigTwoFieldsDefault)
}))
})).and(zod.object({
  "type": zod.enum(['group'])
}))

export type FormItemGroup = zod.input<typeof FormItemGroup>;
export type FormItemGroupOutput = zod.output<typeof FormItemGroup>;
