/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const geoPointFieldConfigOneOneDataKeyDefault = null;
export const geoPointFieldConfigOneOneAutoDataKeyDefault = true;
export const geoPointFieldConfigOneTwoRequiredDefault = true;
export const geoPointFieldConfigOneTwoReadonlyDefault = false;
export const geoPointFieldConfigOneTwoTitleDefault = ``;
export const geoPointFieldConfigOneTwoDescriptionDefault = null;
export const geoPointFieldConfigTwoDefaultValueLatMax = 90;

export const geoPointFieldConfigTwoDefaultValueLongMax = 180;

export const geoPointFieldConfigTwoDefaultValueDefault = null;
export const GeoPointFieldConfig = zod.object({
  "dataKey": zod.string().nullable().default(geoPointFieldConfigOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(geoPointFieldConfigOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(geoPointFieldConfigOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(geoPointFieldConfigOneTwoReadonlyDefault),
  "title": zod.string().default(geoPointFieldConfigOneTwoTitleDefault),
  "description": zod.string().nullish().default(geoPointFieldConfigOneTwoDescriptionDefault)
})).and(zod.object({
  "type": zod.enum(['geo-point']),
  "defaultValue": zod.object({
  "lat": zod.number().max(geoPointFieldConfigTwoDefaultValueLatMax),
  "long": zod.number().max(geoPointFieldConfigTwoDefaultValueLongMax)
}).nullish().default(geoPointFieldConfigTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['geo-point'])
}))

export type GeoPointFieldConfig = zod.input<typeof GeoPointFieldConfig>;
export type GeoPointFieldConfigOutput = zod.output<typeof GeoPointFieldConfig>;
