/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const GetFacilityInfoParams = zod.object({
  "sv": zod.uuid().optional(),
  "fv": zod.uuid().optional(),
  "tags": zod.array(zod.string()).optional()
})

export type GetFacilityInfoParams = zod.input<typeof GetFacilityInfoParams>;
