/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const hasDataKeyDataKeyDefault = null;
export const hasDataKeyAutoDataKeyDefault = true;
export const HasDataKey = zod.object({
  "dataKey": zod.string().nullable().default(hasDataKeyDataKeyDefault),
  "autoDataKey": zod.boolean().default(hasDataKeyAutoDataKeyDefault)
})

export type HasDataKey = zod.input<typeof HasDataKey>;
export type HasDataKeyOutput = zod.output<typeof HasDataKey>;
