/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface AvailabilityResponse extends AdditionalDataHolder, Parsable {
    /**
     * The available property
     */
    available?: boolean | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AvailabilityResponse}
 */
// @ts-ignore
export function createAvailabilityResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAvailabilityResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Dataset}
 */
// @ts-ignore
export function createDatasetFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDataset;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DatasetItem}
 */
// @ts-ignore
export function createDatasetItemFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDatasetItem;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DatasetParentRef}
 */
// @ts-ignore
export function createDatasetParentRefFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDatasetParentRef;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FormDefinition}
 */
// @ts-ignore
export function createFormDefinitionFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFormDefinition;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FormField}
 */
// @ts-ignore
export function createFormFieldFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFormField;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FormLookup}
 */
// @ts-ignore
export function createFormLookupFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFormLookup;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FormSection_relevance}
 */
// @ts-ignore
export function createFormSection_relevanceFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFormSection_relevance;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FormSection}
 */
// @ts-ignore
export function createFormSectionFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFormSection;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FormVersionLookup}
 */
// @ts-ignore
export function createFormVersionLookupFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFormVersionLookup;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RelevanceDefinition}
 */
// @ts-ignore
export function createRelevanceDefinitionFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRelevanceDefinition;
}
export interface Dataset extends AdditionalDataHolder, Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The items property
     */
    items?: DatasetItem[] | null;
    /**
     * The key property
     */
    key?: string | null;
    /**
     * The parent property
     */
    parent?: DatasetParentRef | null;
    /**
     * The parentId property
     */
    parentId?: Guid | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The updatedAt property
     */
    updatedAt?: Date | null;
}
export interface DatasetItem extends AdditionalDataHolder, Parsable {
    /**
     * The i18nKey property
     */
    i18nKey?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The label property
     */
    label?: string | null;
    /**
     * The ordinal property
     */
    ordinal?: number | null;
    /**
     * The parentValue property
     */
    parentValue?: string | null;
    /**
     * The value property
     */
    value?: string | null;
}
export interface DatasetParentRef extends AdditionalDataHolder, Parsable {
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The key property
     */
    key?: string | null;
    /**
     * The title property
     */
    title?: string | null;
}
/**
 * The deserialization information for the current model
 * @param AvailabilityResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAvailabilityResponse(availabilityResponse: Partial<AvailabilityResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "available": n => { availabilityResponse.available = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Dataset The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDataset(dataset: Partial<Dataset> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { dataset.createdAt = n.getDateValue(); },
        "description": n => { dataset.description = n.getStringValue(); },
        "id": n => { dataset.id = n.getGuidValue(); },
        "items": n => { dataset.items = n.getCollectionOfObjectValues<DatasetItem>(createDatasetItemFromDiscriminatorValue); },
        "key": n => { dataset.key = n.getStringValue(); },
        "parent": n => { dataset.parent = n.getObjectValue<DatasetParentRef>(createDatasetParentRefFromDiscriminatorValue); },
        "parentId": n => { dataset.parentId = n.getGuidValue(); },
        "title": n => { dataset.title = n.getStringValue(); },
        "updatedAt": n => { dataset.updatedAt = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DatasetItem The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDatasetItem(datasetItem: Partial<DatasetItem> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "i18nKey": n => { datasetItem.i18nKey = n.getStringValue(); },
        "id": n => { datasetItem.id = n.getGuidValue(); },
        "label": n => { datasetItem.label = n.getStringValue(); },
        "ordinal": n => { datasetItem.ordinal = n.getNumberValue(); },
        "parentValue": n => { datasetItem.parentValue = n.getStringValue(); },
        "value": n => { datasetItem.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DatasetParentRef The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDatasetParentRef(datasetParentRef: Partial<DatasetParentRef> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { datasetParentRef.description = n.getStringValue(); },
        "key": n => { datasetParentRef.key = n.getStringValue(); },
        "title": n => { datasetParentRef.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param FormDefinition The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFormDefinition(formDefinition: Partial<FormDefinition> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { formDefinition.createdAt = n.getDateValue(); },
        "fields": n => { formDefinition.fields = n.getCollectionOfObjectValues<FormField>(createFormFieldFromDiscriminatorValue); },
        "form": n => { formDefinition.form = n.getStringValue(); },
        "id": n => { formDefinition.id = n.getGuidValue(); },
        "isCurrent": n => { formDefinition.isCurrent = n.getBooleanValue(); },
        "label": n => { formDefinition.label = n.getStringValue(); },
        "parentId": n => { formDefinition.parentId = n.getGuidValue(); },
        "sections": n => { formDefinition.sections = n.getCollectionOfObjectValues<FormSection>(createFormSectionFromDiscriminatorValue); },
        "updatedAt": n => { formDefinition.updatedAt = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param FormField The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFormField(formField: Partial<FormField> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { formField.createdAt = n.getDateValue(); },
        "description": n => { formField.description = n.getStringValue(); },
        "fieldId": n => { formField.fieldId = n.getGuidValue(); },
        "fieldType": n => { formField.fieldType = n.getStringValue(); },
        "formVersion": n => { formField.formVersion = n.getGuidValue(); },
        "readonly": n => { formField.readonly = n.getBooleanValue(); },
        "relevance": n => { formField.relevance = n.getObjectValue<RelevanceDefinition>(createRelevanceDefinitionFromDiscriminatorValue); },
        "sectionKey": n => { formField.sectionKey = n.getStringValue(); },
        "span": n => { formField.span = n.getNumberValue(); },
        "title": n => { formField.title = n.getStringValue(); },
        "updatedAt": n => { formField.updatedAt = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param FormLookup The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFormLookup(formLookup: Partial<FormLookup> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { formLookup.createdAt = n.getDateValue(); },
        "createdBy": n => { formLookup.createdBy = n.getStringValue(); },
        "description": n => { formLookup.description = n.getStringValue(); },
        "label": n => { formLookup.label = n.getStringValue(); },
        "logo": n => { formLookup.logo = n.getStringValue(); },
        "slug": n => { formLookup.slug = n.getStringValue(); },
        "updatedAt": n => { formLookup.updatedAt = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param FormSection The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFormSection(formSection: Partial<FormSection> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { formSection.createdAt = n.getDateValue(); },
        "fields": n => { formSection.fields = n.getCollectionOfObjectValues<FormField>(createFormFieldFromDiscriminatorValue); },
        "formVersion": n => { formSection.formVersion = n.getGuidValue(); },
        "key": n => { formSection.key = n.getStringValue(); },
        "relevance": n => { formSection.relevance = n.getObjectValue<FormSection_relevance>(createFormSection_relevanceFromDiscriminatorValue); },
        "title": n => { formSection.title = n.getStringValue(); },
        "updatedAt": n => { formSection.updatedAt = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param FormSection_relevance The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFormSection_relevance(formSection_relevance: Partial<FormSection_relevance> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param FormVersionLookup The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFormVersionLookup(formVersionLookup: Partial<FormVersionLookup> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { formVersionLookup.createdAt = n.getDateValue(); },
        "form": n => { formVersionLookup.form = n.getStringValue(); },
        "id": n => { formVersionLookup.id = n.getGuidValue(); },
        "isCurrent": n => { formVersionLookup.isCurrent = n.getBooleanValue(); },
        "label": n => { formVersionLookup.label = n.getStringValue(); },
        "parentId": n => { formVersionLookup.parentId = n.getStringValue(); },
        "updatedAt": n => { formVersionLookup.updatedAt = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RelevanceDefinition The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRelevanceDefinition(relevanceDefinition: Partial<RelevanceDefinition> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
export interface FormDefinition extends AdditionalDataHolder, Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The fields property
     */
    fields?: FormField[] | null;
    /**
     * The form property
     */
    form?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The isCurrent property
     */
    isCurrent?: boolean | null;
    /**
     * The label property
     */
    label?: string | null;
    /**
     * The parentId property
     */
    parentId?: Guid | null;
    /**
     * The sections property
     */
    sections?: FormSection[] | null;
    /**
     * The updatedAt property
     */
    updatedAt?: Date | null;
}
export interface FormField extends AdditionalDataHolder, Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The fieldId property
     */
    fieldId?: Guid | null;
    /**
     * The fieldType property
     */
    fieldType?: string | null;
    /**
     * The formVersion property
     */
    formVersion?: Guid | null;
    /**
     * The readonly property
     */
    readonly?: boolean | null;
    /**
     * The relevance property
     */
    relevance?: RelevanceDefinition | null;
    /**
     * The sectionKey property
     */
    sectionKey?: string | null;
    /**
     * The span property
     */
    span?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The updatedAt property
     */
    updatedAt?: Date | null;
}
export interface FormLookup extends AdditionalDataHolder, Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The createdBy property
     */
    createdBy?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The label property
     */
    label?: string | null;
    /**
     * The logo property
     */
    logo?: string | null;
    /**
     * The slug property
     */
    slug?: string | null;
    /**
     * The updatedAt property
     */
    updatedAt?: Date | null;
}
export interface FormSection extends AdditionalDataHolder, Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The fields property
     */
    fields?: FormField[] | null;
    /**
     * The formVersion property
     */
    formVersion?: Guid | null;
    /**
     * The key property
     */
    key?: string | null;
    /**
     * The relevance property
     */
    relevance?: FormSection_relevance | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The updatedAt property
     */
    updatedAt?: Date | null;
}
export interface FormSection_relevance extends AdditionalDataHolder, Parsable {
}
/**
 * Lookup for a form version
 */
export interface FormVersionLookup extends AdditionalDataHolder, Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The form property
     */
    form?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The isCurrent property
     */
    isCurrent?: boolean | null;
    /**
     * The label property
     */
    label?: string | null;
    /**
     * The parentId property
     */
    parentId?: string | null;
    /**
     * The updatedAt property
     */
    updatedAt?: Date | null;
}
export interface RelevanceDefinition extends AdditionalDataHolder, Parsable {
}
/**
 * Serializes information the current object
 * @param AvailabilityResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAvailabilityResponse(writer: SerializationWriter, availabilityResponse: Partial<AvailabilityResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!availabilityResponse || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("available", availabilityResponse.available);
    writer.writeAdditionalData(availabilityResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param Dataset The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDataset(writer: SerializationWriter, dataset: Partial<Dataset> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!dataset || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", dataset.createdAt);
    writer.writeStringValue("description", dataset.description);
    writer.writeGuidValue("id", dataset.id);
    writer.writeCollectionOfObjectValues<DatasetItem>("items", dataset.items, serializeDatasetItem);
    writer.writeStringValue("key", dataset.key);
    writer.writeObjectValue<DatasetParentRef>("parent", dataset.parent, serializeDatasetParentRef);
    writer.writeGuidValue("parentId", dataset.parentId);
    writer.writeStringValue("title", dataset.title);
    writer.writeDateValue("updatedAt", dataset.updatedAt);
    writer.writeAdditionalData(dataset.additionalData);
}
/**
 * Serializes information the current object
 * @param DatasetItem The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDatasetItem(writer: SerializationWriter, datasetItem: Partial<DatasetItem> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!datasetItem || isSerializingDerivedType) { return; }
    writer.writeStringValue("i18nKey", datasetItem.i18nKey);
    writer.writeGuidValue("id", datasetItem.id);
    writer.writeStringValue("label", datasetItem.label);
    writer.writeNumberValue("ordinal", datasetItem.ordinal);
    writer.writeStringValue("parentValue", datasetItem.parentValue);
    writer.writeStringValue("value", datasetItem.value);
    writer.writeAdditionalData(datasetItem.additionalData);
}
/**
 * Serializes information the current object
 * @param DatasetParentRef The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDatasetParentRef(writer: SerializationWriter, datasetParentRef: Partial<DatasetParentRef> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!datasetParentRef || isSerializingDerivedType) { return; }
    writer.writeStringValue("description", datasetParentRef.description);
    writer.writeStringValue("key", datasetParentRef.key);
    writer.writeStringValue("title", datasetParentRef.title);
    writer.writeAdditionalData(datasetParentRef.additionalData);
}
/**
 * Serializes information the current object
 * @param FormDefinition The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFormDefinition(writer: SerializationWriter, formDefinition: Partial<FormDefinition> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!formDefinition || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", formDefinition.createdAt);
    writer.writeCollectionOfObjectValues<FormField>("fields", formDefinition.fields, serializeFormField);
    writer.writeStringValue("form", formDefinition.form);
    writer.writeGuidValue("id", formDefinition.id);
    writer.writeBooleanValue("isCurrent", formDefinition.isCurrent);
    writer.writeStringValue("label", formDefinition.label);
    writer.writeGuidValue("parentId", formDefinition.parentId);
    writer.writeCollectionOfObjectValues<FormSection>("sections", formDefinition.sections, serializeFormSection);
    writer.writeDateValue("updatedAt", formDefinition.updatedAt);
    writer.writeAdditionalData(formDefinition.additionalData);
}
/**
 * Serializes information the current object
 * @param FormField The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFormField(writer: SerializationWriter, formField: Partial<FormField> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!formField || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", formField.createdAt);
    writer.writeStringValue("description", formField.description);
    writer.writeGuidValue("fieldId", formField.fieldId);
    writer.writeStringValue("fieldType", formField.fieldType);
    writer.writeGuidValue("formVersion", formField.formVersion);
    writer.writeBooleanValue("readonly", formField.readonly);
    writer.writeObjectValue<RelevanceDefinition>("relevance", formField.relevance, serializeRelevanceDefinition);
    writer.writeStringValue("sectionKey", formField.sectionKey);
    writer.writeNumberValue("span", formField.span);
    writer.writeStringValue("title", formField.title);
    writer.writeDateValue("updatedAt", formField.updatedAt);
    writer.writeAdditionalData(formField.additionalData);
}
/**
 * Serializes information the current object
 * @param FormLookup The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFormLookup(writer: SerializationWriter, formLookup: Partial<FormLookup> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!formLookup || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", formLookup.createdAt);
    writer.writeStringValue("createdBy", formLookup.createdBy);
    writer.writeStringValue("description", formLookup.description);
    writer.writeStringValue("label", formLookup.label);
    writer.writeStringValue("logo", formLookup.logo);
    writer.writeStringValue("slug", formLookup.slug);
    writer.writeDateValue("updatedAt", formLookup.updatedAt);
    writer.writeAdditionalData(formLookup.additionalData);
}
/**
 * Serializes information the current object
 * @param FormSection The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFormSection(writer: SerializationWriter, formSection: Partial<FormSection> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!formSection || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", formSection.createdAt);
    writer.writeCollectionOfObjectValues<FormField>("fields", formSection.fields, serializeFormField);
    writer.writeGuidValue("formVersion", formSection.formVersion);
    writer.writeStringValue("key", formSection.key);
    writer.writeObjectValue<FormSection_relevance>("relevance", formSection.relevance, serializeFormSection_relevance);
    writer.writeStringValue("title", formSection.title);
    writer.writeDateValue("updatedAt", formSection.updatedAt);
    writer.writeAdditionalData(formSection.additionalData);
}
/**
 * Serializes information the current object
 * @param FormSection_relevance The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFormSection_relevance(writer: SerializationWriter, formSection_relevance: Partial<FormSection_relevance> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!formSection_relevance || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(formSection_relevance.additionalData);
}
/**
 * Serializes information the current object
 * @param FormVersionLookup The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFormVersionLookup(writer: SerializationWriter, formVersionLookup: Partial<FormVersionLookup> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!formVersionLookup || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", formVersionLookup.createdAt);
    writer.writeStringValue("form", formVersionLookup.form);
    writer.writeGuidValue("id", formVersionLookup.id);
    writer.writeBooleanValue("isCurrent", formVersionLookup.isCurrent);
    writer.writeStringValue("label", formVersionLookup.label);
    writer.writeStringValue("parentId", formVersionLookup.parentId);
    writer.writeDateValue("updatedAt", formVersionLookup.updatedAt);
    writer.writeAdditionalData(formVersionLookup.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RelevanceDefinition The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRelevanceDefinition(writer: SerializationWriter, relevanceDefinition: Partial<RelevanceDefinition> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!relevanceDefinition || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(relevanceDefinition.additionalData);
}
/* tslint:enable */
/* eslint-enable */
