/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const libraryItemBaseTagsItemKeyDefault = null;
export const libraryItemBaseTagsItemValueDefault = null;
export const LibraryItemBase = zod.object({
  "id": zod.uuid(),
  "type": zod.string(),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(libraryItemBaseTagsItemKeyDefault),
  "value": zod.string().nullable().default(libraryItemBaseTagsItemValueDefault)
})).optional()
})

export type LibraryItemBase = zod.input<typeof LibraryItemBase>;
export type LibraryItemBaseOutput = zod.output<typeof LibraryItemBase>;
