/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const lookupSubmissionVersionsParamsIncludeArchivedDefault = false;
export const LookupSubmissionVersionsParams = zod.object({
  "fv": zod.uuid().optional(),
  "includeArchived": zod.boolean().default(lookupSubmissionVersionsParamsIncludeArchivedDefault)
})

export type LookupSubmissionVersionsParams = zod.input<typeof LookupSubmissionVersionsParams>;
export type LookupSubmissionVersionsParamsOutput = zod.output<typeof LookupSubmissionVersionsParams>;
