/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const lookupFormVersionsParamsLimitDefault = 10;
export const LookupFormVersionsParams = zod.object({
  "form": zod.string().optional(),
  "limit": zod.number().default(lookupFormVersionsParamsLimitDefault),
  "offset": zod.number().optional()
})

export type LookupFormVersionsParams = zod.input<typeof LookupFormVersionsParams>;
export type LookupFormVersionsParamsOutput = zod.output<typeof LookupFormVersionsParams>;
