/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const multiDateFieldConfigOneOneOneDataKeyDefault = null;
export const multiDateFieldConfigOneOneOneAutoDataKeyDefault = true;
export const multiDateFieldConfigOneOneTwoRequiredDefault = true;
export const multiDateFieldConfigOneOneTwoReadonlyDefault = false;
export const multiDateFieldConfigOneOneTwoTitleDefault = ``;
export const multiDateFieldConfigOneOneTwoDescriptionDefault = null;
export const multiDateFieldConfigOneTwoMinDefault = null;
export const multiDateFieldConfigOneTwoMaxDefault = null;
export const multiDateFieldConfigTwoMinSelectionDefault = null;
export const multiDateFieldConfigTwoMaxSelectionDefault = null;
export const multiDateFieldConfigTwoDefaultValueDefault = [];
export const MultiDateFieldConfig = zod.object({
  "dataKey": zod.string().nullable().default(multiDateFieldConfigOneOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(multiDateFieldConfigOneOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(multiDateFieldConfigOneOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(multiDateFieldConfigOneOneTwoReadonlyDefault),
  "title": zod.string().default(multiDateFieldConfigOneOneTwoTitleDefault),
  "description": zod.string().nullish().default(multiDateFieldConfigOneOneTwoDescriptionDefault)
})).and(zod.object({
  "min": zod.number().nullable().default(multiDateFieldConfigOneTwoMinDefault),
  "max": zod.number().nullable().default(multiDateFieldConfigOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date']),
  "minSelection": zod.number().nullish().default(multiDateFieldConfigTwoMinSelectionDefault),
  "maxSelection": zod.number().nullish().default(multiDateFieldConfigTwoMaxSelectionDefault),
  "defaultValue": zod.array(zod.number()).nullish().default(multiDateFieldConfigTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date'])
}))

export type MultiDateFieldConfig = zod.input<typeof MultiDateFieldConfig>;
export type MultiDateFieldConfigOutput = zod.output<typeof MultiDateFieldConfig>;
