/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const newFormItemNoteOnePathDefault = null;
export const newFormItemNoteOneTagsDefault = [];
export const newFormItemNoteOneRelevanceEnabledDefault = true;
export const newFormItemNoteOneRelevanceOperatorDefault = `and`;
export const newFormItemNoteOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const newFormItemNoteOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const newFormItemNoteOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const newFormItemNoteOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const newFormItemNoteTwoConfigFontSizeDefault = 13;
export const NewFormItemNote = zod.object({
  "path": zod.string().nullable().default(newFormItemNoteOnePathDefault),
  "tags": zod.array(zod.string()).default(newFormItemNoteOneTagsDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(newFormItemNoteOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(newFormItemNoteOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(newFormItemNoteOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(newFormItemNoteOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(newFormItemNoteOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(newFormItemNoteOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['note']),
  "config": zod.object({
  "fontSize": zod.number().default(newFormItemNoteTwoConfigFontSizeDefault)
})
})).and(zod.object({
  "type": zod.enum(['note'])
}))

export type NewFormItemNote = zod.input<typeof NewFormItemNote>;
