/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const newFormItemGroupOneOnePathDefault = null;
export const newFormItemGroupOneOneTagsItemKeyDefault = null;
export const newFormItemGroupOneOneTagsItemValueDefault = null;
export const newFormItemGroupOneOneTagsDefault = [];
export const newFormItemGroupOneOneMetaTagDefault = null;
export const newFormItemGroupOneOneRelevanceEnabledDefault = true;
export const newFormItemGroupOneOneRelevanceOperatorDefault = `and`;
export const newFormItemGroupOneOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const newFormItemGroupOneOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const newFormItemGroupOneOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const newFormItemGroupOneOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const newFormItemGroupTwoConfigOneOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigOneOneAutoDataKeyDefault = true;
export const newFormItemGroupTwoConfigOneTwoTitleDefault = null;
export const newFormItemGroupTwoConfigOneTwoDescriptionDefault = null;
export const newFormItemGroupTwoConfigOneTwoRepeatableDefault = false;
export const newFormItemGroupTwoConfigOneTwoDivisionCountDefault = 1;

export const newFormItemGroupTwoConfigOneTwoOrientationDefault = `vertical`;
export const newFormItemGroupTwoConfigTwoFieldsItemOnePathDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemOneTagsItemKeyDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemOneTagsItemValueDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemOneTagsDefault = [];
export const newFormItemGroupTwoConfigTwoFieldsItemOneMetaTagDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemOneRelevanceEnabledDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemOneRelevanceOperatorDefault = `and`;
export const newFormItemGroupTwoConfigTwoFieldsItemOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const newFormItemGroupTwoConfigTwoFieldsItemOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoParentIdDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneOneOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneOneOneAutoDataKeyDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneOneTwoRequiredDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneOneTwoReadonlyDefault = false;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneOneTwoTitleDefault = ``;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneOneTwoDescriptionDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneTwoDefaultValueLatMax = 90;

export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneTwoDefaultValueLongMax = 180;

export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneTwoDefaultValueDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoOneOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoOneOneAutoDataKeyDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoOneTwoRequiredDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoOneTwoReadonlyDefault = false;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoOneTwoTitleDefault = ``;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoOneTwoDescriptionDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoTwoMinDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoTwoMaxDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoTwoDefaultValueDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigThreeOneOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigThreeOneOneAutoDataKeyDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigThreeOneTwoRequiredDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigThreeOneTwoReadonlyDefault = false;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigThreeOneTwoTitleDefault = ``;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigThreeOneTwoDescriptionDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigThreeTwoDefaultValueDefault = false;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigThreeTwoRenderAsDefault = `checkbox`;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourOneOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourOneOneAutoDataKeyDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourOneTwoRequiredDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourOneTwoReadonlyDefault = false;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourOneTwoTitleDefault = ``;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourOneTwoDescriptionDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourTwoPlaceholderDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourTwoPatternDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourTwoMinlengthDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourTwoMaxlengthDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourTwoDefaultValueDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveOneOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveOneOneAutoDataKeyDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveOneTwoRequiredDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveOneTwoReadonlyDefault = false;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveOneTwoTitleDefault = ``;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveOneTwoDescriptionDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveTwoItemSourceRefDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveTwoDefaultValueDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveTwoHardItemsItemLabelDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveTwoHardItemsItemValueDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveTwoHardItemsDefault = [];
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixOneOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixOneOneAutoDataKeyDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixOneTwoRequiredDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixOneTwoReadonlyDefault = false;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixOneTwoTitleDefault = ``;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixOneTwoDescriptionDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixTwoItemSourceRefDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixTwoDefaultValueDefault = [];
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixTwoHardItemsItemLabelDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixTwoHardItemsItemValueDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixTwoHardItemsDefault = [];
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenOneOneOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenOneOneOneAutoDataKeyDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenOneOneTwoRequiredDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenOneOneTwoReadonlyDefault = false;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenOneOneTwoTitleDefault = ``;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenOneOneTwoDescriptionDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenOneTwoMinDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenOneTwoMaxDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenTwoMinSelectionDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenTwoMaxSelectionDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenTwoDefaultValueDefault = [];
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightOneOneOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightOneOneOneAutoDataKeyDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightOneOneTwoRequiredDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightOneOneTwoReadonlyDefault = false;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightOneOneTwoTitleDefault = ``;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightOneOneTwoDescriptionDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightOneTwoMinDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightOneTwoMaxDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightTwoDefaultValueDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineOneOneOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineOneOneOneAutoDataKeyDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineOneOneTwoRequiredDefault = true;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineOneOneTwoReadonlyDefault = false;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineOneOneTwoTitleDefault = ``;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineOneOneTwoDescriptionDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineOneTwoMinDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineOneTwoMaxDefault = null;
export const newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineTwoDefaultValueDefault = { start: null, end: null };
export const newFormItemGroupTwoConfigTwoFieldsDefault = [];
export const NewFormItemGroup = zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(newFormItemGroupOneOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(newFormItemGroupOneOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(newFormItemGroupOneOneTagsItemValueDefault)
})).default(newFormItemGroupOneOneTagsDefault),
  "metaTag": zod.string().nullish().default(newFormItemGroupOneOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(newFormItemGroupOneOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(newFormItemGroupOneOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(newFormItemGroupOneOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(newFormItemGroupOneOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(newFormItemGroupOneOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(newFormItemGroupOneOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['group'])
})).and(zod.object({
  "config": zod.object({
  "dataKey": zod.string().nullable().default(newFormItemGroupTwoConfigOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(newFormItemGroupTwoConfigOneOneAutoDataKeyDefault)
}).and(zod.object({
  "title": zod.string().nullable().default(newFormItemGroupTwoConfigOneTwoTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigOneTwoDescriptionDefault),
  "repeatable": zod.boolean().default(newFormItemGroupTwoConfigOneTwoRepeatableDefault),
  "divisionCount": zod.number().min(1).default(newFormItemGroupTwoConfigOneTwoDivisionCountDefault),
  "orientation": zod.enum(['horizonal', 'vertical']).default(newFormItemGroupTwoConfigOneTwoOrientationDefault)
})).and(zod.object({
  "fields": zod.array(zod.object({
  "itemId": zod.uuid().nullish(),
  "path": zod.string().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemOnePathDefault),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemOneTagsItemValueDefault)
})).default(newFormItemGroupTwoConfigTwoFieldsItemOneTagsDefault),
  "metaTag": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemOneMetaTagDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(newFormItemGroupTwoConfigTwoFieldsItemOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(newFormItemGroupTwoConfigTwoFieldsItemOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(newFormItemGroupTwoConfigTwoFieldsItemOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(newFormItemGroupTwoConfigTwoFieldsItemOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(newFormItemGroupTwoConfigTwoFieldsItemOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['field']),
  "parentId": zod.uuid().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoParentIdDefault),
  "config": zod.union([zod.object({
  "dataKey": zod.string().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneOneTwoReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneOneTwoTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneOneTwoDescriptionDefault)
})).and(zod.object({
  "type": zod.enum(['geo-point']),
  "defaultValue": zod.object({
  "lat": zod.number().max(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneTwoDefaultValueLatMax),
  "long": zod.number().max(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneTwoDefaultValueLongMax)
}).nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigOneTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['geo-point'])
})),zod.object({
  "dataKey": zod.string().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoOneTwoReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoOneTwoTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoOneTwoDescriptionDefault)
})).and(zod.object({
  "type": zod.enum(['integer', 'float']),
  "min": zod.number().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoTwoMinDefault),
  "max": zod.number().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoTwoMaxDefault),
  "defaultValue": zod.number().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigTwoTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['integer', 'float'])
})),zod.object({
  "dataKey": zod.string().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigThreeOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigThreeOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigThreeOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigThreeOneTwoReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigThreeOneTwoTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigThreeOneTwoDescriptionDefault)
})).and(zod.object({
  "type": zod.enum(['boolean']),
  "defaultValue": zod.boolean().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigThreeTwoDefaultValueDefault),
  "renderAs": zod.enum(['select', 'checkbox']).nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigThreeTwoRenderAsDefault)
})).and(zod.object({
  "type": zod.enum(['boolean'])
})),zod.object({
  "dataKey": zod.string().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourOneTwoReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourOneTwoTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourOneTwoDescriptionDefault)
})).and(zod.object({
  "type": zod.enum(['text', 'multiline']),
  "placeholder": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourTwoPlaceholderDefault),
  "pattern": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourTwoPatternDefault),
  "minlength": zod.number().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourTwoMinlengthDefault),
  "maxlength": zod.number().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourTwoMaxlengthDefault),
  "defaultValue": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFourTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['text', 'multiline'])
})),zod.object({
  "dataKey": zod.string().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveOneTwoReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveOneTwoTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveOneTwoDescriptionDefault)
})).and(zod.object({
  "type": zod.enum(['single-select']),
  "itemSourceRef": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveTwoItemSourceRefDefault),
  "defaultValue": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveTwoDefaultValueDefault),
  "hardItems": zod.array(zod.object({
  "label": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveTwoHardItemsItemLabelDefault),
  "value": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveTwoHardItemsItemValueDefault)
})).default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigFiveTwoHardItemsDefault)
})).and(zod.object({
  "type": zod.enum(['single-select'])
})),zod.object({
  "dataKey": zod.string().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixOneTwoReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixOneTwoTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixOneTwoDescriptionDefault)
})).and(zod.object({
  "type": zod.enum(['multi-select']),
  "itemSourceRef": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixTwoItemSourceRefDefault),
  "defaultValue": zod.array(zod.string()).nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixTwoDefaultValueDefault),
  "hardItems": zod.array(zod.object({
  "label": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixTwoHardItemsItemLabelDefault),
  "value": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixTwoHardItemsItemValueDefault)
})).default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSixTwoHardItemsDefault)
})).and(zod.object({
  "type": zod.enum(['multi-select'])
})),zod.object({
  "dataKey": zod.string().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenOneOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenOneOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenOneOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenOneOneTwoReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenOneOneTwoTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenOneOneTwoDescriptionDefault)
})).and(zod.object({
  "min": zod.number().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenOneTwoMinDefault),
  "max": zod.number().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date']),
  "minSelection": zod.number().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenTwoMinSelectionDefault),
  "maxSelection": zod.number().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenTwoMaxSelectionDefault),
  "defaultValue": zod.array(zod.number()).nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigSevenTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date'])
})),zod.object({
  "dataKey": zod.string().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightOneOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightOneOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightOneOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightOneOneTwoReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightOneOneTwoTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightOneOneTwoDescriptionDefault)
})).and(zod.object({
  "min": zod.number().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightOneTwoMinDefault),
  "max": zod.number().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time']),
  "defaultValue": zod.number().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigEightTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time'])
})),zod.object({
  "dataKey": zod.string().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineOneOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineOneOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineOneOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineOneOneTwoReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineOneOneTwoTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineOneOneTwoDescriptionDefault)
})).and(zod.object({
  "min": zod.number().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineOneTwoMinDefault),
  "max": zod.number().nullable().default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date-range']),
  "defaultValue": zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
}).default(newFormItemGroupTwoConfigTwoFieldsItemTwoConfigNineTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date-range'])
}))])
})).and(zod.object({
  "type": zod.enum(['field'])
}))).default(newFormItemGroupTwoConfigTwoFieldsDefault)
}))
})).and(zod.object({
  "type": zod.enum(['group'])
}))

export type NewFormItemGroup = zod.input<typeof NewFormItemGroup>;
export type NewFormItemGroupOutput = zod.output<typeof NewFormItemGroup>;
