/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const newFormItemGroupOnePathDefault = null;
export const newFormItemGroupOneTagsDefault = [];
export const newFormItemGroupOneRelevanceEnabledDefault = true;
export const newFormItemGroupOneRelevanceOperatorDefault = `and`;
export const newFormItemGroupOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const newFormItemGroupOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const newFormItemGroupOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const newFormItemGroupOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const newFormItemGroupTwoConfigFieldsItemOnePathDefault = null;
export const newFormItemGroupTwoConfigFieldsItemOneTagsDefault = [];
export const newFormItemGroupTwoConfigFieldsItemOneRelevanceEnabledDefault = true;
export const newFormItemGroupTwoConfigFieldsItemOneRelevanceOperatorDefault = `and`;
export const newFormItemGroupTwoConfigFieldsItemOneRelevanceLogicItemExpressionsItemFieldDefault = null;
export const newFormItemGroupTwoConfigFieldsItemOneRelevanceLogicItemExpressionsItemOperatorDefault = null;
export const newFormItemGroupTwoConfigFieldsItemOneRelevanceLogicItemExpressionsItemNegatedDefault = false;
export const newFormItemGroupTwoConfigFieldsItemOneRelevanceLogicItemExpressionsItemValueDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigOneOneRequiredDefault = true;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigOneOneReadonlyDefault = false;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigOneOneTitleDefault = ``;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigOneOneDescriptionDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigOneOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigOneTwoDefaultValueLatMax = 90;

export const newFormItemGroupTwoConfigFieldsItemTwoConfigOneTwoDefaultValueLongMax = 180;

export const newFormItemGroupTwoConfigFieldsItemTwoConfigOneTwoDefaultValueDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigTwoOneRequiredDefault = true;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigTwoOneReadonlyDefault = false;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigTwoOneTitleDefault = ``;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigTwoOneDescriptionDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigTwoOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigTwoTwoMinDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigTwoTwoMaxDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigTwoTwoDefaultValueDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigThreeOneRequiredDefault = true;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigThreeOneReadonlyDefault = false;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigThreeOneTitleDefault = ``;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigThreeOneDescriptionDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigThreeOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigThreeTwoDefaultValueDefault = false;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigThreeTwoRenderAsDefault = `checkbox`;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFourOneRequiredDefault = true;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFourOneReadonlyDefault = false;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFourOneTitleDefault = ``;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFourOneDescriptionDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFourOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFourTwoPatternDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFourTwoMinlengthDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFourTwoMaxlengthDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFourTwoDefaultValueDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFiveOneRequiredDefault = true;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFiveOneReadonlyDefault = false;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFiveOneTitleDefault = ``;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFiveOneDescriptionDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFiveOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFiveTwoItemSourceRefDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFiveTwoDefaultValueDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFiveTwoHardItemsItemLabelDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFiveTwoHardItemsItemValueDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigFiveTwoHardItemsDefault = [];
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSixOneOneRequiredDefault = true;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSixOneOneReadonlyDefault = false;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSixOneOneTitleDefault = ``;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSixOneOneDescriptionDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSixOneOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSixOneTwoMinDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSixOneTwoMaxDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSixTwoMinSelectionDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSixTwoMaxSelectionDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSixTwoDefaultValueDefault = [];
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSevenOneOneRequiredDefault = true;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSevenOneOneReadonlyDefault = false;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSevenOneOneTitleDefault = ``;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSevenOneOneDescriptionDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSevenOneOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSevenOneTwoMinDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSevenOneTwoMaxDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigSevenTwoDefaultValueDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigEightOneOneRequiredDefault = true;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigEightOneOneReadonlyDefault = false;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigEightOneOneTitleDefault = ``;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigEightOneOneDescriptionDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigEightOneOneDataKeyDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigEightOneTwoMinDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigEightOneTwoMaxDefault = null;
export const newFormItemGroupTwoConfigFieldsItemTwoConfigEightTwoDefaultValueDefault = { start: null, end: null };
export const newFormItemGroupTwoConfigFieldsDefault = [];
export const NewFormItemGroup = zod.object({
  "path": zod.string().nullable().default(newFormItemGroupOnePathDefault),
  "tags": zod.array(zod.string()).default(newFormItemGroupOneTagsDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(newFormItemGroupOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(newFormItemGroupOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(newFormItemGroupOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(newFormItemGroupOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(newFormItemGroupOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(newFormItemGroupOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['group']),
  "config": zod.object({
  "fields": zod.array(zod.object({
  "path": zod.string().nullable().default(newFormItemGroupTwoConfigFieldsItemOnePathDefault),
  "tags": zod.array(zod.string()).default(newFormItemGroupTwoConfigFieldsItemOneTagsDefault),
  "relevance": zod.object({
  "enabled": zod.boolean().default(newFormItemGroupTwoConfigFieldsItemOneRelevanceEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(newFormItemGroupTwoConfigFieldsItemOneRelevanceOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(newFormItemGroupTwoConfigFieldsItemOneRelevanceLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(newFormItemGroupTwoConfigFieldsItemOneRelevanceLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(newFormItemGroupTwoConfigFieldsItemOneRelevanceLogicItemExpressionsItemNegatedDefault),
  "value": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemOneRelevanceLogicItemExpressionsItemValueDefault)
}))
}))
})
}).and(zod.object({
  "type": zod.enum(['field']),
  "config": zod.union([zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigOneOneReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigFieldsItemTwoConfigOneOneTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigOneOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['geo-point']),
  "defaultValue": zod.object({
  "lat": zod.number().max(newFormItemGroupTwoConfigFieldsItemTwoConfigOneTwoDefaultValueLatMax),
  "long": zod.number().max(newFormItemGroupTwoConfigFieldsItemTwoConfigOneTwoDefaultValueLongMax)
}).nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigOneTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['geo-point'])
})),zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigTwoOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigTwoOneReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigFieldsItemTwoConfigTwoOneTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigTwoOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigTwoOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['integer', 'float']),
  "min": zod.number().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigTwoTwoMinDefault),
  "max": zod.number().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigTwoTwoMaxDefault),
  "defaultValue": zod.number().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigTwoTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['integer', 'float'])
})),zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigThreeOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigThreeOneReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigFieldsItemTwoConfigThreeOneTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigThreeOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigThreeOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['boolean']),
  "defaultValue": zod.boolean().default(newFormItemGroupTwoConfigFieldsItemTwoConfigThreeTwoDefaultValueDefault),
  "renderAs": zod.enum(['select', 'checkbox']).nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigThreeTwoRenderAsDefault)
})).and(zod.object({
  "type": zod.enum(['boolean'])
})),zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFourOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFourOneReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFourOneTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFourOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFourOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['text', 'multiline']),
  "pattern": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFourTwoPatternDefault),
  "minlength": zod.number().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFourTwoMinlengthDefault),
  "maxlength": zod.number().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFourTwoMaxlengthDefault),
  "defaultValue": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFourTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['text', 'multiline'])
})),zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFiveOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFiveOneReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFiveOneTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFiveOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFiveOneDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['single-select', 'multi-select']),
  "itemSourceRef": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFiveTwoItemSourceRefDefault),
  "defaultValue": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFiveTwoDefaultValueDefault),
  "hardItems": zod.array(zod.object({
  "label": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFiveTwoHardItemsItemLabelDefault),
  "value": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigFiveTwoHardItemsItemValueDefault)
})).default(newFormItemGroupTwoConfigFieldsItemTwoConfigFiveTwoHardItemsDefault)
})).and(zod.object({
  "type": zod.enum(['single-select', 'multi-select'])
})),zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSixOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSixOneOneReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSixOneOneTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSixOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSixOneOneDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSixOneTwoMinDefault),
  "max": zod.number().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSixOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date']),
  "minSelection": zod.number().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSixTwoMinSelectionDefault),
  "maxSelection": zod.number().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSixTwoMaxSelectionDefault),
  "defaultValue": zod.array(zod.number()).nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSixTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['multi-date'])
})),zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSevenOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSevenOneOneReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSevenOneOneTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSevenOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSevenOneOneDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSevenOneTwoMinDefault),
  "max": zod.number().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSevenOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time']),
  "defaultValue": zod.number().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigSevenTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time'])
})),zod.object({
  "required": zod.boolean().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigEightOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigEightOneOneReadonlyDefault),
  "title": zod.string().default(newFormItemGroupTwoConfigFieldsItemTwoConfigEightOneOneTitleDefault),
  "description": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigEightOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(newFormItemGroupTwoConfigFieldsItemTwoConfigEightOneOneDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigEightOneTwoMinDefault),
  "max": zod.number().nullable().default(newFormItemGroupTwoConfigFieldsItemTwoConfigEightOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date-range']),
  "defaultValue": zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
}).default(newFormItemGroupTwoConfigFieldsItemTwoConfigEightTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date-range'])
}))])
})).and(zod.object({
  "type": zod.enum(['field'])
}))).default(newFormItemGroupTwoConfigFieldsDefault)
})
})).and(zod.object({
  "type": zod.enum(['group'])
}))

export type NewFormItemGroup = zod.input<typeof NewFormItemGroup>;
