/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const noteLibraryItemOneTagsItemKeyDefault = null;
export const noteLibraryItemOneTagsItemValueDefault = null;
export const noteLibraryItemTwoConfigFontSizeDefault = 13;
export const NoteLibraryItem = zod.object({
  "id": zod.uuid(),
  "type": zod.string(),
  "tags": zod.array(zod.object({
  "key": zod.string().nullable().default(noteLibraryItemOneTagsItemKeyDefault),
  "value": zod.string().nullable().default(noteLibraryItemOneTagsItemValueDefault)
})).optional()
}).and(zod.object({
  "type": zod.enum(['note']).optional(),
  "config": zod.object({
  "fontSize": zod.number().default(noteLibraryItemTwoConfigFontSizeDefault)
}).optional()
})).and(zod.object({
  "type": zod.enum(['note'])
}))

export type NoteLibraryItem = zod.input<typeof NoteLibraryItem>;
export type NoteLibraryItemOutput = zod.output<typeof NoteLibraryItem>;
