/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const noteItemConfigFontSizeDefault = 13;
export const NoteItemConfig = zod.object({
  "fontSize": zod.number().default(noteItemConfigFontSizeDefault)
})

export type NoteItemConfig = zod.input<typeof NoteItemConfig>;
