/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const numberFieldConfigOneRequiredDefault = true;
export const numberFieldConfigOneReadonlyDefault = false;
export const numberFieldConfigOneTitleDefault = ``;
export const numberFieldConfigOneDescriptionDefault = null;
export const numberFieldConfigOneDataKeyDefault = null;
export const numberFieldConfigOneAutoDataKeyDefault = true;
export const numberFieldConfigTwoMinDefault = null;
export const numberFieldConfigTwoMaxDefault = null;
export const numberFieldConfigTwoDefaultValueDefault = null;
export const NumberFieldConfig = zod.object({
  "required": zod.boolean().nullable().default(numberFieldConfigOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(numberFieldConfigOneReadonlyDefault),
  "title": zod.string().default(numberFieldConfigOneTitleDefault),
  "description": zod.string().nullish().default(numberFieldConfigOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(numberFieldConfigOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(numberFieldConfigOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['integer', 'float']),
  "min": zod.number().nullish().default(numberFieldConfigTwoMinDefault),
  "max": zod.number().nullish().default(numberFieldConfigTwoMaxDefault),
  "defaultValue": zod.number().nullish().default(numberFieldConfigTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['integer', 'float'])
}))

export type NumberFieldConfig = zod.input<typeof NumberFieldConfig>;
