/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const pullDocumentChangesParamsBatchSizeDefault = 1;


export const PullDocumentChangesParams = zod.object({
  "lastCheckpoint": zod.string().optional(),
  "batchSize": zod.number().min(1).default(pullDocumentChangesParamsBatchSizeDefault)
})

export type PullDocumentChangesParams = zod.input<typeof PullDocumentChangesParams>;
export type PullDocumentChangesParamsOutput = zod.output<typeof PullDocumentChangesParams>;
