/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const PushDocumentChangeData = zod.record(zod.string(), zod.unknown())

export type PushDocumentChangeData = zod.input<typeof PushDocumentChangeData>;
export type PushDocumentChangeDataOutput = zod.output<typeof PushDocumentChangeData>;
