/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const rangeDateFieldConfigOneOneRequiredDefault = true;
export const rangeDateFieldConfigOneOneReadonlyDefault = false;
export const rangeDateFieldConfigOneOneTitleDefault = ``;
export const rangeDateFieldConfigOneOneDescriptionDefault = null;
export const rangeDateFieldConfigOneOneDataKeyDefault = null;
export const rangeDateFieldConfigOneTwoMinDefault = null;
export const rangeDateFieldConfigOneTwoMaxDefault = null;
export const rangeDateFieldConfigTwoDefaultValueDefault = { start: null, end: null };
export const RangeDateFieldConfig = zod.object({
  "required": zod.boolean().nullable().default(rangeDateFieldConfigOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(rangeDateFieldConfigOneOneReadonlyDefault),
  "title": zod.string().default(rangeDateFieldConfigOneOneTitleDefault),
  "description": zod.string().nullish().default(rangeDateFieldConfigOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(rangeDateFieldConfigOneOneDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(rangeDateFieldConfigOneTwoMinDefault),
  "max": zod.number().nullable().default(rangeDateFieldConfigOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date-range']),
  "defaultValue": zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
}).default(rangeDateFieldConfigTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date-range'])
}))

export type RangeDateFieldConfig = zod.input<typeof RangeDateFieldConfig>;
