/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const relevanceDefinitionEnabledDefault = true;
export const relevanceDefinitionOperatorDefault = `and`;
export const relevanceDefinitionLogicItemExpressionsItemFieldDefault = null;
export const relevanceDefinitionLogicItemExpressionsItemOperatorDefault = null;
export const relevanceDefinitionLogicItemExpressionsItemNegatedDefault = false;
export const relevanceDefinitionLogicItemExpressionsItemValueDefault = null;
export const RelevanceDefinition = zod.object({
  "enabled": zod.boolean().default(relevanceDefinitionEnabledDefault),
  "operator": zod.enum(['and', 'or']).default(relevanceDefinitionOperatorDefault),
  "logic": zod.array(zod.object({
  "operator": zod.enum(['and', 'or']),
  "expressions": zod.array(zod.object({
  "field": zod.string().nullable().default(relevanceDefinitionLogicItemExpressionsItemFieldDefault),
  "operator": zod.enum(['in', 'eq', 'ne', 'gt', 'lt', 'lte', 'gte', 'empty', 'notEmpty', 'between', 'match', 'isNull', 'isNotNull', 'checked', 'unchecked', 'selectedAny', 'selectedAll', 'startsWith', 'endsWith', 'noselection', 'before', 'after', 'afterOrOn', 'beforeOrOn']).nullable().default(relevanceDefinitionLogicItemExpressionsItemOperatorDefault),
  "negated": zod.boolean().default(relevanceDefinitionLogicItemExpressionsItemNegatedDefault),
  "value": zod.union([zod.union([zod.string(),zod.number(),zod.boolean()]),zod.array(zod.union([zod.string(),zod.number(),zod.boolean()])),zod.object({
  "start": zod.number().nullish(),
  "end": zod.number().nullish()
})]).nullish().default(relevanceDefinitionLogicItemExpressionsItemValueDefault)
}))
}))
})

export type RelevanceDefinition = zod.input<typeof RelevanceDefinition>;
