/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const selectFieldConfigOneRequiredDefault = true;
export const selectFieldConfigOneReadonlyDefault = false;
export const selectFieldConfigOneTitleDefault = ``;
export const selectFieldConfigOneDescriptionDefault = null;
export const selectFieldConfigOneDataKeyDefault = null;
export const selectFieldConfigOneAutoDataKeyDefault = true;
export const selectFieldConfigTwoItemSourceRefDefault = null;
export const selectFieldConfigTwoDefaultValueDefault = null;
export const selectFieldConfigTwoHardItemsItemLabelDefault = null;
export const selectFieldConfigTwoHardItemsItemValueDefault = null;
export const selectFieldConfigTwoHardItemsDefault = [];
export const SelectFieldConfig = zod.object({
  "required": zod.boolean().nullable().default(selectFieldConfigOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(selectFieldConfigOneReadonlyDefault),
  "title": zod.string().default(selectFieldConfigOneTitleDefault),
  "description": zod.string().nullish().default(selectFieldConfigOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(selectFieldConfigOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(selectFieldConfigOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['single-select', 'multi-select']),
  "itemSourceRef": zod.string().nullish().default(selectFieldConfigTwoItemSourceRefDefault),
  "defaultValue": zod.string().nullish().default(selectFieldConfigTwoDefaultValueDefault),
  "hardItems": zod.array(zod.object({
  "label": zod.string().nullish().default(selectFieldConfigTwoHardItemsItemLabelDefault),
  "value": zod.string().nullish().default(selectFieldConfigTwoHardItemsItemValueDefault)
})).default(selectFieldConfigTwoHardItemsDefault)
})).and(zod.object({
  "type": zod.enum(['single-select', 'multi-select'])
}))

export type SelectFieldConfig = zod.input<typeof SelectFieldConfig>;
