/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const simpleDateFieldConfigOneOneRequiredDefault = true;
export const simpleDateFieldConfigOneOneReadonlyDefault = false;
export const simpleDateFieldConfigOneOneTitleDefault = ``;
export const simpleDateFieldConfigOneOneDescriptionDefault = null;
export const simpleDateFieldConfigOneOneDataKeyDefault = null;
export const simpleDateFieldConfigOneTwoMinDefault = null;
export const simpleDateFieldConfigOneTwoMaxDefault = null;
export const simpleDateFieldConfigTwoDefaultValueDefault = null;
export const SimpleDateFieldConfig = zod.object({
  "required": zod.boolean().nullable().default(simpleDateFieldConfigOneOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(simpleDateFieldConfigOneOneReadonlyDefault),
  "title": zod.string().default(simpleDateFieldConfigOneOneTitleDefault),
  "description": zod.string().nullish().default(simpleDateFieldConfigOneOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(simpleDateFieldConfigOneOneDataKeyDefault)
}).and(zod.object({
  "min": zod.number().nullable().default(simpleDateFieldConfigOneTwoMinDefault),
  "max": zod.number().nullable().default(simpleDateFieldConfigOneTwoMaxDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time']),
  "defaultValue": zod.number().nullish().default(simpleDateFieldConfigTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['date', 'date-time'])
}))

export type SimpleDateFieldConfig = zod.input<typeof SimpleDateFieldConfig>;
