/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const SubmissionVersionLookup = zod.object({
  "next": zod.number().nullish(),
  "prev": zod.number().nullish(),
  "tag": zod.string(),
  "form": zod.string().optional(),
  "changeNotes": zod.string(),
  "isCurrent": zod.boolean(),
  "archivedAt": zod.iso.datetime({}).optional(),
  "formVersion": zod.uuid().optional(),
  "index": zod.number(),
  "recordedAt": zod.iso.datetime({}),
  "validationCode": zod.string(),
  "approvedAt": zod.iso.datetime({}).optional()
})

export type SubmissionVersionLookup = zod.input<typeof SubmissionVersionLookup>;
export type SubmissionVersionLookupOutput = zod.output<typeof SubmissionVersionLookup>;
