/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const submissionLookupVersionCountDefault = 0;
export const submissionLookupVersionCountMin = 0;


export const SubmissionLookup = zod.object({
  "slug": zod.string().optional(),
  "form": zod.string(),
  "formVersion": zod.uuid(),
  "index": zod.number(),
  "recordedAt": zod.iso.datetime({}),
  "lastUpdatedAt": zod.iso.datetime({}).optional(),
  "versionCount": zod.number().min(submissionLookupVersionCountMin).default(submissionLookupVersionCountDefault)
})

export type SubmissionLookup = zod.input<typeof SubmissionLookup>;
export type SubmissionLookupOutput = zod.output<typeof SubmissionLookup>;
