/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const textFieldConfigOneRequiredDefault = true;
export const textFieldConfigOneReadonlyDefault = false;
export const textFieldConfigOneTitleDefault = ``;
export const textFieldConfigOneDescriptionDefault = null;
export const textFieldConfigOneDataKeyDefault = null;
export const textFieldConfigOneAutoDataKeyDefault = true;
export const textFieldConfigTwoPlaceholderDefault = null;
export const textFieldConfigTwoPatternDefault = null;
export const textFieldConfigTwoMinlengthDefault = null;
export const textFieldConfigTwoMaxlengthDefault = null;
export const textFieldConfigTwoDefaultValueDefault = null;
export const TextFieldConfig = zod.object({
  "required": zod.boolean().nullable().default(textFieldConfigOneRequiredDefault),
  "readonly": zod.boolean().nullable().default(textFieldConfigOneReadonlyDefault),
  "title": zod.string().default(textFieldConfigOneTitleDefault),
  "description": zod.string().nullish().default(textFieldConfigOneDescriptionDefault),
  "dataKey": zod.string().nullish().default(textFieldConfigOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(textFieldConfigOneAutoDataKeyDefault)
}).and(zod.object({
  "type": zod.enum(['text', 'multiline']),
  "placeholder": zod.string().nullish().default(textFieldConfigTwoPlaceholderDefault),
  "pattern": zod.string().nullish().default(textFieldConfigTwoPatternDefault),
  "minlength": zod.number().nullish().default(textFieldConfigTwoMinlengthDefault),
  "maxlength": zod.number().nullish().default(textFieldConfigTwoMaxlengthDefault),
  "defaultValue": zod.string().nullish().default(textFieldConfigTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['text', 'multiline'])
}))

export type TextFieldConfig = zod.input<typeof TextFieldConfig>;
