/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const textFieldConfigOneOneDataKeyDefault = null;
export const textFieldConfigOneOneAutoDataKeyDefault = true;
export const textFieldConfigOneTwoRequiredDefault = true;
export const textFieldConfigOneTwoReadonlyDefault = false;
export const textFieldConfigOneTwoTitleDefault = ``;
export const textFieldConfigOneTwoDescriptionDefault = null;
export const textFieldConfigTwoPlaceholderDefault = null;
export const textFieldConfigTwoPatternDefault = null;
export const textFieldConfigTwoMinlengthDefault = null;
export const textFieldConfigTwoMaxlengthDefault = null;
export const textFieldConfigTwoDefaultValueDefault = null;
export const TextFieldConfig = zod.object({
  "dataKey": zod.string().nullable().default(textFieldConfigOneOneDataKeyDefault),
  "autoDataKey": zod.boolean().default(textFieldConfigOneOneAutoDataKeyDefault)
}).and(zod.object({
  "required": zod.boolean().nullable().default(textFieldConfigOneTwoRequiredDefault),
  "readonly": zod.boolean().nullable().default(textFieldConfigOneTwoReadonlyDefault),
  "title": zod.string().default(textFieldConfigOneTwoTitleDefault),
  "description": zod.string().nullish().default(textFieldConfigOneTwoDescriptionDefault)
})).and(zod.object({
  "type": zod.enum(['text', 'multiline']),
  "placeholder": zod.string().nullish().default(textFieldConfigTwoPlaceholderDefault),
  "pattern": zod.string().nullish().default(textFieldConfigTwoPatternDefault),
  "minlength": zod.number().nullish().default(textFieldConfigTwoMinlengthDefault),
  "maxlength": zod.number().nullish().default(textFieldConfigTwoMaxlengthDefault),
  "defaultValue": zod.string().nullish().default(textFieldConfigTwoDefaultValueDefault)
})).and(zod.object({
  "type": zod.enum(['text', 'multiline'])
}))

export type TextFieldConfig = zod.input<typeof TextFieldConfig>;
export type TextFieldConfigOutput = zod.output<typeof TextFieldConfig>;
