/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const ToggleSubmissionApprovalStatusParams = zod.object({
  "form": zod.string(),
  "fv": zod.string().optional(),
  "sv": zod.string().optional()
})

export type ToggleSubmissionApprovalStatusParams = zod.input<typeof ToggleSubmissionApprovalStatusParams>;
export type ToggleSubmissionApprovalStatusParamsOutput = zod.output<typeof ToggleSubmissionApprovalStatusParams>;
