/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import {
  GetFacilityInfo200,
  IndexRange,
  LookupFormSubmissions200,
  PerformSubmissionDeletion202,
  SubmissionDataResponse,
  SubmissionVersionLookup
} from '../../../../../../libs/sdk/models';
import type {
  FindSparseIndexRangesParams,
  GetFacilityInfo200Output,
  GetFacilityInfoParams,
  GetSubmissionDataParams,
  LookupFormSubmissions200Output,
  LookupFormSubmissionsParams,
  LookupSubmissionVersionsParams,
  PerformSubmissionDeletion202Output,
  PerformSubmissionDeletionParams,
  SubmissionDataResponseOutput,
  ToggleSubmissionApprovalStatusParams
} from '../../../../../../libs/sdk/models';

import {
  map
} from 'rxjs';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      preserveRequiredNullables &&
      value === null &&
      requiredNullableKeys.has(key)
    ) {
      filteredParams[key] = null;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}





@Injectable()
export class SubmissionsService {
  private readonly http = inject(HttpClient);
/**
 * Retrieve the facility information, via standard tags or custom tags
 * @summary Get facility info
 */
 getFacilityInfo(submission: number,
    form: string,
    params?: GetFacilityInfoParams, options?: HttpClientBodyOptions): Observable<GetFacilityInfo200Output>;
 getFacilityInfo(submission: number,
    form: string,
    params?: GetFacilityInfoParams, options?: HttpClientEventOptions): Observable<HttpEvent<GetFacilityInfo200Output>>;
 getFacilityInfo(submission: number,
    form: string,
    params?: GetFacilityInfoParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<GetFacilityInfo200Output>>;
  getFacilityInfo(
    submission: number,
    form: string,
    params?: GetFacilityInfoParams, options?: HttpClientObserveOptions): Observable<GetFacilityInfo200Output | HttpEvent<GetFacilityInfo200Output> | AngularHttpResponse<GetFacilityInfo200Output>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<GetFacilityInfo200Output>(
      `/api/submissions/${submission}/forms/${form}/facility-info`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: GetFacilityInfo200.parse(event.body) }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.get<GetFacilityInfo200Output>(
      `/api/submissions/${submission}/forms/${form}/facility-info`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    ).pipe(map(response => response.clone({ body: GetFacilityInfo200.parse(response.body) })));
    }

    return this.http.get<GetFacilityInfo200Output>(
      `/api/submissions/${submission}/forms/${form}/facility-info`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    ).pipe(map(data => GetFacilityInfo200.parse(data)));
  }
/**
 * Fetch the responses for a particular submission
 * @summary Get submission data
 */
 getSubmissionData(submission: number,
    form: string,
    params?: GetSubmissionDataParams, options?: HttpClientBodyOptions): Observable<SubmissionDataResponseOutput>;
 getSubmissionData(submission: number,
    form: string,
    params?: GetSubmissionDataParams, options?: HttpClientEventOptions): Observable<HttpEvent<SubmissionDataResponseOutput>>;
 getSubmissionData(submission: number,
    form: string,
    params?: GetSubmissionDataParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<SubmissionDataResponseOutput>>;
  getSubmissionData(
    submission: number,
    form: string,
    params?: GetSubmissionDataParams, options?: HttpClientObserveOptions): Observable<SubmissionDataResponseOutput | HttpEvent<SubmissionDataResponseOutput> | AngularHttpResponse<SubmissionDataResponseOutput>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<SubmissionDataResponseOutput>(
      `/api/submissions/${submission}/forms/${form}`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: SubmissionDataResponse.parse(event.body) }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.get<SubmissionDataResponseOutput>(
      `/api/submissions/${submission}/forms/${form}`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    ).pipe(map(response => response.clone({ body: SubmissionDataResponse.parse(response.body) })));
    }

    return this.http.get<SubmissionDataResponseOutput>(
      `/api/submissions/${submission}/forms/${form}`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    ).pipe(map(data => SubmissionDataResponse.parse(data)));
  }
/**
 * Lookup the versions for a submission
 * @summary Lookup submission versions
 */
 lookupSubmissionVersions<TData = SubmissionVersionLookup[]>(submission: number,
    form: string,
    params?: LookupSubmissionVersionsParams, options?: HttpClientBodyOptions): Observable<TData>;
 lookupSubmissionVersions<TData = SubmissionVersionLookup[]>(submission: number,
    form: string,
    params?: LookupSubmissionVersionsParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 lookupSubmissionVersions<TData = SubmissionVersionLookup[]>(submission: number,
    form: string,
    params?: LookupSubmissionVersionsParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  lookupSubmissionVersions<TData = SubmissionVersionLookup[]>(
    submission: number,
    form: string,
    params?: LookupSubmissionVersionsParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/submissions/${submission}/forms/${form}/lookup`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/submissions/${submission}/forms/${form}/lookup`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/submissions/${submission}/forms/${form}/lookup`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
/**
 * Deletes a submission from a form, either from all form versions, or a for a particular form version or for a particular submission version
 * @summary Delete submission
 */
 performSubmissionDeletion(submission: number,
    params: PerformSubmissionDeletionParams, options?: HttpClientBodyOptions): Observable<PerformSubmissionDeletion202Output>;
 performSubmissionDeletion(submission: number,
    params: PerformSubmissionDeletionParams, options?: HttpClientEventOptions): Observable<HttpEvent<PerformSubmissionDeletion202Output>>;
 performSubmissionDeletion(submission: number,
    params: PerformSubmissionDeletionParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<PerformSubmissionDeletion202Output>>;
  performSubmissionDeletion(
    submission: number,
    params: PerformSubmissionDeletionParams, options?: HttpClientObserveOptions): Observable<PerformSubmissionDeletion202Output | HttpEvent<PerformSubmissionDeletion202Output> | AngularHttpResponse<PerformSubmissionDeletion202Output>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.delete<PerformSubmissionDeletion202Output>(
      `/api/submissions/${submission}`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: PerformSubmissionDeletion202.parse(event.body) }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.delete<PerformSubmissionDeletion202Output>(
      `/api/submissions/${submission}`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    ).pipe(map(response => response.clone({ body: PerformSubmissionDeletion202.parse(response.body) })));
    }

    return this.http.delete<PerformSubmissionDeletion202Output>(
      `/api/submissions/${submission}`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    ).pipe(map(data => PerformSubmissionDeletion202.parse(data)));
  }
/**
 * Toggles the approval status of a submission for a given form and index.
 * @summary Toggle approval status
 */
 toggleSubmissionApprovalStatus<TData = void>(submission: number,
    params: ToggleSubmissionApprovalStatusParams, options?: HttpClientBodyOptions): Observable<TData>;
 toggleSubmissionApprovalStatus<TData = void>(submission: number,
    params: ToggleSubmissionApprovalStatusParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 toggleSubmissionApprovalStatus<TData = void>(submission: number,
    params: ToggleSubmissionApprovalStatusParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  toggleSubmissionApprovalStatus<TData = void>(
    submission: number,
    params: ToggleSubmissionApprovalStatusParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/submissions/${submission}/toggle-approval`,
      undefined,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/submissions/${submission}/toggle-approval`,
      undefined,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.patch<TData>(
      `/api/submissions/${submission}/toggle-approval`,
      undefined,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
/**
 * Find sparse submission index ranges
 * @summary Find index ranges
 */
 findSparseIndexRanges<TData = IndexRange[]>(params: FindSparseIndexRangesParams, options?: HttpClientBodyOptions): Observable<TData>;
 findSparseIndexRanges<TData = IndexRange[]>(params: FindSparseIndexRangesParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 findSparseIndexRanges<TData = IndexRange[]>(params: FindSparseIndexRangesParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  findSparseIndexRanges<TData = IndexRange[]>(
    params: FindSparseIndexRangesParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/submissions/index-ranges`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/submissions/index-ranges`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/submissions/index-ranges`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
/**
 * Lookup all form submissions, with paginated results
 * @summary Lookup submissions
 */
 lookupFormSubmissions(params?: LookupFormSubmissionsParams, options?: HttpClientBodyOptions): Observable<LookupFormSubmissions200Output>;
 lookupFormSubmissions(params?: LookupFormSubmissionsParams, options?: HttpClientEventOptions): Observable<HttpEvent<LookupFormSubmissions200Output>>;
 lookupFormSubmissions(params?: LookupFormSubmissionsParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<LookupFormSubmissions200Output>>;
  lookupFormSubmissions(
    params?: LookupFormSubmissionsParams, options?: HttpClientObserveOptions): Observable<LookupFormSubmissions200Output | HttpEvent<LookupFormSubmissions200Output> | AngularHttpResponse<LookupFormSubmissions200Output>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<LookupFormSubmissions200Output>(
      `/api/submissions/lookup`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: LookupFormSubmissions200.parse(event.body) }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.get<LookupFormSubmissions200Output>(
      `/api/submissions/lookup`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    ).pipe(map(response => response.clone({ body: LookupFormSubmissions200.parse(response.body) })));
    }

    return this.http.get<LookupFormSubmissions200Output>(
      `/api/submissions/lookup`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    ).pipe(map(data => LookupFormSubmissions200.parse(data)));
  }
};

