/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithSubmissionItemRequestBuilder, WithSubmissionItemRequestBuilderNavigationMetadata, WithSubmissionItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { LookupRequestBuilderRequestsMetadata, type LookupRequestBuilder } from './lookup/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/submissions
 */
export interface SubmissionsRequestBuilder extends BaseRequestBuilder<SubmissionsRequestBuilder> {
    /**
     * The lookup property
     */
    get lookup(): LookupRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.submissions.item collection
     * @param submission The submission index
     * @returns {WithSubmissionItemRequestBuilder}
     */
     bySubmission(submission: number) : WithSubmissionItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SubmissionsRequestBuilderUriTemplate = "{+baseurl}/api/submissions";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SubmissionsRequestBuilderNavigationMetadata: Record<Exclude<keyof SubmissionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySubmission: {
        requestsMetadata: WithSubmissionItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithSubmissionItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["submission"],
    },
    lookup: {
        requestsMetadata: LookupRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
