/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Lookup_currentVersion}
 */
// @ts-ignore
export function createLookup_currentVersionFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLookup_currentVersion;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Lookup}
 */
// @ts-ignore
export function createLookupFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLookup;
}
/**
 * The deserialization information for the current model
 * @param Lookup The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLookup(lookup: Partial<Lookup> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "currentVersion": n => { lookup.currentVersion = n.getObjectValue<Lookup_currentVersion>(createLookup_currentVersionFromDiscriminatorValue); },
        "formVersion": n => { lookup.formVersion = n.getStringValue(); },
        "index": n => { lookup.index = n.getNumberValue(); },
        "recordedAt": n => { lookup.recordedAt = n.getDateValue(); },
        "updatedAt": n => { lookup.updatedAt = n.getDateValue(); },
        "validationCode": n => { lookup.validationCode = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Lookup_currentVersion The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLookup_currentVersion(lookup_currentVersion: Partial<Lookup_currentVersion> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { lookup_currentVersion.id = n.getGuidValue(); },
    }
}
export interface Lookup extends AdditionalDataHolder, Parsable {
    /**
     * The currentVersion property
     */
    currentVersion?: Lookup_currentVersion | null;
    /**
     * The formVersion property
     */
    formVersion?: string | null;
    /**
     * The index property
     */
    index?: number | null;
    /**
     * The recordedAt property
     */
    recordedAt?: Date | null;
    /**
     * The updatedAt property
     */
    updatedAt?: Date | null;
    /**
     * The validationCode property
     */
    validationCode?: string | null;
}
export interface Lookup_currentVersion extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
}
/**
 * Builds and executes requests for operations under /api/submissions/lookup
 */
export interface LookupRequestBuilder extends BaseRequestBuilder<LookupRequestBuilder> {
    /**
     * Lookup all form submissions, with paginated results
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Lookup[]>}
     */
     get(requestConfiguration?: RequestConfiguration<LookupRequestBuilderGetQueryParameters> | undefined) : Promise<Lookup[] | undefined>;
    /**
     * Lookup all form submissions, with paginated results
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<LookupRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Lookup all form submissions, with paginated results
 */
export interface LookupRequestBuilderGetQueryParameters {
    /**
     * A form identifier
     */
    form?: string;
    /**
     * A form version identifier
     */
    fv?: Guid;
    /**
     * Pagination result size
     */
    limit?: number;
    /**
     * Pagination page offset
     */
    page?: number;
    /**
     * A JSON string expressing sorting orders
     */
    sort?: string;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Lookup The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLookup(writer: SerializationWriter, lookup: Partial<Lookup> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!lookup || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Lookup_currentVersion>("currentVersion", lookup.currentVersion, serializeLookup_currentVersion);
    writer.writeStringValue("formVersion", lookup.formVersion);
    writer.writeNumberValue("index", lookup.index);
    writer.writeDateValue("recordedAt", lookup.recordedAt);
    writer.writeDateValue("updatedAt", lookup.updatedAt);
    writer.writeStringValue("validationCode", lookup.validationCode);
    writer.writeAdditionalData(lookup.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Lookup_currentVersion The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLookup_currentVersion(writer: SerializationWriter, lookup_currentVersion: Partial<Lookup_currentVersion> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!lookup_currentVersion || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", lookup_currentVersion.id);
    writer.writeAdditionalData(lookup_currentVersion.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const LookupRequestBuilderUriTemplate = "{+baseurl}/api/submissions/lookup{?form*,fv*,limit*,page*,sort*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const LookupRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: LookupRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createLookupFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
