/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * CivilIO API
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import {
  ArchivedFormVersionDefinition,
  AvailabilityResponse,
  CreateNewForm201,
  FormLookup,
  FormVersionDefinition,
  FormVersionLookup,
  LibraryItem
} from '../../../../../../libs/sdk/models/index.zod';
import type {
  AvailabilityResponseOutput,
  CreateNewForm201Output,
  CreateNewFormBody,
  FindFormDefinitionByVersionParams,
  IsFormTitleAvailableParams,
  IsSlugAvailableParams,
  UpdateFormDefinitionRequest
} from '../../../../../../libs/sdk/models/index.zod';

import {
  map
} from 'rxjs';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
): Record<string, AngularHttpParamValueWithNullable> {
  const filteredParams: Record<string, AngularHttpParamValueWithNullable> = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      preserveRequiredNullables &&
      value === null &&
      requiredNullableKeys.has(key)
    ) {
      filteredParams[key] = value;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}





@Injectable()
export class FormsService {
  private readonly http = inject(HttpClient);
/**
 * Update a form version's definition
 * @summary Update form definition
 */
 updateFormVersionDefinition<TData = void>(form: string,
    version: string,
    updateFormDefinitionRequest: UpdateFormDefinitionRequest, options?: HttpClientBodyOptions): Observable<TData>;
 updateFormVersionDefinition<TData = void>(form: string,
    version: string,
    updateFormDefinitionRequest: UpdateFormDefinitionRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 updateFormVersionDefinition<TData = void>(form: string,
    version: string,
    updateFormDefinitionRequest: UpdateFormDefinitionRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  updateFormVersionDefinition<TData = void>(
    form: string,
    version: string,
    updateFormDefinitionRequest: UpdateFormDefinitionRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
      `/api/forms/${form}/${version}/definition`,
      updateFormDefinitionRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
      `/api/forms/${form}/${version}/definition`,
      updateFormDefinitionRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.put<TData>(
      `/api/forms/${form}/${version}/definition`,
      updateFormDefinitionRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Get a form's definition by version
 * @summary Get form version definition
 */
 findFormDefinitionByVersion<TData = FormVersionDefinition | ArchivedFormVersionDefinition>(form: string,
    params?: FindFormDefinitionByVersionParams, options?: HttpClientBodyOptions): Observable<TData>;
 findFormDefinitionByVersion<TData = FormVersionDefinition | ArchivedFormVersionDefinition>(form: string,
    params?: FindFormDefinitionByVersionParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 findFormDefinitionByVersion<TData = FormVersionDefinition | ArchivedFormVersionDefinition>(form: string,
    params?: FindFormDefinitionByVersionParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  findFormDefinitionByVersion<TData = FormVersionDefinition | ArchivedFormVersionDefinition>(
    form: string,
    params?: FindFormDefinitionByVersionParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/forms/${form}/definition`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/forms/${form}/definition`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/forms/${form}/definition`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
/**
 * @summary Toggle a form's archived status
 */
 toggleArchivedStatus<TData = void>(form: string, options?: HttpClientBodyOptions): Observable<TData>;
 toggleArchivedStatus<TData = void>(form: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 toggleArchivedStatus<TData = void>(form: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  toggleArchivedStatus<TData = void>(
    form: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/forms/${form}/toggle-archive`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/forms/${form}/toggle-archive`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/forms/${form}/toggle-archive`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Lookup versions for a form using its slug
 * @summary Lookup form versions
 */
 lookupFormVersions<TData = FormVersionLookup[]>(form: string, options?: HttpClientBodyOptions): Observable<TData>;
 lookupFormVersions<TData = FormVersionLookup[]>(form: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 lookupFormVersions<TData = FormVersionLookup[]>(form: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  lookupFormVersions<TData = FormVersionLookup[]>(
    form: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/forms/${form}/versions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/forms/${form}/versions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/forms/${form}/versions`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Create form
 */
 createNewForm<TData = CreateNewForm201Output>(createNewFormBody: CreateNewFormBody, options?: HttpClientBodyOptions): Observable<TData>;
 createNewForm<TData = CreateNewForm201Output>(createNewFormBody: CreateNewFormBody, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 createNewForm<TData = CreateNewForm201Output>(createNewFormBody: CreateNewFormBody, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  createNewForm<TData = CreateNewForm201Output>(
    createNewFormBody: CreateNewFormBody, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/forms`,
      createNewFormBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: CreateNewForm201.parse(event.body) as TData }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/forms`,
      createNewFormBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    ).pipe(map(response => response.clone({ body: CreateNewForm201.parse(response.body) as TData })));
    }

    return this.http.post<TData>(
      `/api/forms`,
      createNewFormBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    ).pipe(map(data => CreateNewForm201.parse(data) as TData));
  }
/**
 * @summary Lookup form items library
 */
 findLibraryItems<TData = LibraryItem[]>( options?: HttpClientBodyOptions): Observable<TData>;
 findLibraryItems<TData = LibraryItem[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 findLibraryItems<TData = LibraryItem[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  findLibraryItems<TData = LibraryItem[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/forms/library`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/forms/library`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/forms/library`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Lookup all forms
 * @summary Lookup forms
 */
 lookupForms<TData = FormLookup[]>( options?: HttpClientBodyOptions): Observable<TData>;
 lookupForms<TData = FormLookup[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 lookupForms<TData = FormLookup[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  lookupForms<TData = FormLookup[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/forms/lookup`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/forms/lookup`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/forms/lookup`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Check whether a form slug is available
 * @deprecated
 * @summary Check slug
 */
 isSlugAvailable<TData = AvailabilityResponseOutput>(params: IsSlugAvailableParams, options?: HttpClientBodyOptions): Observable<TData>;
 isSlugAvailable<TData = AvailabilityResponseOutput>(params: IsSlugAvailableParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 isSlugAvailable<TData = AvailabilityResponseOutput>(params: IsSlugAvailableParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  isSlugAvailable<TData = AvailabilityResponseOutput>(
    params: IsSlugAvailableParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/forms/slug-check`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: AvailabilityResponse.parse(event.body) as TData }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/forms/slug-check`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    ).pipe(map(response => response.clone({ body: AvailabilityResponse.parse(response.body) as TData })));
    }

    return this.http.get<TData>(
      `/api/forms/slug-check`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    ).pipe(map(data => AvailabilityResponse.parse(data) as TData));
  }
/**
 * @summary Check title availability
 */
 isFormTitleAvailable<TData = AvailabilityResponseOutput>(params: IsFormTitleAvailableParams, options?: HttpClientBodyOptions): Observable<TData>;
 isFormTitleAvailable<TData = AvailabilityResponseOutput>(params: IsFormTitleAvailableParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 isFormTitleAvailable<TData = AvailabilityResponseOutput>(params: IsFormTitleAvailableParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  isFormTitleAvailable<TData = AvailabilityResponseOutput>(
    params: IsFormTitleAvailableParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/forms/title-check`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: AvailabilityResponse.parse(event.body) as TData }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/forms/title-check`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    ).pipe(map(response => response.clone({ body: AvailabilityResponse.parse(response.body) as TData })));
    }

    return this.http.get<TData>(
      `/api/forms/title-check`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    ).pipe(map(data => AvailabilityResponse.parse(data) as TData));
  }
};

