name: Run CI Tests 🧪

permissions:
  contents: read
on:
  push:
    branches:
      - CI-*
    paths:
      - src/main/java/**/*.*
      - src/main/test/**/*.*
      - .github/workflows/**.*
  workflow_dispatch:

jobs:
  test:
    env:
      APP_NAME: ${{ vars.APP_NAME }}
      LOG_LEVEL: ${{ vars.LOG_LEVEL }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    name: Testing on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo
      - uses: actions/setup-java@v4.7.0
        name: Setup Java
        with:
          java-version-file: .tool-versions
          distribution: graalvm
          cache: gradle
      - name: Run tests
        run: gradle test