/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ToggleApprovalRequestBuilderRequestsMetadata, type ToggleApprovalRequestBuilder } from './toggleApproval/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BackedModel, type BackingStore, type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithSubmission_field_relevance}
 */
// @ts-ignore
export function createWithSubmission_field_relevanceFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithSubmission_field_relevance;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithSubmission_field}
 */
// @ts-ignore
export function createWithSubmission_fieldFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithSubmission_field;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithSubmissionDeleteResponse}
 */
// @ts-ignore
export function createWithSubmissionDeleteResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithSubmissionDeleteResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithSubmission}
 */
// @ts-ignore
export function createWithSubmissionFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithSubmission;
}
/**
 * The deserialization information for the current model
 * @param WithSubmission The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithSubmission(withSubmission: Partial<WithSubmission> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "backingStoreEnabled": n => { withSubmission.backingStoreEnabled = true; },
        "field": n => { withSubmission.field = n.getObjectValue<WithSubmission_field>(createWithSubmission_fieldFromDiscriminatorValue); },
        "fieldId": n => { withSubmission.fieldId = n.getStringValue(); },
        "formVersion": n => { withSubmission.formVersion = n.getStringValue(); },
        "responseVersionId": n => { withSubmission.responseVersionId = n.getStringValue(); },
        "submissionIndex": n => { withSubmission.submissionIndex = n.getNumberValue(); },
        "value": n => { withSubmission.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param WithSubmission_field The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithSubmission_field(withSubmission_field: Partial<WithSubmission_field> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "backingStoreEnabled": n => { withSubmission_field.backingStoreEnabled = true; },
        "createdAt": n => { withSubmission_field.createdAt = n.getDateValue(); },
        "description": n => { withSubmission_field.description = n.getStringValue(); },
        "fieldId": n => { withSubmission_field.fieldId = n.getStringValue(); },
        "fieldType": n => { withSubmission_field.fieldType = n.getEnumValue<WithSubmission_field_fieldType>(WithSubmission_field_fieldTypeObject); },
        "formVersion": n => { withSubmission_field.formVersion = n.getStringValue(); },
        "readonly": n => { withSubmission_field.readonly = n.getBooleanValue(); },
        "relevance": n => { withSubmission_field.relevance = n.getObjectValue<WithSubmission_field_relevance>(createWithSubmission_field_relevanceFromDiscriminatorValue); },
        "sectionKey": n => { withSubmission_field.sectionKey = n.getStringValue(); },
        "span": n => { withSubmission_field.span = n.getNumberValue(); },
        "title": n => { withSubmission_field.title = n.getStringValue(); },
        "updatedAt": n => { withSubmission_field.updatedAt = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param WithSubmission_field_relevance The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithSubmission_field_relevance(withSubmission_field_relevance: Partial<WithSubmission_field_relevance> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "backingStoreEnabled": n => { withSubmission_field_relevance.backingStoreEnabled = true; },
    }
}
/**
 * The deserialization information for the current model
 * @param WithSubmissionDeleteResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithSubmissionDeleteResponse(withSubmissionDeleteResponse: Partial<WithSubmissionDeleteResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "backingStoreEnabled": n => { withSubmissionDeleteResponse.backingStoreEnabled = true; },
        "responsesDeleted": n => { withSubmissionDeleteResponse.responsesDeleted = n.getNumberValue(); },
        "versionsDeleted": n => { withSubmissionDeleteResponse.versionsDeleted = n.getNumberValue(); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithSubmission The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithSubmission(writer: SerializationWriter, withSubmission: Partial<WithSubmission> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!withSubmission || isSerializingDerivedType) { return; }
    writer.writeObjectValue<WithSubmission_field>("field", withSubmission.field, serializeWithSubmission_field);
    writer.writeStringValue("fieldId", withSubmission.fieldId);
    writer.writeStringValue("formVersion", withSubmission.formVersion);
    writer.writeStringValue("responseVersionId", withSubmission.responseVersionId);
    writer.writeNumberValue("submissionIndex", withSubmission.submissionIndex);
    writer.writeStringValue("value", withSubmission.value);
    writer.writeAdditionalData(withSubmission.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithSubmission_field The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithSubmission_field(writer: SerializationWriter, withSubmission_field: Partial<WithSubmission_field> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!withSubmission_field || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", withSubmission_field.createdAt);
    writer.writeStringValue("description", withSubmission_field.description);
    writer.writeStringValue("fieldId", withSubmission_field.fieldId);
    writer.writeEnumValue<WithSubmission_field_fieldType>("fieldType", withSubmission_field.fieldType);
    writer.writeStringValue("formVersion", withSubmission_field.formVersion);
    writer.writeBooleanValue("readonly", withSubmission_field.readonly);
    writer.writeObjectValue<WithSubmission_field_relevance>("relevance", withSubmission_field.relevance, serializeWithSubmission_field_relevance);
    writer.writeStringValue("sectionKey", withSubmission_field.sectionKey);
    writer.writeNumberValue("span", withSubmission_field.span);
    writer.writeStringValue("title", withSubmission_field.title);
    writer.writeDateValue("updatedAt", withSubmission_field.updatedAt);
    writer.writeAdditionalData(withSubmission_field.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithSubmission_field_relevance The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithSubmission_field_relevance(writer: SerializationWriter, withSubmission_field_relevance: Partial<WithSubmission_field_relevance> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!withSubmission_field_relevance || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(withSubmission_field_relevance.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithSubmissionDeleteResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithSubmissionDeleteResponse(writer: SerializationWriter, withSubmissionDeleteResponse: Partial<WithSubmissionDeleteResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!withSubmissionDeleteResponse || isSerializingDerivedType) { return; }
    writer.writeNumberValue("responsesDeleted", withSubmissionDeleteResponse.responsesDeleted);
    writer.writeNumberValue("versionsDeleted", withSubmissionDeleteResponse.versionsDeleted);
    writer.writeAdditionalData(withSubmissionDeleteResponse.additionalData);
}
export interface WithSubmission extends AdditionalDataHolder, BackedModel, Parsable {
    /**
     * Stores model information.
     */
    backingStoreEnabled?: boolean | null;
    /**
     * The field property
     */
    field?: WithSubmission_field | null;
    /**
     * The fieldId property
     */
    fieldId?: string | null;
    /**
     * The formVersion property
     */
    formVersion?: string | null;
    /**
     * The responseVersionId property
     */
    responseVersionId?: string | null;
    /**
     * The submissionIndex property
     */
    submissionIndex?: number | null;
    /**
     * The value property
     */
    value?: string | null;
}
export interface WithSubmission_field extends AdditionalDataHolder, BackedModel, Parsable {
    /**
     * Stores model information.
     */
    backingStoreEnabled?: boolean | null;
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The fieldId property
     */
    fieldId?: string | null;
    /**
     * The fieldType property
     */
    fieldType?: WithSubmission_field_fieldType | null;
    /**
     * The formVersion property
     */
    formVersion?: string | null;
    /**
     * The readonly property
     */
    readonly?: boolean | null;
    /**
     * The relevance property
     */
    relevance?: WithSubmission_field_relevance | null;
    /**
     * The sectionKey property
     */
    sectionKey?: string | null;
    /**
     * The span property
     */
    span?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The updatedAt property
     */
    updatedAt?: Date | null;
}
export type WithSubmission_field_fieldType = (typeof WithSubmission_field_fieldTypeObject)[keyof typeof WithSubmission_field_fieldTypeObject];
export interface WithSubmission_field_relevance extends AdditionalDataHolder, BackedModel, Parsable {
    /**
     * Stores model information.
     */
    backingStoreEnabled?: boolean | null;
}
/**
 * Summary of the deletion
 */
export interface WithSubmissionDeleteResponse extends AdditionalDataHolder, BackedModel, Parsable {
    /**
     * Stores model information.
     */
    backingStoreEnabled?: boolean | null;
    /**
     * The number of response values deleted
     */
    responsesDeleted?: number | null;
    /**
     * The number of submission versions deleted
     */
    versionsDeleted?: number | null;
}
/**
 * Builds and executes requests for operations under /api/submissions/{submission}
 */
export interface WithSubmissionItemRequestBuilder extends BaseRequestBuilder<WithSubmissionItemRequestBuilder> {
    /**
     * The toggleApproval property
     */
    get toggleApproval(): ToggleApprovalRequestBuilder;
    /**
     * Deletes a submission from a form, either from all form versions, or a for a particular form version or for a particular submission version
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WithSubmissionDeleteResponse>}
     */
     delete(requestConfiguration?: RequestConfiguration<WithSubmissionItemRequestBuilderDeleteQueryParameters> | undefined) : Promise<WithSubmissionDeleteResponse | undefined>;
    /**
     * Fetch the responses for a particular submission
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WithSubmission[]>}
     */
     get(requestConfiguration?: RequestConfiguration<WithSubmissionItemRequestBuilderGetQueryParameters> | undefined) : Promise<WithSubmission[] | undefined>;
    /**
     * Deletes a submission from a form, either from all form versions, or a for a particular form version or for a particular submission version
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<WithSubmissionItemRequestBuilderDeleteQueryParameters> | undefined) : RequestInformation;
    /**
     * Fetch the responses for a particular submission
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<WithSubmissionItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Deletes a submission from a form, either from all form versions, or a for a particular form version or for a particular submission version
 */
export interface WithSubmissionItemRequestBuilderDeleteQueryParameters {
    /**
     * The form slug to identify the form
     */
    form?: string;
    /**
     * The form version to use, leave empty to use the current version
     */
    fv?: string;
    /**
     * The submission version to use, leave empty to delete all versions, use "current" to delete the current version
     */
    sv?: string;
}
/**
 * Fetch the responses for a particular submission
 */
export interface WithSubmissionItemRequestBuilderGetQueryParameters {
    form?: string;
    fv?: Guid;
    sv?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const WithSubmissionItemRequestBuilderUriTemplate = "{+baseurl}/api/submissions/{submission}?form={form}{&fv*,sv*}";
export const WithSubmission_field_fieldTypeObject = {
    Number: "number",
    Boolean: "boolean",
    Date: "date",
    File: "file",
    Url: "url",
    Text: "text",
    Multiline: "multiline",
    DateTime: "date-time",
    Email: "email",
    GeoPoint: "geo-point",
    SingleSelect: "single-select",
    MultiSelect: "multi-select",
    Phone: "phone",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithSubmissionItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithSubmissionItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    toggleApproval: {
        requestsMetadata: ToggleApprovalRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithSubmissionItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithSubmissionItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createWithSubmissionDeleteResponseFromDiscriminatorValue,
    },
    get: {
        uriTemplate: WithSubmissionItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createWithSubmissionFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
